### ISSUE TITLE
Can you please add a compact help version with flag -h?

### ISSUE THREAD

**Issue by saifali-ch** [Genivia/ugrep#104]
### I'm very used to -h flag. I think many others as well.
While in the case of ugrep it really annoys me when using -h option.
![image](https://user-images.githubusercontent.com/54573967/107449064-b3a88700-6b64-11eb-9364-34e91c004846.png)

**Suggestion**
1. Ether introduce a new compact version of help with -h flag. like [ripgrep](https://github.com/BurntSushi/ripgrep).
2. Or please at least make -h behave as --help.

Hope you will understand my request.

**Comment by genivia-inc** [comment]
Sorry, cannot do that because that breaks compatibility with GNU grep.

You can use `-?` which many (but not all) *nix tools support.

**Comment by saifali-ch** [comment]
## Luckily, I have GNU grep binary 
### And grep -? produces

![image](https://user-images.githubusercontent.com/54573967/107450864-ee5fee80-6b67-11eb-9986-bb1658a20277.png)

**Comment by genivia-inc** [comment]
Like I said, not all *nix tools support `-?` but some do.

Changing the `-h` option in `ugrep` is not negotiable, because `-h` is already assigned the same function a grep.

One of the problems with other grep-like tools is their incompatibility with grep. So they are not drop-in replacements (e.g. `-h` does not behave the same!), but ugrep should be.

**Comment by saifali-ch** [comment]
I'm really sorry, I was unaware that ugrep's -h option is already assigned to **--no-filename** same like **grep**.

Thank you super much @genivia-inc
**Jazzak Allah**

**Comment by genivia-inc** [comment]
Thank you for your feedback and suggestions!
