### ISSUE TITLE
--hidden overrides --ignore-files

### ISSUE THREAD

**Issue by myelsukov** [Genivia/ugrep#117]
This works as expected. Files from the `.git` directory are ignored
```
ugrep --files-with-matches --ignore-files=.gitignore --stats PATTERN
```

This prints files from the `.git` directory:
```
ugrep --files-with-matches --ignore-files=.gitignore --hidden --stats PATTERN
```
Even though `--stats` says: `--exclude-dir='**/.git'`

**Comment by genivia-inc** [comment]
Thanks for the feedback. I will have to look into this more closely.

**Comment by genivia-inc** [comment]
I don't see the same behavior. Please note that `--stats` should also indicate that a `.gitignore` was found and used in the search. All `.gitigore` files on the path down will be used, not any up to the root (for the important reason to avoid people from complaining why their search did not work):
~~~
$ ugrep -2 --ignore-files --hidden 'AvailabilityInternal.h' -l --stats
Searched 406 files with 8 threads in 19 directories: 0 matching
The following pathname selections and restrictions were applied:
  --hidden
  --depth=2
  --ignore-files='.gitignore'
    ./.gitignore exclusions were applied to .
Lines matched if:
  "AvailabilityInternal.h" matches
~~~

**Comment by myelsukov** [comment]
Running this in the freshly cloned `ugrep` directory:

```
> ugrep --ignore-files --hidden 'Y40000' -l --stats
.git/objects/pack/pack-7b2ac1d2cbb73c5eb022c09ca421c84f7f03947e.pack
Searched 1161 files with 16 threads in 50 directories: 1 matching
The following pathname selections and restrictions were applied:
  --hidden
  --ignore-files='.gitignore'
    ./.gitignore exclusions were applied to .
Lines matched if:
  "Y40000" matches
```

**Comment by myelsukov** [comment]
It's a mystery, but I can't reproduce it anymore either. Sorry for confusion.

**Comment by wimstefan** [comment]
I'm also experiencing the same problem as the OP with the latest ugrep: `ugrep 3.7.1 x86_64-pc-linux-gnu +avx2 +pcre2_jit +zlib +bzip2 +lzma +lz4 +zstd`

@genivia-inc I'm not sure whether to re-open this issue and show the details in here or to open a new issue?

**Comment by genivia-inc** [comment]
I'll take a look at it. It may have to do with the fact that `.git` is seen as a file when used in a .gitignore. Use `.git/` to skip the `.git/` directory.

**Comment by wimstefan** [comment]
OK so we'll continue in this issue ...

Let me share the details then - it's all about the `--hidden` flag which changes things for me:

```sh
ugrep -RIjnkzo --hidden --ignore-files --exclude-dir="^.git/" --stats fzf-l
tmux/tmux-tj.conf:52:3:fzf-l
tmux/tmux-laptop.conf:52:3:fzf-l
tmux/tmux-desktop.conf:52:3:fzf-l
.git/logs/refs/heads/master:10:208:fzf-l
.git/logs/refs/heads/master:11:207:fzf-l
.git/logs/refs/heads/master:20:190:fzf-l
.git/logs/HEAD:10:208:fzf-l
.git/logs/HEAD:11:207:fzf-l
.git/logs/HEAD:20:190:fzf-l
Searched 458 files with 12 threads in 238 directories: 5 matching
The following pathname selections and restrictions were applied:
  --hidden
  --ignore-files='.gitignore'
    ./.gitignore exclusions were applied to .
  --exclude-dir='^.git'
Lines matched if:
  "fzf-l" matches
```

```sh
ugrep -RIjnkzo --ignore-files --exclude-dir="^.git/" --stats fzf-l
tmux/tmux-laptop.conf:52:3:fzf-l
tmux/tmux-tj.conf:52:3:fzf-l
tmux/tmux-desktop.conf:52:3:fzf-l
Searched 21 files with 12 threads in 11 directories: 3 matching
The following pathname selections and restrictions were applied:
  --no-hidden (default)
  --ignore-files='.gitignore'
    ./.gitignore exclusions were applied to .
  --exclude-dir='^.git'
Lines matched if:
  "fzf-l" matches
  ```

As you can see the `--hidden` flag invalidates the `--exclude-dir` flag. I'd like to be able to use both though since I'm after some content in hidden directories as well ...

I hope this makes my problem a bit clearer.

**Comment by genivia-inc** [comment]
Thanks for the details.

Note that `--exclude-dir="^.git/"` includes the .git directory, because it overrides _all_ exclusions with the `^` operator.

Try `--exclude-dir=".git"` or just `-g"^.git/` which is the same (`^` means exclude and `/` means directory).

Or put `.git/` in .gitignore when using `--ignore-files`. Note the trailing `/` which is proper for directories.

Both work for me with and without `--hidden`.

**Comment by wimstefan** [comment]
That would have been to good to be true! :D

I was indeed mixing up the commands in my examples but I had the same result with the correct commands before.
In my use case it stands and falls with `--hidden` ... as soon as that is used the `-g`/`--exclude-dir` flags are ignored (sorry for the pun ;) )

```sh
ugrep -o --ignore-files -g'^.git/' --stats --hidden fzf-l
tmux/tmux-tj.conf:fzf-l
tmux/tmux-desktop.conf:fzf-l
tmux/tmux-laptop.conf:fzf-l
.git/logs/HEAD:fzf-l
.git/logs/HEAD:fzf-l
.git/logs/HEAD:fzf-l
.git/logs/refs/heads/master:fzf-l
.git/logs/refs/heads/master:fzf-l
.git/logs/refs/heads/master:fzf-l
Searched 473 files with 12 threads in 240 directories: 5 matching
The following pathname selections and restrictions were applied:
  --hidden
  --ignore-files='.gitignore'
    ./.gitignore exclusions were applied to .
  --exclude-dir='.git'
Lines matched if:
  "fzf-l" matches
```

```sh
ugrep -o --ignore-files -g'^.git/' --stats  fzf-l
tmux/tmux-tj.conf:fzf-l
tmux/tmux-laptop.conf:fzf-l
tmux/tmux-desktop.conf:fzf-l
Searched 21 files with 12 threads in 11 directories: 3 matching
The following pathname selections and restrictions were applied:
  --no-hidden (default)
  --ignore-files='.gitignore'
    ./.gitignore exclusions were applied to .
  --exclude-dir='.git'
Lines matched if:
  "fzf-l" matches
```

You can see that `--hidden` has highest priority and overrides the other 
flags.

Putting the `.git` directory in `.gitignore` is a workaround indeed but not 
always applicable. And I also think that `--exclude-dir` shouldn't be ignored 
that easily ...

**Comment by genivia-inc** [comment]
Here is my reproducible test on the ugrep GitHub repo contents, so anyone can try this:
~~~
$ cd ~/GitHub/ugrep

$ ugrep --hidden -g'^.git/' -l '' | fgrep git
.gitignore
.gitattributes

$ ugrep --hidden --ignore-files  -l '' | fgrep git
.gitignore
.gitattributes

$ ugrep --hidden --exclude-dir='.git' -l '' | fgrep git
.gitignore
.gitattributes

$ ugrep  -l '' | fgrep git

$ ugrep -g'^.git/' -l '' | fgrep git

$ ugrep --ignore-files -l '' | fgrep git

$ ugrep --hidden -l '' | fgrep git
.gitattributes
.gitignore
.git/packed-refs
.git/config
.git/COMMIT_EDITMSG
.git/ORIG_HEAD
.git/FETCH_HEAD
.git/HEAD
.git/description
.git/index
.git/objects/61/153fa90066b19404bb0dc4c11d4a2ba110bb9e
...etc
~~~
This is with `.git/` added to .gitignore. As expected, .git is not searched unless for the last case with `--hidden` and no exclusions specified, as expected.

**Comment by genivia-inc** [comment]
The logic in ugrep is very clear on this:
~~~
  while ((dirent = readdir(dir)) != NULL)
  {
    if (dirent->d_name[0] != '.' || (flag_hidden && dirent->d_name[1] != '\0' && dirent->d_name[1] != '.'))
    {
      switch (select(level + 1, dirpathname.c_str(), cFileName.c_str(), DIRENT_TYPE_UNKNOWN, inode, info))
      {      ... search(dirpathname.c_str()); ...
~~~
~~~
// select file or directory to search for pattern matches, return SKIP, DIRECTORY or OTHER
Grep::Type Grep::select(size_t level, const char *pathname, const char *basename, int type, ino_t& inode, uint64_t& info, bool is_argument)
{
  if (*basename == '.' && !flag_hidden && !is_argument)
    return Type::SKIP;
  ...
            // check for --exclude-dir and --include-dir constraints if pathname != "."
            if (strcmp(pathname, ".") != 0)
            {
              if (!flag_all_exclude_dir.empty())
              {
                // exclude directories whose pathname matches any one of the --exclude-dir globs unless negated with !
                bool ok = true;
                for (const auto& glob : flag_all_exclude_dir)
                {
                  if (glob.front() == '!')
                  {
                    if (!ok && glob_match(pathname, basename, glob.c_str() + 1))
                      ok = true;
                  }
                  else if (ok && glob_match(pathname, basename, glob.c_str()))
                  {
                    ok = false;
                  }
                }
                if (!ok)
                  return Type::SKIP;
              }
~~~
Directories are searched if they don't start with a `.` or if they do, then `--hidden` must be true and the directory name must not be `.` and not `..` to search the files there. Then the exclude-dir and exclude file constraints are applied.

Dot files on the command line are always searched (is_argument` is true).

The `!` check is for .gitignore files defining overriding ! globs.

If an include glob starts with a dot like `-g".git"` or contains a dotfile like `/.../.git` then `--hidden` will be enabled, because we won't see any .git dirs and files otherwise in the results. This is the _only case_ when `--hidden` is implicitly enabled to avoid losing data and not getting what is expected in the results.

I don't see the problem, unless I'm overlooking something more complicated that is hidden (no pun intended) in the code.

**Comment by wimstefan** [comment]
Oh wow! Thanks for taking the time and be as explicit and as explanatory as you are 🙏

The above examples are indeed reproducible as long as you put `.git/` into `.gitignore`.
If that's not the case the outcome is different - hence with **no** `.gitgnore` entry I get:

```sh
 ugrep --hidden -g'^.git/' -l --stats fzf-l
tmux/tmux-laptop.conf
tmux/tmux-tj.conf
tmux/tmux-desktop.conf
Searched 22 files with 12 threads in 11 directories: 3 matching
The following pathname selections and restrictions were applied:
  --hidden
  --exclude-dir='.git'
Lines matched if:
  "fzf-l" matches
```

```sh
ugrep --hidden --ignore-files -g'^.git/' -l --stats fzf-l
tmux/tmux-laptop.conf
tmux/tmux-desktop.conf
tmux/tmux-tj.conf
.git/logs/HEAD
.git/logs/refs/heads/master
Searched 473 files with 12 threads in 240 directories: 5 matching
The following pathname selections and restrictions were applied:
  --hidden
  --ignore-files='.gitignore'
    ./.gitignore exclusions were applied to .
  --exclude-dir='.git'
Lines matched if:
  "fzf-l" matches
```

Interesting outcome 😏

If I understood and tested it correctly that means I can **not** search in hidden directories (with `--hidden`) respecting an existing `.gitgnore` (with `--ignore-files`) that I can't edit and hence have to exclude `.git` directories with `-g'^.git/'` or `--exclude-dir='.git'` ...

Or am I just thinking to complicated now? 

Background is that I'm trying to use `ugrep` as `grepprg` in `neovim` and I'm searching for the best options to cover the cases above ...

**Comment by wimstefan** [comment]
Oh and I see that you've dove in the `ugrep` code to explain the inner working of it while I was writing my last post :) Many thanks for that. It's way beyond I can comprehend and I'm very grateful that you took the time for that deep argumentation 🙏

I hope I could explain a bit better what I try to achieve with my last post ...

**Comment by genivia-inc** [comment]
Maybe something funny is going on with `--hidden` combined with `--ignore-files` and `-g^` or `--exclude-dir=`. In principle, `--hidden` does not override the latter options in the code flow. Somehow `-g^` or `--exclude-dir=` are not picked up when `--ignore-files` is used. That's more likely.

**Comment by genivia-inc** [comment]
Ah, I see what the problem is. It has nothing to do with `--hidden` or the specific `.git` directory that is hidden. It has to do whether we want a local .gitignore to _replace_ the current exclusions or _add more_ exclusions. The current way this is handled is to let a local .gitignore _replace_ the exclusions. Therefore, if `-g` or `--exclude-dir` is specified, then these are _replaced_ by the .gitignore exclusions. This has nothing to do with `--hidden`, which is why I didn't think there was a problem with `--hidden`. That part works as it should.

If it is more reasonable to _add more_ exclusions as we go deeper into a directory tree when we encounter additional .gitignore files, then we can just "stack" these together by changing two lines of code:
~~~
void Grep::recurse(size_t level, const char *pathname)
{
  ...
          save_all_exclude = std::unique_ptr<std::vector<std::string>>(new std::vector<std::string>);
          save_all_exclude->swap(flag_all_exclude);
          save_all_exclude_dir = std::unique_ptr<std::vector<std::string>>(new std::vector<std::string>);
          save_all_exclude_dir->swap(flag_all_exclude_dir);
~~~
to:
~~~
void Grep::recurse(size_t level, const char *pathname)
{
  ...
          save_all_exclude = std::unique_ptr<std::vector<std::string>>(new std::vector<std::string>(flag_all_exclude));
          save_all_exclude->swap(flag_all_exclude);
          save_all_exclude_dir = std::unique_ptr<std::vector<std::string>>(new std::vector<std::string>(flag_all_exclude_dir));
          save_all_exclude_dir->swap(flag_all_exclude_dir);
~~~
This way, when multiple .gitignore are found in the traversal down the tree branches, then the exclusions are _added on_, not being replaced. When traversing up, the old exclusions are restored (hence `save_all_exclude` and `save_all_exclude_dir` to restore).

If that is not desirable and we want to keep the old behavior, then some additional logic is needed to preserve the command line exclusions (normalized) and use these instead of the previous `flag_all_exclude` and `flag_all_exclude_dir`.

**Comment by wimstefan** [comment]
Thank you so much for the insight!

**Comment by genivia-inc** [comment]
Thanks again for reporting this to make ugrep better.

Multiple .gitignore along a path down a directory tree are unlikely in practice, but possible. If this happens, the likely intent is to apply the exclusions combined. IMHO "extending" seems more natural to me. But "extending" is a choice, just like "overriding" is a choice. With "extending" we may find fewer matching files (more exclusions). With "overriding" we may find too many files than expected. We could even introduce a new option, so the user can select a choice. But I don't want to add options for things that almost never practically happen. In any case, `--stats` reports the exclusions and that is what counts as feedback to the user to understand the results.

So let's adopt "extending". It is intuitive and `--stats` is understandable too. Perhaps `--stats` should be more clear on this, by changing:
~~~
./.gitignore exclusions were applied to .
~~~
to:
~~~
./.gitignore exclusions were applied to . and its subdirectories
~~~
where `.` is a directory, in this case the working directory.

**Comment by wimstefan** [comment]
That is way beyond expectation!
In first place I wanted to understand why things work as they did and after you've kindly taken the time to explain you've even changed the behaviour of the flags 😀
Thank you so much for that!!! 🙏
