### ISSUE TITLE
missing -lboost_regex

### ISSUE THREAD

**Issue by capngp** [Genivia/ugrep#121]
Building ugrep on mint 2.1, downloaded fine, build error, can't find -lboost_regex. Build file output below, autoreconf -fi does not fix.

g++ -std=gnu++11  -Wall -Wextra -Wunused -O2  -L/usr/lib -L/usr/lib -L/usr/lib -L/usr/lib -L/usr/lib -o ugrep ugrep-ugrep.o ugrep-cnf.o ugrep-glob.o ugrep-output.o ugrep-query.o ugrep-screen.o ugrep-stats.o ugrep-vkey.o ugrep-zopen.o -lpthread ../lib/libreflex.a -lpcre2-8  -lboost_regex
/usr/bin/ld: cannot find -lboost_regex
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:392: ugrep] Error 1
make[2]: Leaving directory '/home/pete/ugrep/src'
make[1]: *** [Makefile:459: all-recursive] Error 1
make[1]: Leaving directory '/home/pete/ugrep'
make: *** [Makefile:359: all] Error 2
Failed to build ugrep: please run the following two commands:
$ autoreconf -fi
$ ./build.sh

**Comment by genivia-inc** [comment]
I assume you're using `./configure` instead of `./build.sh`? The `./configure` script uses the `AX_BOOST_REGEX` check defined in `ugrep/m4/ax_boost_regex.m4` which has been around for some time so I do not expect issues with it.

Run `./configure` first to see what is reported for Boost.Regex. Then run `make`.

**Comment by genivia-inc** [comment]
Again, please rerun `./build.sh` or run `./configure` and check what `./configure` shows, whether or not it reports that Boost.Regex was found and share that with us. Maybe it was found but does not compile? If that is the case, there is no fix or solution, because the `ax_boost_regex.m4` is faulty (not our code). Run `./configure --without-boost-regex` to skip Boost.Regex.

**Comment by genivia-inc** [comment]
Since there is not feedback to figure out how to address this issue, I recommend:
~~~
./build.sh --without-boost-regex
~~~
This command (or `./confgure --without-boost-regex; make`) removes the Boost.Regex dependency. This dependency is normally ignored when the PCRE2 library is installed and used with ugrep option `-P`.
