### ISSUE TITLE
ugrep cannot recognize regexes that are valid under `grep -P`

### ISSUE THREAD

**Issue by stdedos** [Genivia/ugrep#122]
```console
$ ugrep -P '/^(?:(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])(\.(?!$)|$)){4}$/'
ugrep: error: error in regex at position 70
-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])(\.(?!$)|$)){4}$
                                invalid syntax___/
```

```console
$ ugrep -P 'rad[\d-]?[^/]+/[^.]+'
ugrep: error: error in regex at position 11
(?mi)rad[\d-]?[^/]+/[^.]+
           \___invalid character class range
```

**Comment by genivia-inc** [comment]
The `(?!$)|$)){4}` part looks suspiciously wrong to me with the `$` misplaced anchors. These should probably be escaped with `\`. Other regex libraries reject this too.

The `[\d-]` syntax is rejected because of the incomplete `-` range. But `[-\d]` is fine. I'll relax the syntax error for this one.

**Comment by genivia-inc** [comment]
It is a bit bizarre to claim that "_ugrep cannot recognize regexes that are valid under grep -P_". So I will close this as invalid unless the title is changed to be more accurate.

**Comment by stdedos** [comment]
I am not that sure with the other one (idk what "mainline grep PCRE" is and accepts it, but

> The `[\d-]` syntax is rejected because of the incomplete `-` range. But `[-\d]` is fine. I'll relax the syntax error for this one.

This is not an error, from a number of online resources, e.g.: https://stackoverflow.com/a/29458719/2309247
However, to be honest, I don't know how to find / I haven't read *the* rules of the specific PCRE library you are using.

**Comment by stdedos** [comment]
> It is a bit bizarre to claim that "_ugrep cannot recognize regexes that are valid under grep -P_".

Well, it can be "bizarre" all it wants; I can use those regexes with "plan" grep, and not with ugrep. ugrep claiming to be a
> compatible grep replacement

makes the title valid.

> So I will close this as invalid unless the title is changed to be more accurate.

Last but not least, if _the title is what bothers you_, you can _of course_ change it yourself to whatever you think it's appropriate to be.

"grep works with those, ugrep doesn't" does not make for a very eloquent title.

**Comment by genivia-inc** [comment]
Not all Perl-based matchers accept the first example either, when checking online regex libraries for compatibility with Perl.

The second example can be supported in ugrep in the future by removing the restriction on `-` at the end of the bracket list. This is a very minor issue that will have to wait until the next update.

> Well, it can be "bizarre" all it wants

Feedback is important for everyone to continue to use and help evolve ugrep by reporting issues when applicable. But this is a very small issue that should have an appropriate title like "_ugrep option -P rejects some special but valid regex patterns_" or something similar rather than "throwing a bomb" so to speak. Not too much to ask IMHO.

> I can use those regexes with "plan" grep, and not with ugrep. ugrep claiming to be a compatible grep replacement

Ugrep is compatible with standard grep options and behaviors. GNU grep even for many years referred to this option as experimental (I assume because PCRE evolved). Note that BSD grep did not support `-P` until a few years ago, though it was a compatible grep implementation too, obviously. It is not part of the POSIX grep standard either (but granted that is a lame argument because POSIX grep is very limited). Grep changed and continues to change over time. Perhaps there will be a time when ugrep will be "the standard" that dictates what GNU grep should do :-)

**Comment by stdedos** [comment]
> > Well, it can be "bizarre" all it wants
> 
> Feedback is important for everyone to continue to use and help evolve ugrep by reporting issues when applicable. But this is a very small issue that should have an appropriate title like "_ugrep option -P rejects some special but valid regex patterns_" or something similar [...]

Great! 😀 That's why _you_ (as the maintainer) are allowed to do pretty much whatever you want - including re-titling the issues 😀 


> [...] rather than "throwing a bomb" so to speak. Not too much to ask IMHO.

Not too much, indeed. However, I hope I wasn't looking at all like that.

Title is (as of now):
> ugrep cannot recognize regexes that are valid under `grep -P`

Which, could have further spoken at a lesser impact (in my head) as
> ugrep cannot recognize _some_ regexes that are valid under `grep -P`

Which, probably, is still not to your liking.

After that (call it half-way blunder), I did give explicit examples, with console output and everything.
I could've given examples that this works with `grep -P`, but it felt redundant - and actually, some of that output is protected by an NDA; so, I would have had to mask it before pasting it.

> > I can use those regexes with "plan" grep, and not with ugrep. ugrep claiming to be a compatible grep replacement
> 
> Ugrep is compatible with standard grep options and behaviors. GNU grep even for many years referred to this option as experimental (I assume because PCRE evolved). Note that BSD grep did not support `-P` until a few years ago, though it was a compatible grep implementation too, obviously. It is not part of the POSIX grep standard either (but granted that is a lame argument because POSIX grep is very limited). Grep changed and continues to change over time. Perhaps there will be a time when ugrep will be "the standard" that dictates what GNU grep should do :-)

I fully agree with the above paragraph. But I also agree that this is a "lame argument", in the sense that both of us are (hopefully) working on good faith:
* You, in good faith, say that this is a super fast and robust-er `grep` in-place replacement (note that here I _did_ change your wording, but I hope this is still somewhat accurate), and
* I, in good faith, tell you that I found _this_ that does not work.

And again: True, the first one _can_ be bogus, but it works nicely in IP address matching (if you haven't guessed already), but the second one is a "clear" ommission.

And no-one said anything about fixing it _immediately_ 😉

**Comment by genivia-inc** [comment]
I've made several improvements for the upcoming v3.1.14 release. The two `-P` patterns now work in the upcoming v3.1.14 release as expected:
~~~
$ echo '123.123.123.123' | ugrep -P '^(?:(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])(\.(?!$)|$)){4}$'
123.123.123.123
$ echo 'rad9a/b' | ugrep -P 'rad[\d-]?[^/]+/[^.]+'
rad9a/b
~~~
