### ISSUE TITLE
Support for zstd compression

### ISSUE THREAD

**Issue by trantor** [Genivia/ugrep#124]
Hello @genivia-inc .
I was looking at the compression formats supported by ugrep and I noticed how zstd is not mentioned.
Would it be feasible to add it? In our organization we've moved from xz to zstd quite a while ago.

Thanks in advance

**Comment by genivia-inc** [comment]
Should be easy to do given that lz4 is already supported. Zstd is (sort of) a rebranded lz4 by the FB folks.

Lz4 is interesting. But technically and factually lz4 simply uses HUGE blocks to speed up decompression. Spatial and temporal locality are easily improved and compression rates too (because of the huge blocks the compression window is larger). I have played around with lz4 and others formats to compare and test to get the best performance. Lz4 uses 4MB blocks to speed up decompression, but that also means that its output has long latencies with big bursts of data. Because of this, lz4 cannot be efficiently pipelined to send decompressed streams to other threads, like we do in ugrep to speed up compressed file searching in parallel. The consuming threads are waiting most of the time for lz4 to finish. This causes a parallel load imbalance. Worse, if a compressed file is less than 4MB, then there is no parallelism at all (to decompress and search the file in parallel). By contrast, ugrep with gz offers the fastest decompressed search, faster than lz4 in my tests. I was surprised by this, because I noticed that Zstd and lz4 show very good benchmarks on their project sites. However, these benchmarks turn out to be not so meaningful, because these were run in "isolation" to just compress/decompress data, i.e. without any further processing e.g. by pipelined threads. Nevertheless, zstd is alright despite this limitation.

**Comment by genivia-inc** [comment]
Good news. The ugrep update v3.2 with support for the [zstd](http://zstd.net) compression format is ready for release very soon. The ugrep.exe Windows versions also include support for zstd.

The initial tests look very good. Searching a 100MB `enwik8` Wikipedia file compressed to 35MB `enwik8.zst` takes only 0.24s on my system:
~~~
$ time ugrep -zc testing enwik8.zst
468
0.215u 0.041s 0:00.24 104.1%	0+0k 0+0io 0pf+0w
~~~
This is faster than searching the gzip-compressed 36MB `enwik8.gz` file, which takes 0.39s on my system:
~~~
$ time ugrep -zc testing enwik8.gz
468
0.388u 0.031s 0:00.39 105.1%	0+0k 0+0io 0pf+0w
~~~
This means that zstd-compressed file searching can be 60% faster than gzip. But mileage will vary by file, compression level, and by search options and patterns.

Note that both test runs indicate parallel efficiency, since CPU>100%. The ugrep decompression thread and search thread appear to overlap and thus offer a modest performance increase. A 100% to 110% CPU utilization is to be expected (200% is only theoretically possible, but unlikely due to IO and synchronization overhead.)

By comparison, searching an xz-compressed 26MB `enwik8.xz`file takes 1.5s:
~~~
$ time ugrep -zc testing enwik8.xz
468
1.495u 0.034s 0:01.50 101.3%	0+0k 0+0io 0pf+0w
~~~

**Comment by genivia-inc** [comment]
Released v3.2.

**Comment by kilobyte** [comment]
Big thanks for this!

As for your concerns about speed, it looks like all is fine -- and, in fact, ZSTD is best (corpus is 3173 files text files 677MB gzipped in total, machine is a slow 4-core J4115, median of 3 runs):

| | real | user |
|-|-|-|
| gz | 0m11.970s | 0m39.869s |
| xz | 0m16.822s | 0m58.233s |
| zstd | 0m8.858s | 0m26.339s |
| xz-9 | 0m21.619s | 1m3.740s |
| zstd-19 | 0m8.324s | 0m25.094s |
| xzgrep 9 | 1m23.856s | 1m19.257s |
| zgrep | 0m58.098s | 1m4.907s |

As this corpus is customary for ugrep but atypical for compressors (lots of giant text files), ZSTD actually wins over XZ: 344MB zstd -19 vs 365M xz -9, thus 677MB gz looks terrible.

On a faster machine (64-core 2990WX) there are no surprises.

**Comment by trantor** [comment]
Can't wait to try it out!

**Comment by genivia-inc** [comment]
Thanks for the additional info! My earlier comments reflected my experience with the lz4 decompression and not zstd. I assumed that zstd would be similar to lz4, because of what I had read this somewhere about lz4 and its creator. But std is clearly much better than lz4 and doesn't have the huge 4MB block size issue that lz4 has.

**Comment by genivia-inc** [comment]
> Can't wait to try it out!

Thanks @trantor. I tested the implementation with small to large files and carefully checked the details of the zstd method. The zstd documentation is not that easy to follow compared to other compression library docs. The [examples in the zstd repo](https://github.com/facebook/zstd) helped. Nevertheless, if anyone finds room for improvement (speed or other issues) then I would like to know!
