### ISSUE TITLE
Using `ugrep -w` differs from `grep -w`

### ISSUE THREAD

**Issue by firasuke** [Genivia/ugrep#134]
Is it possible to use `ugrep` as a complete drop-in replacement for `grep`?

I tried running both `grep` and `ugrep` with the following flags, but I got different results:

```Shell
grep -rnw . -ie ".*some_string.*"
```

and:

```Shell
ugrep -rnw . -ie ".*some_string.*"
```

I'm getting different results with both (`grep` tends to show more results). I even trtied removing the `.*` and `grep` still showed more results.

Is there something I'm doing wrong? Or is it not possible to completely replace `grep` with `ugrep`?

Thanks for your time and effort.

**Comment by genivia-inc** [comment]
Thanks for the feedback! The difference is that the word boundary `\<` (used with option `-w`) in ugrep does not match a line that starts with a non-word character. GNU grep matches the whole line, even if the first character is not a word character:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/13117347/118675166-6160ad00-b7c8-11eb-9cad-2442dbc3ea1a.png">
Both greps are wrong for this (contrived) example. GNU grep matches the line starting with `#` with `\<.*`, which is strictly speaking incorrect! On the other hand, ugrep should match `bin` with the `\<.*bin` part of the pattern because the chars before `bin` are non-word characters. However, the latter would make the regex matching very expensive due to backtracking. Not sure if the effort is worth it to correct that by implementing ad-hoc backtracking. Another approach would be to treat `\<.*` as `\<([[:word:]].*)?` and avoid backtracking to obtain the correct match:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/13117347/118677109-fca65200-b7c9-11eb-8f47-26a121f3e336.png">
The same principle applies to the ending `.*` that eats up line until the end after which the `\>` word boundary is checked so that the last character on that line must be a word character. In this case `.*\>` should be `(.*[[:word:]])?\>` to get a perfect match.

Anyway, I suspect that GNU grep and BSD grep just take an easy way out of this problem by not enforcing `\<` and `\>` boundaries at the start and end of a line (can we call this "cheating"?). That's why you get more results with GNU/BSD grep. This "feature" (or bug) of GNU/BSD grep is probably documented somewhere. Perhaps we should do the same in ugrep and that would be a simple modification to implement.

**Comment by firasuke** [comment]
Thanks for the extensive explanation!

From a Linux distribution developer's point of view, I'd say having `ugrep` as a ready drop-in replacement for GNU/BSD `grep` would greatly increase its adoption; perhaps have a mode or a flag or a wrapper that allows `ugrep` to operate fully in GNU `grep` mode; even if it were wrong in some edge cases.

That doesn't mean that `ugrep` shouldn't have all the great features it has and the way it does things "correctly".

Perhaps passing `--gnu` to `ugrep` would allow it to operate in GNU `grep` mode, and passing `--bsd` would allow it to operate in BSD `grep` mode.

It'd be even better if one can just symlink `grep`, `egrep` and `fgrep` to `ugrep` and it'll handle that automatically based on how it's called (this will allow the complete removal of the GNU `grep` package as `ugrep` will truly be a complete, modern and viable replacement to it).

**Comment by genivia-inc** [comment]
No worries. I tried to make ugrep behave [as close as possible to GNU grep](https://github.com/Genivia/ugrep#grep).

When ugrep is renamed to `grep`, `egrep`, `fgrep` then certain options are enabled to make ugrep behave exactly like those.

Also, all GNU options are available and behave the same (or better by adding more features), with the exception of `-Z` being changed to fuzzy matching.

I have not yet found cases where ugrep deviates. I scoured the docs and online forums for grep issues to see how ugrep should address them or replicate them. I had not seen `-w` being forced to behave this way. I hope to get feedback like yours to address any remaining differences that I and others may have overlooked. Such cases are likely to be specialized/weird/edge situations.

**Comment by genivia-inc** [comment]
GNU grep produces the following for option `-w`:
~~~
$ ggrep -w 'bin/' push.sh
$ ggrep -w '/bin' push.sh
#!/bin/sh
~~~
The first has no matches, the second matches. I suppose GNU grep's algorithm is much simpler as it just looks at the character before and after the match if it is not a "word character". By contrast, the `\<` and `\>` word boundaries check both sides (left side of `\<` is a non-word char and right side is a word char). So rather than using the more powerful `\>` and `\<` boundaries, a simpler one-sided check should suffice to filter matches.

**Comment by firasuke** [comment]
Based on my usage, then other than the reported example above, I've seen no deviation in `ugrep`'s behavior in comparison with GNU `grep`.

> I hope to get feedback like yours to address any remaining differences that I and others may have overlooked. Such cases are likely to be specialized/weird/edge situations.
I'll be giving `ugrep` a decent test ride by attempting to bootstrap an entire Linux distribution using `ugrep` as a complete replacement for GNU `grep` and see how things go, but it'll be a while before I report my findings so stay tuned (hopefully).

**Comment by genivia-inc** [comment]
A quick update on progress to address this. I've corrected the `\<` and `\>` anchors in the dev version of ugrep (not yet committed). There was an internal optimization that resulted in some edge cases to be ignored, meaning the search advanced too quickly. Now the previous example works as expected and a range of other test cases after verifying the algorithms. However, we still have the noted small difference to GNU grep's `-w` option (more about that below):

<img width="570" alt="image" src="https://user-images.githubusercontent.com/13117347/118890313-758dd280-b8cc-11eb-9802-62bf5a1c52ba.png">

Also PCRE grep and Silver Searcher do not produce the same result as GNU grep for this pattern, i.e. the same issue:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/13117347/118891833-f5686c80-b8cd-11eb-9d3c-d89588806628.png">

I will address the difference of ugrep compared to GNU grep by dropping the internal use of `\<` and `\>` for option `-w`.

So after looking into the GNU and BSD grep option `-w` details, the requirement is that the matching text has a non-word character preceding it or starts at a new line and the matching text has a non-word character following it. This is contrary to what I had assumed for ugrep's implementation, which was based on the BSD grep man page that incorrectly states:
~~~
     -w, --word-regexp
             The expression is searched for as a word (as if surrounded by
             `[[:<:]]' and `[[:>:]]'; see re_format(7)).
~~~
The `[[:<:]]` and `[[:>:]]` are the same as `\<` and `\>` to match word boundaries, meaning a non-word on the left of `\<` followed by a word character, and vice versa for `\>`. This is false, because BSD grep does not require word characters "inside" the pattern, e.g. `grep -w '/bin'` matches `/bin`, just like GNU grep.

Even official implementations get it wrong. Perhaps not surprising, BSD grep has another bug:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/13117347/118889200-c7355d80-b8ca-11eb-99e0-6728757a0d7e.png">

The first match is fine (GNU grep), but the second (BSD grep) is wrong because there are no matches. Also PCRE grep and Silver Searcher do not produce any output for this example, which makes sense because I assume these use `\<` and `\>` internally for option `-w`.

The problem with BSD grep here is that just checking the character before and following a matching text pattern is not sufficient. The matcher has to advance and try again. This is similar to `\<` and `\>`, which will advance until a match, but without requiring word characters "inside" the pattern.

**Comment by firasuke** [comment]
@genivia-inc cool, thanks for the update!

**Comment by genivia-inc** [comment]
Testing of ugrep v3.3 is progressing well after a major upgrade to revise option `-P`. The default `-w` matching is now exactly as GNU grep. I've tested thoroughly to check if the implementation indeed avoids the `-w` pitfalls (bugs), such as the ones discussed here.

Also in the upgrade all PCRE2 regex pattern features should be available. Also `-w` and `-i` are updated for Unicode compliance when option `-P` is used with PCRE2.

**Comment by firasuke** [comment]
> Testing of ugrep v3.3 is progressing well after a major upgrade to revise option `-P`. The default `-w` matching is now exactly as GNU grep. I've tested thoroughly to check if the implementation indeed avoids the `-w` pitfalls (bugs), such as the ones discussed here.
> 
> Also in the upgrade all PCRE2 regex pattern features should be available. Also `-w` and `-i` are updated for Unicode compliance when option `-P` is used with PCRE2.

Awesome! When will a new version be released?

**Comment by genivia-inc** [comment]
All tests passed so far, including the RE/flex regex pattern testing with the PCRE2 engine. We are verifying more edge cases to try to break it to check if ugrep holds up, which is time consuming. If testing continues to go well today, then the update will be released today or tomorrow.

**Comment by firasuke** [comment]
> All tests passed so far, including the RE/flex regex pattern testing with the PCRE2 engine. We are verifying more edge cases to try to break it to check if ugrep holds up, which is time consuming. If testing continues to go well today, then the update will be released today or tomorrow.

Ok cool.
