### ISSUE TITLE
macOS and symbolic link

### ISSUE THREAD

**Issue by grylem** [Genivia/ugrep#14]
Hi
for macOS this error is still present
Thanks
P.S
please fix syntax exampe
ugrep -Rl '.' -N '\p{Unicode})'

**Comment by genivia-inc** [comment]
Hm, it works fine on my Mac:
~~~
~/Projects/ugrep/tests % ls -l dir1
lrwxr-xr-x  1 engelen  staff   7 Sep  4 13:46 dir2 -> ../dir2
-rw-r--r--  1 engelen  staff  27 Sep  4 13:46 text1.txt
~/Projects/ugrep/tests % ls -l dir2
lrwxr-xr-x  1 engelen  staff   7 Sep  4 13:55 dir1 -> ../dir1
-rw-r--r--  1 engelen  staff  27 Sep  4 13:46 text2.txt
~~~
Then:
~~~
~/Projects/ugrep/tests % ugrep -Rl '' dir1
dir1/dir2/text2.txt
dir1/text1.txt
dir1/dir2/dir1/text1.txt
~~~
Are you sure you are using 1.7.0?

**Comment by grylem** [comment]
your example only works for a folder but not for a file.

> Are you sure you are using 1.7.0?

of course

**Comment by genivia-inc** [comment]
After more testing I found that there is indeed a case when a symlink does point to a file that is missed in the results. The problem is a missing test for `type == DIRENT_TYPE_LNK`. I should have caught that problem earlier.

Let me release an update. The extensive tests succeed, so I'm confident this fixes the problem.

Thanks for reporting this.
