### ISSUE TITLE
unaligned output schema with output formats JSON/XML/CSV

### ISSUE THREAD

**Issue by chrissiebert** [Genivia/ugrep#145]
IMHO, the output format should be aligned across the 3 currently available output formats JSON, XML and CSV:
The search results with option --json uses 'matches' and a list of 'match' dictionaries, while --xml uses tags 'grep' and 'file' with a list of 'match' tags, and --csv does not use any header by default.
That behavior can be verified e.g. by comparing the results of the following commands:
ls * | ugrep <pattern> --json
ls * | ugrep <pattern> --xml
ls * | ugrep <pattern> --csv
IMHO the use of 'matches' and list of 'match' dictionaries as currently used with JSON is generic enough to be also used with XML as tags (and CSV header) to represent any kind of search results. The use of 'grep' and 'file' with XML might be misleading with some results.

**Comment by genivia-inc** [comment]
Thanks for the feedback! XML _requires_ a root element (JSON does not), which is chosen to be `<grep>`. The XML `<file>` tag could be changed to `<matches>` like the JSON output. Other than that possibility, I am not sure what you suggest that would be valid.

**Comment by chrissiebert** [comment]
Many thanks for your fast answer. I'd have envisioned something like the following (also using option -Hkn):

XML:
```
 <result>
  <matches>
    <match>script1.py</match>
    <line>4</line>
    <column>4</column>
  </matches>
  <matches>
    <match>script2.py</match>
    <line>4</line>
    <column>4</column>
  </matches>
 </result>
```

JSON:
```
{
  "result": {
    "matches": [
      {
        "match": "script1.py",
        "line": 4,
        "column": 4
      },
      {
        "match": "script2.py",
        "line": 4,
        "column": 4
      }
    ]
  }
}
```

CSV:
```
match,line,column
script1.py,4,4
script2.py,4,4
```

IMHO, that would be more consistent when comparing these output formats.

**Comment by genivia-inc** [comment]
This JSON example will not work because we need an _array of matches_, not an object with a single `"matches"` property. This array of matches also normally contains a `"file"` property unless only one "file" was matched so the filename is not included as `"file"`. Try with option `-H` to see the difference. This produces the JSON `"file"` property like the XML output:
~~~
[
  {
    "file": "(standard input)",
    "matches": [
~~~
Note that JSON does not require a root object, so `"result"` is redundant.

Normally you'll match multiple files instead of standard input. Creating a special case for standard input makes it incompatible to the multi-file match output.

XML and JSON are really two different beasts that do not translate syntactically perfectly, but match semantically (mostly). JSON's arrays are nameless, whereas XML "arrays" as element repetitions are named.

**Comment by genivia-inc** [comment]
FYI. I think this discussion is might be useful to others. I had decided against the following format some time ago when implementing JSON (and XML) outputs:
~~~
      {
        "match": "script1.py",
        "line": 4,
        "column": 4
      },
~~~
This produces a file name `"match"` property for _every match_ in a _single file_, meaning that all `"match"` values are the same. It is more compact to produce one JSON object per file (exactly like the XML `<file>` element), which contains an array of "matches" and each match in the array has pattern-match specific information. This approach is perfectly translatable between the JSON and XML outputs once you see the hierarchical structure. Both JSON and XML are hierarchical. Let's use this to our advantage.

**Comment by genivia-inc** [comment]
I will close this with a final note that `--format` allows customization of the output, including JSON (different forms). The manual shows how JSON is produced with `--format` here: https://github.com/Genivia/ugrep#format

To produce the format with JSON `"match": "filename"`:
~~~
--format-open='%,%~ {%~ "matches": ['
--format='%,%~ { %[, ]$%["match": ]H%["line": ]N%["column": ]K%["offset": ]B"match": %J }%u'
~~~
