### ISSUE TITLE
Python3 files are not found using -M option

### ISSUE THREAD

**Issue by juhopp** [Genivia/ugrep#163]
There's a problem with the Python shebang, as files with explicit Python version are not found. E.g.

$ cat tester 
#!/usr/bin/env python3
print("Hello")

$ ugrep -lt Python "" .
<no output>

However, without explicit version it works as expected, e.g.

$ cat tester 
#!/usr/bin/env python
print("Hello")

$ ugrep -lt Python "" .
tester

**Comment by genivia-inc** [comment]
How about `"#!\\h*/.*\\Wpython[23]?(\\W.*)?\\n"`? This also finds `#!/usr/bin/python`, #!/usr/bin/python3, `#!/usr/bin/python2.7` etc.

**Comment by genivia-inc** [comment]
The reason why there is a `(\W.*)?\n` pattern at the end is to ensure that the name of the utility directly ends with a `\n` or ends with a non-word character `\W` followed by any characters `.*` and a `\n`. It is safer this way, because it won't match `#!/usr/bin/pythonista` or `#!/usr/bin/env pythonista` for example. Instead of `\W` perhaps `\s` (any space) can work too, but not with `"#!\\h*/.*\\Wpython[23]?(\\s.*)?\\n"`.
