### ISSUE TITLE
Win32 - ugrep output contains extra CR

### ISSUE THREAD

**Issue by idigdoug** [Genivia/ugrep#165]
Most Win32 files use CR-LF as the line ending.

When outputting matched lines, ugrep seems to remove the trailing LF, then output the lines as if by `printf("%s\r\n", line)`. However, since the line ended with CR-LF, removing an LF and then adding a CRLF results in ugrep output CR-CR-LF.

Ideally, when removing the trailing LF from a line, ugrep would also remove a trailing CR.

I'll look around to see if there is a good place to add this, but maybe somebody more familiar with ugrep might be able to find the right spot more quickly.

**Comment by idigdoug** [comment]
`FILE*` I/O is buffered. fread satisfies your request from the buffer if possible. If the buffer is empty, fread reads a full buffer from the file (say, 512 bytes). I suspect it then translates the entire buffer according to the current text/binary translation mode. I'm guessing this means if you use setmode the change won't take effect until the current buffer is consumed.

It's probably fine to detect a BOM in text mode since no \r or \n characters are involved, but I suspect the subsequent decoding of that buffer full of bytes will be unsatisfactory. The \r\n translation would be fine for UTF-8 but would interfere with UTF-16 and UTF-32.

With a real file you could call setmode and then seek back to position 0, but that won't work for stdin.

**Comment by genivia-inc** [comment]
Makes sense. Now I need to find some time to update and test on Windows with UTF files.

**Comment by genivia-inc** [comment]
OK, so the reason why switching between binary and text mode is necessary before and after reading the BOM is to ensure that UTF-16 and UTF-32 files are readable in binary mode. Those files may have CTRL Z (hex 1a) as an upper byte of the UTF-16/32 multibyte sequence. A CTRL Z causes an EOF when reading files in text mode on Windows. Therefore the BOM is read byte-by-byte (in binary mode) to switch back to text mode if the file isn't UTF-16/32 encoded. The internal file buffering by the OS should be turned off until the BOM is determined. I've considered and tried in the past to always read a file in binary mode on Windows machines, but that was unsatisfactory.

**Comment by idigdoug** [comment]
Right, as I said above, detecting the BOM works fine in all cases, but text translation (\r\n and ^Z) interferes with subsequent UTF-16 and UTF-32 text (^Z more catastrophically).

Note that this is not OS-level buffering. In Windows, fread and read are both implemented by the CRT, and the OS doesn't get involved until ReadFile. The translation is a characteristic of the read() layer, not the OS or the fread layer.

Can you explain why reading in binary mode was unsatisfactory? It seems like always reading in binary mode (and then doing \r\n translation within your own code) would be the most consistent solution. In particular, if it's acceptable to have binary mode on for UTF-16 (and converting \r\n after converting from UTF-16), why is it unsatisfactory to have binary mode on for UTF-8?

**Comment by chrisant996** [comment]
> Most Win32 files use CR-LF as the line ending.
> 
> When outputting matched lines, ugrep seems to remove the trailing LF, then output the lines as if by `printf("%s\r\n", line)`. However, since the line ended with CR-LF, removing an LF and then adding a CRLF results in ugrep output CR-CR-LF.
> 
> Ideally, when removing the trailing LF from a line, ugrep would also remove a trailing CR.
> 
> I'll look around to see if there is a good place to add this, but maybe somebody more familiar with ugrep might be able to find the right spot more quickly.

Sounds like the issue is because only LF was stripped.  Text vs Binary modes are a complicated and fragile way to compensate for that.

How about making an encapsulated helper function such as `strip_line_ending(char* buf, size_t& len)`?  The helper would encapsulate how to strip a line ending for the current platform (or it could be relaxed and always strip line endings matching any known platform).

Then anywhere that strips LF, call `strip_line_ending(...)` instead.

**Comment by idigdoug** [comment]
> How about making an encapsulated helper function such as `strip_line_ending(char* buf, size_t& len)`? The helper would encapsulate how to strip a line ending for the current platform (or it could be relaxed and always strip line endings matching any known platform).

My perspective is somebody who is pretty familiar with Win32 but not very familiar with the ugrep source code. From my perspective, once you're doing your own text encoding, it's easiest to do your own CRLF translation as well (i.e. always read in binary mode).

However, Dr. van Engelen (the person most familiar with the ugrep code) has said he tried using binary before and ran into trouble, so before I make a mess, I want to learn what went wrong when he tried that approach before.

**Comment by chrisant996** [comment]
I see.  My perspective is somebody who has written cross-platform line ending support in many different kinds of scenarios, and even needing to make each platform support all line ending formats (from the same platform, and other platforms).

Yes, I would expect several problems with using binary mode (and more problems if dynamically changing modes).
First, using binary mode anyway requires the reader code to explicitly handle \r\n and \n (and maybe \r if you want to support Classic Mac).  That's essentially the same work as the helper function I suggested.

In addition, using binary mode requires all writer code to explicitly handle line endings.  That usually is more complicated, because usually there is a single reader site, and usually there are many different writer sites.  So every individual writer site would need to be changed.  And every future writer site would need to do extra work to ensure correct line endings.  The latter is the trickiest part -- using binary mode makes it much more likely to have regressions in the future.

Anyway, this weekend I will take a look at debugging the issue.

I discovered ugrep a couple days ago, and it looks interesting.  The `-r` flag doesn't seem to work as expected (`ugrep -r void *.cpp` doesn't recurse, but `ugrep -g **/*.cpp void` does).  I'll use a debugger and identify what's happening for both issues.

**Comment by chrisant996** [comment]
Finally got it building.  The instructions for building on Windows are surprisingly involved, and the ugrep.vcxproj needs the new `simd_avx2.cpp` file added (the Windows build instructions were last updated 7 months ago, and simd_avx2.cpp was added 5 months ago).  The instructions have put the repo into a state where there are 953 untracked files, plus the ugrep.vcxproj change.  Not a big problem, but a little messy, and care must be taken to avoid accidentally adding external files into the ugrep repo.

Will investigate `-r` and the CR issue next.

**Comment by chrisant996** [comment]
The `-r` issue is because ugrep explicitly expands wildcards in input arguments _before_ doing any further processing (in `init()` in `ugrep.cpp`), to behave like *nix do.  That is very unexpected in a Windows program that has a "recursive" option.  Windows programs typically defer wildcard expansion to happen in each directory.  So that `findstr /s foo *.cpp` means "search recursively in directories for 'foo' in any *.cpp files in each directory`.  Ugrep interprets it as "expand *.cpp in the current directory, and then search for those expanded filenames recursively in subdirectories".  I confess I don't really understand the point of a recursive option if wildcard expansion isn't deferred.

Anyway, I guess that's by design, though if I end up using ugrep a lot then I might explore in a fork making it more Windows-like when running on Windows.

**Comment by chrisant996** [comment]
**Analysis:**

The `\r\n` in input files are seen literally by the match routines.
This is observable in `reflex::Matcher::match()`, where the `buf_` member has the literal `\r\n` characters.

The input file _**is**_ read using binary mode.
The issue seems to be a mismatch between using binary mode to read input files, and using text mode to output results.

The input buffers in memory contain `\r\n`, so when the match lines are output using text mode, text mode line ending conversion is performed on the `\n` to convert it into `\r\n`.
The `\r` in memory is output verbatim, and then the `\n` is output as `\r\n`.

Thus the final output is `\r\r\n`.
Ugrep already behaves as in the binary proposal, which is why the problem occurs.

**Options:**

1. If output will use text mode, then input line endings need to be normalized before output.
    - It could be done during read by using text mode.  That would hide `\r` from the match routines, which many users would probably consider expected behavior, but some might be disappointed.
    - It could be done by reading in binary mode, and immediately normalizing after read.  That would hide `\r` from the match routines, as above.  It would also require careful processing to ensure normalization carries over properly when `\r\n` are split across buffer boundaries.
    - It could be done by reading in binary mode, and omitting line endings when outputting matches, and then explicitly output `\n` and let text mode output convert it.
    - It could be done by making the output routines drop `\r` that are followed by `\n`, i.e. normalizing at the last possible moment.  This might be the safest + simplest approach, since it looks like all affected output is already funneled through the `output` class.

2. Output could use binary mode.  That would require making the output routines normalize output, so that input file output and program message output (any newlines that are from ugrep rather than from the input file) both use the same line endings.

An important question is, what is the desired output behavior on Windows when some input files use `\n` *nix line endings, and some input files use `\r\n` Windows line endings?
- Should both be output from ugrep using normalized Windows line endings, for consistent parseable output from ugrep?
- Or should the *nix files output only `\n` to report matches at literally as possible?

There are pros/cons either way.  As a Windows user, I would lean strongly towards the former being the default, i.e. always report consistent line endings from ugrep -- and I would imagine that *nix users would prefer *nix line endings output from ugrep when searching Windows files from *nix.  And if literal unnormalized output is believed to be important in some cases, I would lean towards having an option that doesn't normalize file match line endings (but does normalize output such as error messages and headers and etc).

**Comment by genivia-inc** [comment]
> The input file _**is**_ read using binary mode. The issue seems to be a mismatch between using binary mode to read input files, and using text mode to output results.
> 
> The input buffers in memory contain `\r\n`, so when the match lines are output using text mode, text mode line ending conversion is performed on the `\n` to convert it into `\r\n`. The `\r` in memory is output verbatim, and then the `\n` is output as `\r\n`.
> 
> Thus the final output is `\r\r\n`.

Thanks for the feedback!

> It could be done by making the output routines drop \r that are followed by \n, i.e. normalizing at the last possible moment. This might be the safest + simplest approach, since it looks like all affected output is already funneled through the output class.

This should be relatively easy to change in ugrep's output class to drop the `\r` before `\n` for Windows and let the text mode output handle it. For *nix the `\r\n` is produced if the input file has `\r\n`, which is useful when the output should also be usable on a Windows machine. But one can also argue against doing this. I'd rather read the files in binary mode because of UTF-16/32 and when searching archives that require binary mode anyway.

> Finally got it building. The instructions for building on Windows are surprisingly involved

Absolutely! Don't blame ugrep or me for this. Including the external libraries that must be built first and setting up the correct C++ configuration settings for MSVC++ on windows makes it rather more involved than I wished (and initially anticipated). That's why I've included the full instructions. It's easy to forget a step myself, so having this documented helps if I ever have to set this up again on a Windows machine (my triple backup strategy with two geolocation should prevent this, but you never know.)

**Comment by chrisant996** [comment]
If you would like to simplify it for yourself, [premake](https://premake.github.io/) could be very useful.  (And I think Cmake is similar to premake.)

It's pretty straightforward to write a premake script (in Lua) that defines all the components and dependencies and build flags.  Running premake and specifying a build toolset then automatically translates the definitions into the appropriate makefiles or sln's or etc. Several toolsets are supported (e.g. gcc, msvc, mingw, etc).

That could make it easy to automate all of the build steps and relative paths, and make it easy to have a .gitignore entry to ignore all the copied/generated/cloned stuff (or even to put it outside the workspace).

Then ultimately there is a single build definition, eliminating the need to maintain separate build systems.

**Comment by idigdoug** [comment]
> The input file is read using binary mode.

Kind-of. That's the problem. The file is opened in text mode, then setmode is used to switch to binary mode, then data is read, then setmode is used to switch back to text mode, then more data is read. The result is technically "unspecified behavior", but in practice we just end up with a mix of binary mode (for the first chunk of the file, or the whole file for utf-16 and utf-32) and text mode depending on the situation.

As mentioned earlier, my vote would be to always open in binary mode and to get rid of all setmode.

I would also vote to strip \r and \n from the line before matching so you don't end up with weird artifacts like \r interfering with "MatchOnlyAtEndOfLine$".

Then yeah, the output files can be in text mode.

> Finally got it building. The instructions for building on Windows are surprisingly involved.

I put together a PR for simplifying this, then decided not to push it. I made a project that would make it trivial to just clone and build ugrep with VS2019 or later. The result wouldn't have zlib or pcre, but it would be really easy to get started. Then if you wanted to add zlib or pcre, it would be just a few additional steps.

I'll put that PR back together because it sounds like there might be some interest in simplifying things.

**Comment by chrisant996** [comment]
@idigdoug You are correct that text mode CRLF->LF translation happens when the C runtime does a buffered read from the file.  ​For example, `fgetc` simply returns the next character from the buffer, without checking the mode.  (At least in the MSVC implementation of the C runtime -- this can be observed in fgetc.cpp, read.cpp, etc in the public MSVC CRT sources.)

So, toggling text/binary mode causes unpredictable translation or non-translation to occur until the rest of the cached buffer is consumed.

From a Windows perspective, if a program needs to dynamically support both binary and text files and doesn't know in advance which type the input is, then the ideal handling would be:
- Always read files in binary mode.
- Identify content type -- and have a flag to optionally force binary or textual treatment.
- If textual:
    - Normalize line endings to LF in memory.
    - Search the normalized lines.
    - Print output using text mode.

Given that the file mode is toggling, searching may not yield consistent results at line endings, depending on the search pattern.  So my suggestion for last-minute normalization is insufficient, because the input it already inconsistent.

**Comment by genivia-inc** [comment]
I just wanted to add: thanks for the team work! I had some assumptions about the binary/text mode input and output that in practice doesn't turn out to be true. I agree that reading files in binary mode is necessary. Also compressed files should be read in binary mode with the decompressed files being read "as is" anyway, with CR LF or simply LF.

The location in the code base that I see as most viable to amend to remove the \r from \r\n is located in output.hpp where the buffers are flushed to display the output:

~~~
  // flush the buffers and acquire lock
  void flush()
  {
    if (buf_ != buffers_.begin() || cur_ > buf_->data)
    {
      if (!eof)
      {
        // if multi-threaded and lock is not owned already, then lock on master's mutex
        acquire();

        // flush the buffers container to the designated output file, pipe, or stream
        for (Buffers::iterator i = buffers_.begin(); i != buf_; ++i)
        {
          size_t nwritten = fwrite(i->data, 1, SIZE, file);
~~~

Ugrep buffers the output and calls `fwrite()` as shown above. Either the write could be made binary if that is possible (is it?) to prevent \r\r\n or the buffer contents should be normalized by replacing \r\n with \n before the `fwrite()`. I don't know if there is even a difference in mode when the output is sent to the terminal or to a file with `fwrite()`, meaning it may not be necessary to replace \r\n with \n if the output file handle mode is binary.

The output is produced from buffers that are synched among multiple threads. This is the most efficient way possible, because we want the search threads to be continuously active. Even better, when threads don't find anything that matched, then they always continue even when the output is sorted by name, date or other criteria. This works by "marking off" a completed search in the sorted sequence order that threads should report the results.

**Comment by idigdoug** [comment]
For simplifying the build process, try: https://github.com/Genivia/ugrep/pull/166

I'll take a look at the \r\n thing sometime in the next week or so.

**Comment by idigdoug** [comment]
Output can definitely be set to binary. For stdout, it is set via setmode. For a file, it is set via "wb" during fopen.

It would probably be acceptable to set the output handle to binary, but I think it would be worthwhile to normalize the output.

**Comment by idigdoug** [comment]
Proposed fix for the CRLF issue: https://github.com/Genivia/ugrep/pull/167

**Comment by chrisant996** [comment]
If stdout is set to binary, then any `\n` that ugrep itself prints need to be normalized to `\r\n` on Windows.

**Comment by idigdoug** [comment]
This fix produces fairly good results for reflex and Boost regex.

There's a side-effect for PCRE. A pattern like ";$" does not match because it sees a \r between the semicolon and the EOL.

**Comment by genivia-inc** [comment]
@chrisant996 if stdout can be set to binary then we have `\r\n` already, because the input is binary. Therefore, I think the simplest solution is to just set the output to binary (assuming this is possible in Windows, I'm sure).

Normalizing any single `\n`in the input is only needed for non-Windows *nix files that are passed as input, assuming we want to normalize *nix files on Windows too, which is fine with me.

**Comment by chrisant996** [comment]
> @chrisant996 if stdout can be set to binary then we have `\r\n` already, because the input is binary. 

Are there any places where ugrep prints messages of its own?
E.g. header lines, help text, error messages, etc.

Those must be using `\n` right now, yes?  Changing to binary output will make all of those places have incorrect line endings on Windows, unless additional corrective actions are taken.

**Comment by genivia-inc** [comment]
@chrisant996 I don't expect code changes (please look at code), because the warning and error messages are sent to stderr, which can still be text mode. All search output runs through the output class to stdout so that part is separate and can be modified at one point in the code.

Also, if we still need some changes to output `\r\n` then it is not a big deal since we can write stuff like `"whatever string" NL` with `#define NL "\r\n"` on Windows, which is still portable, quick & simple and compiles efficiently.

My inclination is to make stdout binary since stdin is read in binary mode. A simple change to the output class `fwrite()` is needed to produce `\r\n` for `\n`. A loop around `fwrite()` to capture `\n` to check for `\r\n` suffices to write the part before `\n` then output `\r\n` and loop again.

@idigdoug PCRE2 includes CRLF considerations https://www.pcre.org/current/doc/html/pcre2api.html#newlines not sure what the problem is with `;$` not matching `;\r\n` on Windows, something to look into.

> @chrisant996 I discovered ugrep a couple days ago, and it looks interesting. The -r flag doesn't seem to work as expected (ugrep -r void *.cpp doesn't recurse, but ugrep -g **/*.cpp void does). I'll use a debugger and identify what's happening for both issues.

Again, welcome to ugrep. Note that `ugrep -r void *.cpp` doesn't recurse because the glob patterns restrict the search to `*.cpp` which are files, not directories. It's a unix thing. Recursive searches can use `-g"*.cpp"` (or on some Windows terminals `"-g*.cpp"`) to restrict the search to recursively matched C++ files in any directory.

**Comment by genivia-inc** [comment]
Searching and replacing `\n` by `\r\n` can be done efficiently with SSE instructions, very similar to the way I've implemented line counting in ugrep (intermezzo: even w/o SSE, counting `\n` is done with 4 way parallelism to exploit ILP to speed this up). Or simply use `memchr()` that almost always uses SIMD instructions in libc.

**Comment by chrisant996** [comment]
> @chrisant996 I don't expect code changes (please look at code), because the warning and error messages are sent to stderr, which can still be text mode. All search output runs through the output class to stdout so that part is separate and can be modified at one point in the code.

I spent only 10 minutes looking at the sources, and have spent almost an hour writing up what I see.  Here are a few places I found that appear to support my prediction:

- https://github.com/Genivia/ugrep/blob/a1f7352711f40cc6c3be6f0bbe4acee38ffbe961/src/ugrep.cpp#L6711 Here `output` seems to be `stdout`, and the `CNF` class implemented in `cnf.cpp` writes `\n` characters.
- https://github.com/Genivia/ugrep/blob/a1f7352711f40cc6c3be6f0bbe4acee38ffbe961/src/cnf.cpp#L659 For example here is one of several places in CNF that seem to write `\n` to stdout.
- https://github.com/Genivia/ugrep/blob/a1f7352711f40cc6c3be6f0bbe4acee38ffbe961/lib/pattern.cpp#L3224 The `Pattern` class has a lot of `\n` output that goes to a parameterized `FILE* file`, so it looks unsafe to assume whether it's writing to stdout.
- https://github.com/Genivia/ugrep/blob/a1f7352711f40cc6c3be6f0bbe4acee38ffbe961/lib/pattern.cpp#L2386 Here the `Pattern` class opens `file`, and it explicitly can be stdout or other files, so it looks unsafe to assume whether it's writing to stdout.
- https://github.com/Genivia/ugrep/blob/a1f7352711f40cc6c3be6f0bbe4acee38ffbe961/src/query.cpp#L3189 Here is a spot that writes `\n` to stdout.
- I searched for `\n` (non-regex) in `*.h` and `*.cpp` and there are 1035 matches.  I also searched for `printf|puts|putc|write` (regex), which can give a parallax view of how output might be routed.  Anyway, overall there is a pretty large set of hits that appear to warrant analysis.  I can't necessarily tell which are reachable in ungrep, or which can write to what destinations.  Some of them explicitly write to `stderr` but it looked like most are either parameterized or go to stdout.

These are just a few examples of why I expect that using binary mode will involve changing a relatively large number of places in the source code.  Also, it probably will not play well with other libraries, if any of them can write to stdout in ugrep.  It looks like several (all?) of the libraries can write to stdout, but I can't quickly or easily tell whether ugrep invokes any of the relevant library functions.

I've implemented cross-platform line ending support many times.  I would not recommend using binary mode unless (1) all file streams will use binary mode and (2) all source code (including libraries) will be modified to explicitly handle line ending translations.

I would encourage you to have fun and explore.  I also hope that I can save you (and others) some time and pain by raising awareness of some of the subtleties and complexities that arise regarding robustly implementing cross platform line ending support.

> Also, if we still need some changes to output `\r\n` then it is not a big deal since we can write stuff like `"whatever string" NL` with `#define NL "\r\n"` on Windows, which is still portable, quick & simple and compiles efficiently.

The `CNF` class is an example of why a processor macro seems unlikely to yield the expected results.  The `CNF` class accepts a `FILE* output` parameter.  If it uses `\n` then it only supports `FILE*` that are in text mode, and if it uses `\r\n` then it only supports `FILE*` that are in binary mode.

This is an example of why I anticipate that line endings will need to be handled at runtime, rather than at compile time.

However, if both `stdout` and `stderr` were set to binary mode, then a preprocessor macro solution could work.  Provided that all sites that output line endings are updated.  Which I agree is not difficult to do.  When looking for line endings, I usually search for `\n`, `10` (whole word match), and `0x0a` (case insensitive).  For some reason I usually don't look for `\012` but probably I should.

> My inclination is to make stdout binary since stdin is read in binary mode. A simple change to the output class `fwrite()` is needed to produce `\r\n` for `\n`. A loop around `fwrite()` to capture `\n` to check for `\r\n` suffices to write the part before `\n` then output `\r\n` and loop again.

Have the examples above helped to clarify what I'm suggesting to take into account when choosing how to proceed?

**Comment by idigdoug** [comment]
When I search through files with LF, CRLF, or mixed endings, I am most happy when the list of results has consistent line endings.

I frequently deal with mixed line endings. Not all Linux files are LF. Not all Windows files are CRLF. Line ending consistency will always require some kind of filtering. This applies to both Linux and Windows.

The list of results will usually be substantially smaller than the size of the input, so I don't usually expect normalization to be a significant cost in the overall search operation. I feel like the value I get from consistent line endings is greater than the cost in terms of CPU for filtering.

In theory, it would be most efficient to internally convert to the local platform's line ending and then output in binary mode so that we don't have to normalize and then have fwrite do another pass of normalization. In practice, this gets pretty messy and makes the code harder to read than just consistently using LF and allowing the platform's fwrite do the conversion to the platform's preferred line ending.

**Comment by genivia-inc** [comment]
@idigdoug agreed!

@chrisant996 With all respect I think we're going around circles and there is no need to nitpick. A quick `ugrep -tc++ -F '\n'` produces a list like this 😉, though the only relevant one in your list is the first item with `Stats::report(output);` and `bcnf.report(output);`. The others are part of the pattern debugging and the query UI. Again, it will be easy to change the stat and CNF classes reporting `\n` to `NL` with a windows-specific `NL` emitting `\r\n`. It takes more time to talk about it then implementing this change in C++ code.

Correct me if I'm wrong, but is the following list of points agreeable?

- on Windows, with input mode binary and output mode binary, there is no normalization necessary if mixed LF and CRLF are not considered to be an issue. You'll get the same behavior on \*nix emitting LF and CRLF depending on the input with CR or CRLF. It just replicates from input to output.
- stderr is still text mode, so warnings and errors are not affected.
- changing `\n` to `\r\n` for the stat and CNF reporting when option `--stats` is used is needed (for the Windows platform). On the other hand, because the stats are shown after the results are complete, won't a stdout flush followed by a change to text mode of stdout not work? Or is the current stdout mode permanent?

The first item can be debatable: if mixed output is not desirable, then normalizing the output to produce `\r\n` on Windows requires a change to the `fwrite()` loop to check for sole `\n` and replace the sole `\n` with `\r\n`. Either replace in the buffer. Or much better, use `memchr()` to find `\n` to output in parts with `\r\n` output afterwards will speed things up. If there is no consensus on the first point, then we can always add a Windows-specific CRLF normalization option to ugrep to output CRLF, so let the user decide.

**Comment by chrisant996** [comment]
@genivia-inc as @idigdoug stated, we normally want line endings emitted from tools to have line endings normalized to the local platform.  If searching Unix files on Windows, we want Windows line endings emitted from the search tool.  If searching Windows files on Unix, we want Unix line endings emitted from the search tool.

#### Regarding output:
- Re: the first item -- mixed output is not desirable; we want normalization, always, for all output.  (We think Unix users want normalization, too, if they ever search Windows files.)
- Re: minimizing changes -- the flush/setmode suggestion sounds promising.  It sounds like you're sure there are only two places where output goes to stdout.  I'm only mentioning kinds of unexpected issues that typically arise when dealing with line ending normalization.  You sound confident they don't apply in this code base.  You know the code better than I do.

#### Regarding input:
We want `;$` to match regardless whether `\r` is present.  Windows users don't want to have to manually modify regexes to ignore `\r` characters.

**Comment by idigdoug** [comment]
Let me try to summarize the conversation so far.

Issues mentioned:

1. ugrep emits "CRCRLF" output in the match result list.
2. ugrep build from Visual Studio is complex.
3. ugrep glob behavior during recursion is not quite as-expected for Windows users (e.g. doesn't match the behavior of DIR).
4. PCRE does not match ";$", probably due to a CR.

I think each of these issues should be considered as completely independent.

1. Being discussed in this GitHub issue.
2. No corresponding GitHub issue. However, I had already done some work on this, so I made a PR. Further discussion might be appropriate in the PR comments or in a new GitHub issue.
3. This should probably be discussed in a new GitHub issue, but here is my take: This behavior is by-design and should not be changed, but related improvements could be made. While this doesn't match the behavior of DIR, it does mostly match the behavior of normal grep, and compatibility with normal grep is a good thing. That said, there is room for improvement:
  - ugrep's `-g` flag behaves much more like what people expect, and this should probably be emphasized in the documentation.
  - The Windows wildcard expansion does not currently handle directory wildcards like a POSIX shell does -- it only handles wildcards in the last component of the path. I never use directory wildcards, so this isn't particularly interesting to me, but adding support for directory wildcards on Windows might be a valid projec if somebody wants to investigate it.
4. This seems like a bug and should be investigated, but as a separate issue.

Continuing the discussion of issue 1 (and only issue 1), I see the following proposed solutions:

1. Change all search input to binary, change all result-list output to binary. This resolves nearly everything, except that the output list will have line endings corresponding to the input file. If input files use inconsistent line endings or if they have line endings different from the platform's natural line endings, the output list will be inconsistent. **I consider this to be acceptable, though I would prefer a better solution that generates consistent line endings event with inconsistent input.**
2. Change all search input to binary, keep all result-list output as text, normalize result-list output to LF. Let fwrite convert output to the platform's natural line endings (conversion on Mac/Windows, no-op on Unix). This resolves everything and has a fairly simple implementation. On Mac/Windows, it does a bit of extra work that could be avoided by a more sophisticated solution, but it is potentially optimal on Unix. **I consider this to meet all of my needs and I made a pull request that implements this solution.**
3. Change all search input to binary, change all result-list output to binary, normalize result-list output to the platform's preferred line ending. This resolves everything, and can be optimal on all platforms, but is the most complex solution. Ugrep would have to know what the platform's preferred line ending is. In addition, the normalization would have to handle the case where normalizing output causes it to become larger (converting LF to CRLF), which makes the normalization somewhat more complicated. **I consider this to meet all of my needs, but it seems to add substantial complexity to ugrep with little to no benefit.**

Additional comments have been made regarding details that could be applied to one or more of the above solutions.

- Using memchr to optimize normalization. My current implementation runs one iteration of the loop per char. For solution 2, this would become one iteration per CR, with each iteration running memchr once and memmove once. For solution 3, this would become one iteration per LF, with each iteration running memchr once and memmove once. There would be startup costs with each call to memchr and memmove, so this change could make things faster or slower depending on how much faster memchr/memmove execute over the simple loop, and how much it costs to get memchr/memmove started, and how often they hit a CR or LF that causes them to stop. Benchmarks would be needed with various mixes of DOS, Unix, and mixed output. My gut feeling is that this would be a lot of work for something that makes almost no difference in practice since time spent normalizing output is likely a very small fraction of the overall work done by ugrep.
- Implementing SSE2 or AVX optimizations for this normalization. This can help minimize the startup costs associated with memchr/memmove, so would likely produce better results than memchr/memmove, and would probably be faster than my current PR's loop. But again, I expect normalization to be a small fraction of the time spent in ugrep, so this would be a lot of work with not a lot of benefit.

If we want to do research into the fastest possible normalization algorithm, that's fine, but I would consider that to be a separate research project. Fixing this issue in ugrep should not have to wait for the results of the research project. We should start by committing a simple fix. Unless the simple fix is a significant performance regression, the fix should not be delayed because there might be an even faster solution. "Premature optimization is the root of all evil."

- Make some or all of the above into a user-configurable option.

User-configurable options are a punt. Every option the user has to configure is a tax on the user. The user has to determine that they have a problem, search the documentation to find the option, and adjust their usage patterns to set the option. Far better if the tool just behaves reasonably in the first place. There has to be significant benefit to the user before a command-line option is worthwhile.

I don't believe that line-ending normalization of result-list output will use so much CPU that any user will be bothered by it.

I can't think of any scenario where the user actually wants to see inconsistent line endings in the result-list output. (There are scenarios where the user wants to detect inconsistent line endings in the input, but there are better solutions to that problem.)

Basically, it would be a disservice to nearly all users of the tool to make them have to decide whether or not to set some command-line option for this. 99.99% of them will either make the same decision or not care, and that means reading the documentation for the command-line option is a waste of time for 99.99% of the community. The tool should just do the right thing.

In summary:

- There are some other issues that have been raised, but they should be discussed separately so we can stay focused on one issue at a time.
- I find value in normalized line endings on both Windows and Unix, so I don't like option 1 but I would accept it as a sub-optimal solution.
- I would be ok with either option 2 or 3, but I would prefer to keep the code simple unless there is significant benefit to the complexity. Option 2 is simpler, and I see no benefit to option 3 that would make it worth the extra complexity.
- Both option 2 and option 3 add a bit of processing, but I expect this to be negligible in nearly all scenarios while the benefit is tangible, so I consider it worthwhile.
- There are interesting optimizations that might potentially reduce the cost of option 2 or option 3. Might be an interesting research project, but the fix should not have to wait for the results of the research project. Even then, unless the results are a substantial and clear win, I would still prefer simpler code over faster code.

**Comment by chrisant996** [comment]
Thanks, @idigdoug .

Issue 4 only occurs if line endings are not normalized on input.

And if line endings are normalized on input, then the issue of normalization on output goes away, as well.

It is possible to treat normalization on input vs output as independent issues.  I'm trying to understand why that would be necessary.

@genivia-inc could you help me understand why binary input is necessary in various cases?  I am willing to look for alternative solutions for those.

**Comment by chrisant996** [comment]
I investigated some things further to gain more understanding, and I've reached the same conclusion:

For ugrep it makes sense to treat output normalization independently from `;$` type input processing.  Input normalization is (very) undesirable because ugrep can report byte offset of matches and input normalization would skew the byte offsets.  And anyway, when searching in binary files (such as PNG or EXE) it would still be desirable to do output normalization at the point of output.

So I understand now why for ugrep it's best to just do last-moment output normalization (as @genivia-inc has described) and to have a separate solution for regexps to consider both `\r\n` and `\n` to be "end of line" markers.

**Comment by idigdoug** [comment]
Just noticed that the PR fixes redirected output, but console output now has an extra newline. Probably some separate filtering needs to happen in the console output path.

**Comment by idigdoug** [comment]
My current PR performs CRLF normalization. CRLF becomes LF, and isolated CR becomes LF.

Unfortunately, when color is enabled, if a line is "text + CRLF", ugrep emits "text + CR + COLOR +LF". The current PR sees the isolated CR and turns it into LF.

Simplest fix is to simply remove all CR instead of normalizing.

Alternative fix would be to disable normalization when color is enabled.

Thoughts?

**Comment by chrisant996** [comment]
I think you're suggesting this:
1. Remove all isolated CR.
2. Normalize all LF.

If that's what you're suggesting, yes, that sounds great:

Any isolated CR that exist embedded within lines in files would garble/hide output, so suppressing them is arguably a benefit anyway.

**Comment by idigdoug** [comment]
In the general case, I much prefer normalizing, i.e. CRLF->LF, CR->LF. And if we were doing input normalization, that would probably be the way to go. In particular, Apple operating systems sometimes use CR instead of LF.

However, since this is output normalization, I agree that it is too late to assign any significance to CR, so just eliminating CR is probably the right solution. I'll update the pull request.

**Comment by chrisant996** [comment]
> In particular, Apple operating systems sometimes use CR instead of LF.

Yes.  I believe ugrep already doesn't handle Classic Mac CR line endings, so I was trying to avoid bringing up an additional issue that may be better tracked separately.

**Comment by genivia-inc** [comment]
Version 3.3.12 is released with @idigdoug PR. I've included some minor improvements.

**Comment by chrisant996** [comment]
Thank you @genivia-inc !

I can confirm that when I use v3.3.12, `ugrep [options] pattern > results.txt` produces CRLF line endings in results.txt on Windows for content from CRLF files and heading lines (e.g. `--heading`).

It still produces LF line endings for content from files with LF line endings on Windows, thus in such cases the output ends up with mixed line endings, i.e. it normalizes CRLF but not LF.  I acknowledge there may be multiple opinions what the output should be in such cases, and I won't press further on that case, as the majority case now behaves as expected on Windows.

Thanks!
