### ISSUE TITLE
Latin-1 encoded files are treated as binary files

### ISSUE THREAD

**Issue by juhopp** [Genivia/ugrep#172]
I have a latin-1 encoded source file, which is not found by ugrep when `-I / --ignore-binary` option is used:

```
$ file functions.c
functions.c: C source, ISO-8859 text
$ ugrep -g functions.c "" .
Binary file functions.c matches
$ ugrep -Ig functions.c "" .
$
```

I think latin-1 encoded files should not be treated as binary files.

**Comment by genivia-inc** [comment]
This is to be expected, because Latin-1 detection is not automatic as there is no identifying feature to distinguish these from UTF-encoded files. The file is seen as invalid UTF-8 and therefore marked as binary (displaying it will not work properly on UTF-capable terminals).

If you know beforehand that none of the files searched is UTF-encoded, then use option `--encoding=LATIN1` to search.

**Comment by genivia-inc** [comment]
PS. I forgot to mention that we're talking about Latin-1 extended, not just ASCII, i.e. extended characters 80h to FFh. These plain extended characters are not valid UTF-8.

**Comment by idigdoug** [comment]
@juhopp, I added `encoding=latin1` to my .ugrep config file. Alternative might be to add it to your ug.bat script.

My personal preference would be for ugrep to default to latin1 instead of ASCII, but for some use cases ASCII is probably better.

**Comment by genivia-inc** [comment]
If the latin1 encoding is specific to certain filename extensions, you may be able to use `--filter="xyz:iconv -f LATIN1 -t UTF-8"` where `xyz` is the filename extension of latin1 files to search. The `iconv` tool converts the input encoding to an output encoding. This should work for all `.xyz` files that are encoded in latin1. Note that if `.xyz` files are not latin1 encoded, then the search may not work properly.

**Comment by juhopp** [comment]
Thanks for the suggestions. My use case is to grep source code files, no matter what the file encoding is, although utf8 and latin1 are the most common. I just want to avoid grepping for binary files, which typically are compiled object files in my case. I think the `--encoding=latin1` and `--filter` options aren't suitable for my use case.

If it was possible to include several encodings, such as `--encoding=utf-8,latin1,^ascii`, it would be suitable for my use case.

**Comment by genivia-inc** [comment]
I understand. ASCII is already handled automatically because it's a 7 bit encoding (a subset of UTF-8). Latin1 can generally not be automatically detected, because there is no identifying information in the file itself until the invalid UTF-8 sequence is encountered, which may or may not happen, meaning that two latin1 bytes may accidental form a valid UTF-8 sequence. So there is no guarantee to detect latin1 automatically by just looking for invalid UTF-8. Worse, the latin1 file may look like valid UTF-8 but the search results will not usable.
