### ISSUE TITLE
djvu files filter etc. 

### ISSUE THREAD

**Issue by grylem** [Genivia/ugrep#181]
Hi
djvutxt 1999_analyze_scanned.djvu | grep -i bott
Patrick Haffner, Ldon Bottou, Paul G. Howard, and Yann LeCun 
[2] L. Bottom P. Haffher, P. G. Howard, P. Simard, Y. Bengio, 
[3] L. Bottom P. G. Howard, and Y. Bengio. The Z-coder adap- 
[4] L. Bottou and S. Pigeon. Lossy compression of partially

djvutxt 1999_analyze_scanned.djvu | ugrep -i bott
Binary file (standard input) matches

same result
djvutxt 1999_analyze_scanned.djvu >text.txt
cat text.txt | ugrep -i bott
and
ugrep --filter='djvu:djvutxt....

http://djvu.org/docs/1999_analyze_scanned.djvu

[text.txt.gz](https://github.com/Genivia/ugrep/files/7805927/text.txt.gz)
Regards.

**Comment by genivia-inc** [comment]
Have you tried `ugrep -U`? If the djvutxt output contains special characters that are illegal UTF-8 such as latin-1 extended characters, then ugrep considers the file "binary" but GNU/BSD grep just don't care. Always use `ugrep -U` for grep compatibility to ignore/disable UTF.

**Comment by genivia-inc** [comment]
So let's check `text.txt`. I assume this is the djvutxt output? Here `more text.txt` (or `less text.txt`) shows an illegal code `<B1>`:
~~~
Color Image 
SU M TU 
Bilevel Mask 
DESTGN S^?.EEP A^?.-T A^?.-<B1> A^?.ARM ON/OFF ON/OFF 
~~~
Confirmed with a hexdump with ugrep:
~~~
ugrep -X -U '[\x80-\xff]' ~/Downloads/text.txt
00003a40  -- -- -- -- -- -- -- --  -- -- -- 44 45 53 54 47  |-----------DESTG|
00003a50  4e 20 53 7f 2e 45 45 50  20 41 7f 2e 2d 54 20 41  |N S~.EEP A~.-T A|
00003a60  7f 2e 2d b1 20 41 7f 2e  41 52 4d 20 4f 4e 2f 4f  |~.-. A~.ARM ON/O|
00003a70  46 46 20 4f 4e 2f 4f 46  46 20 0a -- -- -- -- --  |FF ON/OFF J-----|
~~~
The `b1` code at location 3a63 is highlighted.

To avoid this problem and use djvutxt as a filter, use ugrep option `-U` or better write a script `djvu2utf8` that contains this line:
~~~
djvutxt | iconv -f LATIN1 -t UTF-8
~~~
Then use this script with `ugrep --filter='djvu:djvu2utf8' ...` to do the proper conversion. This way you don't need option `-U`.

**Comment by grylem** [comment]
> So let's check text.txt. I assume this is the djvutxt output?

yes.

>Have you tried ugrep -U? 

of course but in my case it has no effect.
Binary file text.txt matches

> ...or better write a script djvu2utf8 that contains this line:

this is not bad solution but in this case `ugrep` is not equivalent BSD `grep`

Also since the option `-U` doesn't work as expected, there is a high risk of missing text files that contain at least one special character when processing files with `ugrep`

Thanks anyway.

**Comment by genivia-inc** [comment]
The `-U` flag is mentioned in the README to make pattern matching compatible to GNU/BSD grep, but it is the `-a` flag that ignores "binary" contents. For grep this is just allowing \0 in the file, which otherwise would flag the file is binary.

I think that changing `-U` slightly to allow binary file detection only if there is a \0 would solve this dilemma.

**Comment by grylem** [comment]
> This approach to adjust -U works fine and won't cause other issues, so it will be included in the upcoming 3.5 release available very soon:

it is much better than using the `-a` option because true binaries files not be processed, am I right?

**Comment by genivia-inc** [comment]
Yes, the `-a` option overrides the "binary file" reporting in GNU/BSD grep and also in ugrep.

In general, there is no absolute sure way to determine if a file is "binary". GNU/BSD grep just consider a file with \0 to be binary. Ugrep does too, but also considers invalid UTF encoding as a sure sign that a file is "binary". Also note that displaying invalid UTF-8 characters in a terminal may or may not work and more problematically, newer terminal applications don't display latin1 extended characters or display them wrong when interpreted as UTF-8.

Changing `-U` to behave as GNU/BSD grep with respect to "binary files" makes sense and should no longer result in surprises. This option `-U` also affects the patterns, because a Unicode Character point given as a pattern must match a UTF-8/16/32 encoded character. Option `-U` turns that off, making patterns just ASCII/latin1 like GNU/BSD grep (but which don't match UTF-8/16/32 files at all for that reason).

**Comment by grylem** [comment]
Thanks for the explanation.

**Comment by genivia-inc** [comment]
The v3.5.0 update is available. I also updated the README to explain the GNU/BSD grep compatibility better, which options to use and how to define `grep`, `egrep` and `fgrep`. These use options `-U -Y -.` to restrict it to ASCII/LATIN1 non-UTF Unicode, pattern match empty patterns (so annoying that e.g. `a*b*` match everything) and search hidden files instead of ignoring them. I hope that helps. I've changed option `-U` to no longer check for invalid UTF files to no longer flag them as binary files. Thanks for your comment that helped to make ugrep even better.
