### ISSUE TITLE
 cannot decompress unsupported compression format

### ISSUE THREAD

**Issue by hamidaliyev** [Genivia/ugrep#182]
why?  
ugrep 3.5.0 x86_64-pc-linux-gnu +zlib

`ugrep: warning: cannot decompress unsupported compression format: pasteco.txt.bz2 `

**Comment by genivia-inc** [comment]
Because ugrep was not built with the bz2 library in your case. Only with zlib, but nothing else. Install [bzip2](https://www.sourceware.org/bzip2) on your system. It does not suffice to have the bzip2 command, we also need the dev library to link ugrep against to enable decompression. See the [README](https://github.com/Genivia/ugrep#all-platforms-step-2-consider-optional-dependencies) for instructions.

**Comment by hamidaliyev** [comment]
sudo apt-get install -y libbz2-dev  install  already
Have libpcre2? no
Have libboost_regex? no
Have libz? yes
Have libbz2? yes
Have liblzma? yes
Have liblz4? yes
Have libzstd? yes

**Comment by genivia-inc** [comment]
First, rerun `./build.sh` then check the configure output for comments and the `./build.sh` test comment such as the `Have libbz2? yes` that you report. If all that still produces a runtime error, then make sure that you don't have multiple ugrep versions installed on your system. Just try `ugrep --version` to verify. Don't forget `sudo make install` if you want to install the ugrep and ug commands. Otherwise, copy ugrep and ug to a bin directory or create aliases etc. to make sure you run the correct one.

**Comment by genivia-inc** [comment]
If for some reason bz and bz2 decompression fail out-of-the-box, then the `./build.sh` verification step fails. The verification script ensures that all supported decompression libraries work by searching compressed archives. So this tells me that you're running a version of ugrep that lacks `libbz` when you get the *"ugrep: warning: cannot decompress unsupported compression format: pasteco.txt.bz2"* error.
