### ISSUE TITLE
Truncate snippet from javascript file

### ISSUE THREAD

**Issue by raelb** [Genivia/ugrep#199]
Hi,

When ugrep shows a match snippet from javascript file, because the line is very long, it takes up the entire screen display and more:

![image](https://user-images.githubusercontent.com/13108198/160451756-242979b5-a8f5-446a-aa23-086a74c7d8fc.png)

My suggestion is to truncate the snippet display to a reasonable number of words.

Also, in TUI Query mode, because the line is so long, and the result is only shown on one line, you can't actually see any matching snippet.

![image](https://user-images.githubusercontent.com/13108198/160452417-458c3d14-5d33-4ce4-b692-827383dd182f.png)

Sample folder (unzip)
https://www.dropbox.com/s/lcjuzdgm5zropk6/Firefox%20extensions.zip?dl=0

cmdline:
ugrep -i -z "copy all"

My suggestion is to truncate the snippet display so that the matching text is visible.

**Comment by genivia-inc** [comment]
Good point. Thanks for the feedback.

I'd think that truncating long lines is useful, not only in the TUI. Perhaps a new option is useful in this case, to truncate long lines by omitting the initial line up to the match and omitting the line after the match in the output. Something like `--trunc` and `--trunc=NUM` to truncate lines when lines are longer than `NUM` characters. The default `NUM` could be the current window width. Suggestions are welcome.

**Comment by genivia-inc** [comment]
PS. note that the TUI `ALT-left` and `ALT-right` keys will pan the window left and right to view longer lines, but this is not handy when the lines are very long. So something we can and should do to make viewing long lines easier.

**Comment by raelb** [comment]
> by omitting the initial line up to the match and omitting the line after the match in the output.

Not sure what you mean by "omitting the line up to..." and "line after". If it is a long line then would we not want to include words before and words after the match on that line?

**Comment by genivia-inc** [comment]
The part of the line before the match(es) on that line and the part after the match(es) on that line are omitted, like so:

_This is the initial part of a long line that does not fit the limit of 80 characters (the current window width) so it gets truncated._

searching for `limit` gives:

_...a long line that does not fit the **limit** of 80 characters (the current win..._

Something like that.

The question is, what to do with multiple matches on a line? Should the line still be allowed to exceed the max width? Or ignore the matches after the first if the line is too long?

**Comment by raelb** [comment]
Perhaps have something like

_...a long line that does not fit the **limit** of 80 characters (the..._ [+2 more]

In console mode each match could be shown after the other, with x words before and after each match.

**Comment by raelb** [comment]
I like it. When you have an exe available post it here so I can play with it :)

**Comment by genivia-inc** [comment]
> I disagree with the "double meaning" of the `-ABC` flags, in the context of "I may want to search a text, and see the surrounding lines; also a couple of lines might be a little too much - so I want to truncate them".

Why?

The `-ABC` flags show vertical context and now with `-o` they show horizontal context. Same meaning, different direction. It's quite logical if you think about it.

**Comment by stdedos** [comment]
Context direction can be an orthogonal feature to "other flags" - I don't see why is it important to bind them with `-o`.

I might also want both contexes - given the #89, I'd be very willing to add `--width ${COLUMNS}` to my alias; now `-o` is inferred/mandatory when it's not always the case "in my head"

**Comment by genivia-inc** [comment]
@stdedos IMHO it makes no sense to have a short context on the matching line with `-o` (`--only-matching`), but also expect the full contexts on the preceding and following lines with `-ABC`. After all, `-o` does not display the full line, only the match. Why would you want `-ABC` to display _full lines of context_ before and after this short match? Since GNU/BSD grep do not honor `-ABC` with `-o`, there is no reason to believe that `-ABC` has any practical value with `-o` in the traditional sense. In fact, GNU/BSD grep make no assumptions on this combination and is therefore free of our choosing. Therefore, providing context to a match is not at all orthogonal wrt. to `-o` in existing implementations and should not be. It makes more sense to use `-ABC` to provide horizontal context with `-o` as an orientation from vertical to horizontal, within limits to keep the match info short, as proposed.

**Comment by genivia-inc** [comment]
@stdedos with respect to #89, note that this topic is different, but related.

Furthermore, `--width` may have different interpretations among users. Option names that are nouns are not actionable or causal and leave much to the imagination. What is it supposed to truncate the width of? Is it to wrap lines e.g. in the TUI? Is it to get a quick list of matching lines restricted to the specified width to see what the file might match? If it is the screen width, then this can be automatically detected anyway. For the latter case, then I would argue that `-o` with context will do a better job, since it displays the match with context, not just the initial part of a line truncated to `--width` possibly without even showing a matching pattern.

**Comment by stdedos** [comment]
All I am saying is: for exactly the same reason OP created #199, I have also created #89 - those pesky minified js files laying around and wreaking havok when searching.

We want a way "beautifully" truncate excessive text ("excessive": `> $COLUMNS - 1`, or `> $COLUMNS - 1 - $OTHER_UGREP_TEXT_ON_THE_SAME_LINE`). For me, it is totally optional to see exactly only those matches (i.e. ~ `-o`).
Sometimes I am searching a "common" term, by using an perhaps-adjacent unique term. I am doing that to properly isolate the context round that otherwise too common term to "quickly" narrow down the exact one I am looking for.

If you bind `--width` (originally) to `-o`, for me the feature is not as valuable - I "almost never" use `-o` precisely because if blocks horizontal/vertical context

> Furthermore, `--width` may have different interpretations among users.

Well, `--maximal-line-width [chars] - truncate each match line to a maximum of X characters` is not as pretty, but it's exactly what it does. It is true that this is a plumbing command, and not a porcelain once like the proposed change (https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain)

**Comment by genivia-inc** [comment]
I thought of one minor improvement of `-o` with context. When the match is too long, the truncated part is shown as `[-]`. I think it would be nicer to have `[+columns]`to indicate the number of columns not displayed (truncated). This exposes more useful information and one can increase the context accordingly.

**Comment by genivia-inc** [comment]
> The -ABC flags show vertical context and now with -o they show horizontal context. Same meaning, different direction. It's quite logical if you think about it.

> @stdedos: All I am saying is: for exactly the same reason OP created https://github.com/Genivia/ugrep/issues/199, I have also created https://github.com/Genivia/ugrep/issues/89 - those pesky minified js files laying around and wreaking havok when searching.

With all due respect, I still don't see the issue. By using `-ABC` with `-o` to provide context, we can still keep `--width` (or `--line-width` or `--max-line-width` or `--columns`) reserved for future updates to truncate long lines in a "dumb way".

It won't be challenging to implement `--width` in ugrep to truncate long lines. I think it is a very crude option. It won't be as useful as `-o` with `-ABC` context that offers better results, if you search for lines where matches (may) occur without getting bombarded. Or am I missing something?

**Comment by stdedos** [comment]
Well, if it's "reserved for future effort", okay. I don't think you are missing something.

**Comment by genivia-inc** [comment]
For comparisons, this is the output of `ugrep -n+ --width read` to truncate the line width to the terminal width:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/13117347/170834542-4621f960-fb5d-424e-818a-4be420737e89.png">

By comparison, this is the beta output of `ugrep -n+ -oC30 read`:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/13117347/170834596-74bf375c-f4d6-45d2-b37d-ad081f07a8bc.png">

Both are v3.8.0 beta features.
