### ISSUE TITLE
Please add tests for directories with compressed files

### ISSUE THREAD

**Issue by RuneBergh** [Genivia/ugrep#2]
Request:
A very common usecase for people like me that seek maximum performance is searching within large directories with a lot of compressed log files. 

I have explored most options, but none have beaten the following syntax:
time find 2019* -name '*' -print0 | xargs -P8 -0 zgrep -Fl 10.0.0.1
(8 because that was optimal on the last computer i tested on, but will as you know likely differ.) This method is in some cases just as fast on twice the data, while options like rg almost 2x in time when the data doubles, which means there is some unesecary serialization or something else that causes it to wait rather than using available resources to get the work done. Even :
time find 2019* -name '*' -print0 | xargs -P8 -0 -I {} sh -c 'zcat {} |rg -Fl 10.0.0.1'
was faster than using rg on its own. 

It could also be that the performance gain is first seen on a larger amount of data as is the case with one of the servers i usually work with. 

On this data: 
https://github.com/RuneBergh/example_data/blob/master/testdir.tar.gz

Note that this data is really silly test-data, but it made it possible to showcase the differences.

I have not yet tested ugrep, i will later, hopefully it is better with alrger amounts of directories and files and gains more from parallelism than rg on larger worksets. 

Would love to see this, or another kind of test implemented. Thanks!

**Comment by genivia-inc** [comment]
Thanks for the feedback. Apologies for the delay as I was swamped with projects and deadlines.

I ran your example and found that ugrep 1.5.1 was way too slow to decompress files. This problem is due to a missing `xsgetn(char *s, std::streamsize n)` in `zstreambuf` derived from `std::streambuf` (`src/zstream.hpp`). This missing function resulted in reading decompressed file byte-by-byte. With this function added to ugrep 1.5.2, 64K blocks are decompressed at a time. So ugrep 1.5.2 resolves this problem.

For a single file search, the updated ugrep 1.5.2 with option `-z` shows that it is almost as fast as piping the results of `unzip` to `ugrep`:

~~~
$ time gunzip -c big.cpp | ugrep -Fc serialize
        0.06 real         0.03 user         0.00 sys
20743
$ ugrep -z -Fc serialize big.cpp.gz
20743
        0.08 real         0.07 user         0.00 sys
~~~

The overhead is attributed to the threading of `gunzip` and `ugrep` and perhaps the use of `std::istream` with option `-z` instead of reading `FILE*` from standard input.

When the ugrep threading model is improved, I will test the throughput of multiple files collected with `xargs` as your examples show.

**Comment by genivia-inc** [comment]
I am running some tests with your dataset.

Using `xargs -P8` leads to some strange results with ripgrep 0.10.0:

~~~
find 2019* -name '*.gz' -print0 | xargs -P8 -0 ripgrep -z -Fl 10.0.0.1 | wc
xargs: vfork: Resource temporarily unavailable
     432     432   16074
find 2019* -name '*.gz' -print0 | xargs -P8 -0 ripgrep -z -Fl 10.0.0.1 | wc
xargs: vfork: Resource temporarily unavailable
     868     868   31829
~~~

Also ugrep terminates too soon, but without a vfork error thrown by `xargs`.

Looking into this to figure out what could be causing this.

This is on Mac OS X.

**Comment by genivia-inc** [comment]
Have you had success with `xargs` not causing failed searches? when I run `xargs -P8` some searches are lost or `xargs: vfork: Resource temporarily unavailable` are reported. I have this happen with ripgrep, ugrep, etc. Some runs are silent, which is bad.

**Comment by genivia-inc** [comment]
Closing this issue as decompression tests were added and tested.
