### ISSUE TITLE
additional benchmark results

### ISSUE THREAD

**Issue by minusf** [Genivia/ugrep#200]
hello. i am trying out ugrep and it's extraordinary piece of software. i am a longtime `ripgrep` user so naturally i ran some simple benchmarks of my own.

i am searching in 16 subdirectories each holding aroung a 1000 json files with a total of 16130 taking up 4.6 GB on a 2021 macbook pro M1.

searching for a nonexistent pattern (to bypass the terminal outputting overhead) i see `rg` consistently outperforming `ugrep`:

```
% while true; do /usr/bin/time ugrep -l -e '"expirationDatee": "[^N].+"'; sleep 1; done
        2.20 real         6.21 user         1.92 sys
        2.00 real         6.43 user         1.89 sys
        2.00 real         6.43 user         1.85 sys
        2.03 real         6.42 user         1.86 sys
        1.96 real         6.48 user         1.89 sys
        2.02 real         6.44 user         1.87 sys
        1.96 real         6.48 user         1.88 sys
        2.00 real         6.43 user         1.87 sys
% while true; do /usr/bin/time rg -l -e '"expirationDatee": "[^N].+"'; sleep 1; done
        1.39 real         0.74 user         2.26 sys
        1.59 real         0.74 user         2.23 sys
        1.63 real         0.65 user         2.13 sys
        1.74 real         0.65 user         2.14 sys
        1.58 real         0.70 user         2.16 sys
        1.41 real         0.69 user         2.18 sys
        1.52 real         0.67 user         2.12 sys
        1.34 real         0.72 user         2.21 sys
        1.63 real         0.69 user         2.17 sys
```

the same is true with an existing pattern, again i pipe it to `wc -l` to not spam the terminal:

```
% while true; do /usr/bin/time ugrep -l -e '"expirationDate": "[^N].+"'|wc -l; sleep 1; done
        1.91 real         6.54 user         1.90 sys
    3187
        1.96 real         6.45 user         1.93 sys
    3187
        1.92 real         6.46 user         1.92 sys
    3187
        1.94 real         6.47 user         1.91 sys
    3187
        2.00 real         6.45 user         1.88 sys
    3187
% while true; do /usr/bin/time rg -l -e '"expirationDate": "[^N].+"'|wc -l;sleep 1; done
        1.29 real         0.77 user         2.27 sys
    3187
        1.42 real         0.68 user         2.16 sys
    3187
        1.52 real         0.70 user         2.20 sys
    3187
        1.46 real         0.71 user         2.20 sys
    3187
        1.52 real         0.68 user         2.16 sys
    3187
        1.33 real         0.69 user         2.18 sys
    3187
```

and lastly, `rg` cannot do file level boolean combining of patterns, so i use `rg crit1 | xargs rg crit2` style chaining and while it's not apples to apples (the output can show only lines containing `crit2`) this is also faster than `ugrep` with `--files .. --and`. of course this kind of command chaining becomes unwieldy very quickly.  the speed difference is not huge and a more readable and more composable command is much more preferred by me.

```
% while true; do /usr/bin/time ugrep --files -l -e '"expirationDate": "[^N].+"' --and -e '^  "review_state": "private"'|wc -l; sleep 1; done
        2.44 real        11.23 user         1.93 sys
      31
        2.60 real        10.93 user         1.99 sys
      31
        2.48 real        11.12 user         1.97 sys
      31
        2.57 real        10.92 user         1.96 sys
      31
        2.46 real        11.18 user         1.94 sys
      31
        2.58 real        11.06 user         1.92 sys
      31
% while true; do /usr/bin/time rg -0l -e '"expirationDate": "[^N].+"'|xargs -0 rg -le '^  "review_state": "private"'|wc -l; sleep 1; done
        1.48 real         0.73 user         2.21 sys
      31
        1.68 real         0.64 user         2.07 sys
      31
        1.53 real         0.63 user         2.05 sys
      31
        1.53 real         0.67 user         2.10 sys
      31
        1.60 real         0.63 user         2.08 sys
      31
        1.43 real         0.66 user         2.10 sys
      31
```

**Comment by genivia-inc** [comment]
Funny. Note that the "real" time is not that different, This wall-clock time is the time that counts, i.e. you're waiting on. But what is strange is the large "user" time. That should not be that large! Perhaps this could be due to the ARM-based M1? I don't have any tests on that platform yet. To check, the Neon/AArch64 optimizations should be reported by `ugrep --version`. If that is not the case, then searching will be suboptimal. Also what does `--stats` report? Have you tried with option `-P` to see if there is a difference in timing?

Interestingly, on an Intel-based Mac, searching a directory with several huge files (GB and MB size) looks solid and faster than anything else I've tried, here with your search pattern to check:
~~~
/usr/bin/time ugrep -l '"expirationDatee": "[^N].+"' data
        9.39 real         2.95 user        12.39 sys
~~~
Note that the "user" time is not large, not larger than the "sys" time, so this means that the "real" wall-clock time is mostly the IO/mem time. This shows that searching is really fast with this type of CPU.

Searching a directory with 3239 small/medium files:
~~~
/usr/bin/time ugrep -l '"expirationDatee": "[^N].+"' ~/tmp
        0.16 real         0.16 user         0.38 sys
~~~
Again, the "user" time is not excessive.

**Comment by minusf** [comment]
i agree that the wall clock time difference is small but the benchmark table contains even smaller numbers, so that's why i made the report.  it would be interesting to see how the difference scales with both programs as the input corpus grows.

```
% ugrep --version
ugrep 3.7.6 arm-apple-darwin21.3.0 +neon +pcre2_jit +zlib +bzip2 +lzma
License BSD-3-Clause: <https://opensource.org/licenses/BSD-3-Clause>
Written by Robert van Engelen and others: <https://github.com/Genivia/ugrep>
```

here is the output of `zsh` builtin `time`:

```
% while true; do time ugrep --files -l -e '"expirationDatee": "[^N].+"' --and -e '^  "review_state": "private"'; sleep 1; done
ugrep --files -l -e '"expirationDatee": "[^N].+"' --and -e   11.21s user 1.56s system 456% cpu 2.799 total
ugrep --files -l -e '"expirationDatee": "[^N].+"' --and -e   10.78s user 1.41s system 469% cpu 2.597 total
ugrep --files -l -e '"expirationDatee": "[^N].+"' --and -e   10.81s user 1.44s system 464% cpu 2.638 total
ugrep --files -l -e '"expirationDatee": "[^N].+"' --and -e   10.75s user 1.41s system 467% cpu 2.604 total
ugrep --files -l -e '"expirationDatee": "[^N].+"' --and -e   10.78s user 1.42s system 466% cpu 2.615 total
ugrep --files -l -e '"expirationDatee": "[^N].+"' --and -e   10.76s user 1.46s system 468% cpu 2.608 total
ugrep --files -l -e '"expirationDatee": "[^N].+"' --and -e   10.80s user 1.46s system 470% cpu 2.602 total
```

i speculated that 10s user time while the execution finishes in 2 might be the result of summing up all threads user times?

here's `-P` (with `--stats`):

```
% while true; do /usr/bin/time ugrep -P --stats --files -l -e '"expirationDatee": "[^N].+"' --and -e '^  "review_state": "private"'; sleep 1; done
Searched 16130 files with 8 threads in 18 directories: 0 matching
The following pathname selections and restrictions were applied:
  --files
  --no-hidden (default)
Files matched if:
  ""expirationDatee": "[^N].+"" matches a line, and
  "^  "review_state": "private"" matches a line
        3.87 real        19.89 user         1.71 sys
Searched 16130 files with 8 threads in 18 directories: 0 matching
The following pathname selections and restrictions were applied:
  --files
  --no-hidden (default)
Files matched if:
  ""expirationDatee": "[^N].+"" matches a line, and
  "^  "review_state": "private"" matches a line
        3.80 real        19.91 user         1.69 sys
Searched 16130 files with 8 threads in 18 directories: 0 matching
The following pathname selections and restrictions were applied:
  --files
  --no-hidden (default)
Files matched if:
  ""expirationDatee": "[^N].+"" matches a line, and
  "^  "review_state": "private"" matches a line
        3.82 real        19.92 user         1.61 sys
Searched 16130 files with 8 threads in 18 directories: 0 matching
The following pathname selections and restrictions were applied:
  --files
  --no-hidden (default)
Files matched if:
  ""expirationDatee": "[^N].+"" matches a line, and
  "^  "review_state": "private"" matches a line
        3.93 real        19.90 user         1.66 sys
```

**Comment by minusf** [comment]
please note that the numbers would be even better (for both) if i could turn off the antivirus on this company issued notebook 🙄

**Comment by genivia-inc** [comment]
> i speculated that 10s user time while the execution finishes in 2 might be the result of summing up all threads user times?

With 8 threads the performance is a bit lower than usual in your report: only 4.56 speedup (456%) when I see at least 6x or more typically on my machines with 8 cores. This could be due to other processes switching/interfering, which can greatly affect the "real" time (wall clock time).

For example, with "11.21s user 1.56s system 456% cpu 2.799 total" we get 2.8 seconds total = (11.21+1.56)/4.56 seconds. Note that the 11.21 seconds is the sum of all of the 8 worker thread's CPU work that was done. This should be pretty constant because it is the actual work done, whereas the "real" time 2.8 depends on how many threads could be optimally run on the cores. In this case not optimal at all.

The CPU time is the search algorithm running. I don't know if the 6 seconds reported earlier is reasonable compared to other machines.

Things to note on using `--files`:
- it will not have much of an effect on performance except when a lot in a file is matched (like every line)
- when using `and` each of these conditional regex patterns is searched for. If one of these patterns matches a lot then this **will take much more time** even when the file does not match. The reason is that we don't want ugrep to search a file more than once, e.g. it could be a non-seekable pipe and we don't want to store the while file in memory either. This means that ugrep has no limits (and thus no nasty surprises) on what can be done with `--files`.

Generally using `--files` with one or more `and` will be less efficient than other methods. It's the convenience of `--files` that ugrep users wanted.

Given your report which is useful, I am inclined to believe that the 6 seconds "user" time can be explained. The pattern is simply a string followed by a regex pattern which is highly optimized in ugrep on SSE/AVX CPUs. But for ARM and M1 something is not working as well (for ARM Neon/AArch64). In ugrep there is a tradeoff choice made in the pattern matcher that picks a default traditional Boyer-Moore string search depending on letter frequencies in the string pattern. If SSE/AVX is not available to search faster, then Boyer-Moore is picked more often by default, which could be the reason why you see a larger "user" time on the ARM M1. It could be that Boyer-Moore is always picked on the M1, which is bad. If my hypothesis holds, then we should look into optimizing ARM and M1 better for this use case and similar cases to avoid Boyer-Moore.

**Comment by genivia-inc** [comment]
Some experiments on a ARM7 machine show that the performance of the [SIMD NEON/AArch64 algorithm](http://0x80.pl/articles/simd-strfind.html#arm-computers) is fine for most common patterns, but surprisingly the `'"expirationDatee": "[^N].+"'` pattern search is actually faster with Boyer-Moore.

This does not sit well with me, that the performance of Boyer-Moore (which I further optimized in ugrep versus the Boyer-Moore-Horspool) is close to the performance or even exceeds the performance of the advanced [SIMD NEON/AArch64 algorithm](http://0x80.pl/articles/simd-strfind.html#arm-computers). The difference in performance is very profound on an Intel machine with SSE2/AVX2, where the SIMD algorithm greatly outperforms Boyer-Moore.

**Comment by genivia-inc** [comment]
A clarification about `--files` performance is in order perhaps. With `--files` it's easy to formulate complex queries, which you pointed out too. But all separate patterns are searched for in the single source, whether the source is a file or a pipe or a device (so it always works):
~~~
ugrep --files -l -e '"expirationDate": "[^N].+"' --and -e '^  "review_state": "private"'
~~~
The following xargs approach can be faster to search these two "string-like" patterns, as you showed:
~~~
ugrep -0l -e '"expirationDate": "[^N].+"'|xargs -0 ugrep -le '^  "review_state": "private"'
~~~
That is no surprise, because both patterns are "string like". They are not complex regex patterns. The two "string-like" patterns are combined into one regex by the `--files` with `--and` options to search results using a more complex regex pattern that is a bit slower to search versus the two "string-like" patterns.

I'm just saying, this has nothing to do with ugrep versus ripgrep. Oftentimes `--files` is faster and much more convenient, but sometimes it is slower compared to using xargs.

**Comment by minusf** [comment]
very interesting, thank you for looking into this.  i am happy to close this.

**Comment by genivia-inc** [comment]
There will always be anecdotal cases for which one grep versus another runs faster. By contrast, performance testing and optimization requires a large set of tests with patterns and files to make any conclusions and reproducible results. This is something I have been doing for years (though not for M1 yet).

I'm a bit embarrassed that I don't own an M1 yet. When I have an M1, I will take a closer look at the performance optimizations and algorithmic tradeoffs to further optimize ugrep for ARM/M1.

**Comment by genivia-inc** [comment]
I just noticed something.

> i am searching in 16 subdirectories each holding aroung a 1000 json files with a total of 16130 taking up 4.6 GB on a 2021 macbook pro M1.

Are these json files stored as a single line without line breaks?

**Comment by minusf** [comment]
no, they are pretty printed json files.

**Comment by genivia-inc** [comment]
Still waiting on the delivery of my new MacBook Pro M1 10 Core machine. Takes at least another month. Looking forward to tune ugrep for the ARM64 ISA and M1 capabilities. There already is some ARM vector code I wrote to accelerate searching, but not as much as SSE2/AVX2 and not tuned.
