### ISSUE TITLE
Fuzzy search feels not fuzzy enough

### ISSUE THREAD

**Issue by dumblob** [Genivia/ugrep#203]
When using Levenshtein distance, the fuzzy search too many times it doesn't produce the output one would expect.

I have very good experience with [Sørensen–Dice coefficient](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient ) though.

Would you consider changing the `-Z` argument to use [Sørensen–Dice coefficient algorithm](https://github.com/vlang/v/blob/master/vlib/strings/similarity.v#L41 ) instead of Levenshtein distance?

**Comment by genivia-inc** [comment]
Thanks for the feedback. The fuzziness is inspired by `agrep`, approximate grep. The `-Z` option doesn't only apply to strings, regular expressions are "fuzzified" too. Therefore, the distance specified as a `-Z` threshold is used as a hard threshold to show matching patterns within that threshold. The actual distance is not used anywhere to control or report matches (except by `--sort=best`) as long as the matches are within the threshold. So it is not clear to me how a percentage similarity can be used in practice.

The `--sort=best` option can be improved by applying some more clever statistics. Right now the files with at least one exact match are shown first, then the files with at least a match that differs in one character, then by two characters, and so on. What the improvement of `--sort=best` could be implemented might be subjective, I'm sure, or we add more `--sort=` values to differentiate the metrics to apply. For example, I had thought about computing the average distance for all matches in a file to sort files by. However, that hurts files with one exact match when there are a lot of approximate matches, placing those files low on the list which IMO is bad because that is a typical case (some exact matches, lots of approximate matches e.g. as an artifact).

Suggestions are welcome!

**Comment by genivia-inc** [comment]
Sorry, but I don't see an immediate advantage to using something different than edit distance, which is very practical for approximate pattern searching.

**Comment by dumblob** [comment]
Sorry, the first notification got lost in my mail box.

Yes, percentage would not easily work for regexes or any "more precise description" matching language (e.g. globs).

So my suggesting would be to add a new sorting method `dice` which would simply use the Sørensen–Dice coefficient for all values (this method usually places the exact matches first, so there is really no need to use anything else).

I'd really appreciate that. Thanks!

**Comment by genivia-inc** [comment]
An argument `--sort=dice` is useful.

**Comment by genivia-inc** [comment]
Bigrams of two strings are easy to obtain as [this example](https://en.wikipedia.org/wiki/Sørensen–Dice_coefficient#Formula) shows:
> `night`
> `nacht`
> We would find the set of bigrams in each word:
> {`ni`,`ig`,`gh`,`ht`}
> {`na`,`ac`,`ch`,`ht`}
> Each set has four elements, and the intersection of these two sets has only one element: `ht`.
> Inserting these numbers into the formula, we calculate, s = (2 · 1) / (4 + 4) = 0.25.

But how to compute this metric with regular expressions is not clear to me, when there is no string to produce bigrams? The regex dot `.` is easy, but what about the metas `*` and `?` in `n*ight?` for example?

**Comment by dumblob** [comment]
There are multiple ideas - not all if not none make sense though:

1. we could declare that metas will need to maintain exact semantics and thus we will take them "as is" and do not try any fuzzying with them - basically something like "ignoring metas for fuzzy results" (metas could then be even disallowed to make this behavior explicit, IDK)
2. or we could make up some heuristics - POSIX regexes follow the "greedy rule", so we could fuzzy match mainly on the longest match(es)?
3. or alternatively only fuzzy match on the shortest match?
4. or both?
5. or we could define a subset of the regex language which would allow for "exhaustive" fuzzy matching - reminds me of what re2 [did not want to implement](https://github.com/google/re2/issues/5 )
6. other crazy thoughts?
