### ISSUE TITLE
Slow at traversing crafted symlink farms

### ISSUE THREAD

**Issue by jwilk** [Genivia/ugrep#204]
Consider the following script, which creates N² symlinks:
```bash
#!/bin/sh
set -e -u
if [ $# -ne 1 ]
then
    printf 'Usage: %s N\n' "${0##*/}" >&2
    exit 1
fi
n=$(($1))
lst=$(seq 1 $n)
for x in $lst; do
    mkdir -p $x
    for y in $lst
    do
        ln -sf ../$y $x/$y
    done
done
```
ugrep is very slow at grepping through these symlinks:

```console
$ ./makesymlinks 8
$ time ugrep foo

real    0m2.481s
user    0m0.168s
sys     0m2.304s

$ ./makesymlinks 9
$ time ugrep foo

real    0m26.555s
user    0m2.237s
sys     0m24.231s

$ ./makesymlinks 10
$ time ugrep foo
      
real    5m10.336s
user    0m27.140s
sys     4m42.376s

```
(I originally run into this by grepping through a random collection of source code that included <https://github.com/8051Enthusiast/xterm-primality-test>.)

**Comment by genivia-inc** [comment]
A `std::set` of Unix inodes is used to check if symlink directories were visited before to prevent cycling forever when symlinks form a cycle. Besides that set operations are not constant time, also symlinks do incur a cost. Other than that, I am not sure what could explain this as there isn't much going on internally that would explain slowdowns.

Did you test with one thread using option `-J1`? That usually gives more stable timings to see what the timing difference actually is.

**Comment by genivia-inc** [comment]
It's easy to explain why this blows up with grep-like tools (GNU grep and ugrep).

For `./makesymlinks 9` I get:
~~~
$ time ugrep -J1 foo --stats
Searched 1 file in 986410 directories in 91 seconds: 0 matching (0%)
~~~
There is one file (the script) that can be found in 986410 directories that are traversed through the symlinks in all possible combinations (except cycles). The reason is that ugrep checks for cycles (to avoid), but otherwise traverses the links until all (sub)directories have been visited.

The same happens with GNU grep that produces lots of warnings, like:
~~~
grep: 9/7/6/1/8/2/4/3/4: warning: recursive directory loop
grep: 9/7/6/1/8/2/4/3/3: warning: recursive directory loop
grep: 9/7/6/1/8/2/4/3/2: warning: recursive directory loop
grep: 9/7/6/1/8/2/4/3/5/9: warning: recursive directory loop
~~~
So this behavior to produce all n! (n factorial) permutations of 1,...,n is to be expected with GNU grep and ugrep.

What are you looking for? This case seems somewhat hypothetical to me.
