### ISSUE TITLE
Add build artifacts at the release assets

### ISSUE THREAD

**Issue by stdedos** [Genivia/ugrep#22]
As mentioned in https://github.com/Genivia/ugrep/blob/2c9d5c5ad532111e858b1e33f92b37b9230a54f7/README.md#L305

Would you please add all the releases here?
![image](https://user-images.githubusercontent.com/133706/78722339-ee80d380-7931-11ea-88cd-e59bcef63bdc.png)

_Including_ the `cp2bin`'s target (`bin/linux/ugrep` does not run on my system, whereas `bin/ugrep` does)

It actually took me a while to figure out that everything is _instead_ under ugrep/bin

Something like:
* https://help.github.com/en/github/administering-a-repository/about-releases, or
* https://github.com/marketplace/actions/github-upload-release-artifacts

**Comment by genivia-inc** [comment]
Thank you for your feedback. I am not 100% sure what you mean by "add all the releases here". The releases are bundles of source code and binaries for windows `ugrep.exe` for the same version (v1.8.1 in your case). I'll update the README to make this more clear. I could add the executables as assets too perhaps. Is that what you are looking for? I hope to avoid having to do that because it looks like a pain to do despite the suggested workflow. Also, just downloading the binaries won't include the pattern files that come with the project.

There are also Linux and MacOS binaries, but the problem is that those are not 100% binary portable so I am looking to create Homebrew formulas once the project has the required notability (75 stars or 30 forks).

**Comment by stdedos** [comment]
> Thank you for your feedback. I am not 100% sure what you mean by "add all the releases here".

Artifacts i.e. the executables

> [...] Is that what you are looking for?

Yes ...
> I hope to avoid having to do that because it looks like a pain to do despite the suggested workflow.

.. or, as you suggested - update Readme. Either way works - as long as it is "correct".

> Also, just downloading the binaries won't include the pattern files that come with the project.
> 
> There are also Linux and MacOS binaries, but the problem is that those are not 100% binary portable so I am looking to create Homebrew formulas once the project has the required notability (75 stars or 30 forks).

I have been looking so long for _any_ way to be able to replace grep with ugrep, I really don't mind at all about anything else at this time 😝.

Of course, if you really want to, a deb/rpm packaging _wouldn't hurt at all_.

I would do that (sometime, no promises when), if there was a way to statically compile whatever _a nominal Ubuntu system would lack_ e.g. `libboost`; however, I am barely able to navigate `autoconf` stuff.

So far I just miraculously made everything work by copying the `cp2bin`'s target outside of the `Dockerfile`

**Comment by genivia-inc** [comment]
I've updated the README to make it more clear where the binaries are located in the repo. I've also updated the `build.sh` script to report the location of the locally built ugrep binary.

I will consider creating a Linux rpm package, it's on my list.

Sorry for the delay. I've been busy working on ugrep 2.0 that is ready now. The new `-Q` option is awesome, if I may say so myself.

**Comment by stdedos** [comment]
I've tried to see in which commit you did it / if you did it for the release.

So you can imagine how quickly my enthusiasm deflated when I saw that 2.0 is a singular commit ...

**Comment by genivia-inc** [comment]
Not sure what you are really looking for. The binaries are all under `ugrep/bin/ugrep`, including the locally-build binary as reported by `build.sh`. The only fully portable binary that I can create is for Windows, i.e. `bin/win32/ugrep.exe` and `bin/win64/ugrep.exe`. I could add these two as assets.

Once I have the Homebrew formulas ready, I will remove the MacOS and Linux binaries from the repo. These are limited anyway due to portability issues.

**Comment by stdedos** [comment]
> Not sure what you are really looking for.  [...]
> Once I have the Homebrew formulas ready, I will remove the MacOS and Linux binaries from the repo. These are limited anyway due to portability issues.

Exactly that.

Also, as I said the files in `bin/linux/ugrep` does not work, whereas `bin/ugrep` runs. I don't know what are those portability issues, but ... can't you statically build external stuff, and compile against a "generic architecture" for the rest?

**Comment by genivia-inc** [comment]
> can't you statically build external stuff, and compile against a "generic architecture" for the rest?

Statically building the tools for Linux won't make ugrep _binary portable_ to different architectures, e.g. consider x86 versus ARM. Package managers such as rpm, YUM, Homebrew are designed to do just that. Otherwise, there is no guarantee that the executable runs due to CPU differences.

MacOS is less of an issue these days since the PowerPC era has long passed and x86 CPU variants are pretty standard with MacOS (e.g. i5 and i7). But even these x86 CPU differences require essentially building ugrep statically with all AVX/SSE2 optimizations turned off. So you'll be missing out on performance.

IMO the best way to move forward to simplify the installation process without requiring manually installing libpcre2 and compression libs is to create Homebrew formulas for MacOS (Linux perhaps) and e.g. rpm for Linux.

The Dockerfile is included so that anyone can try ugrep if they don't want to build ugrep on their native OS. I am not sure if the ugrep executable built in the container is compatible to the native OS. Likely not in most cases.

**Comment by genivia-inc** [comment]
With [Homebrew](http://brew.sh), binaries for MacOS (and Linux) can now be easily and safely installed as follows:

    brew install https://raw.githubusercontent.com/Genivia/ugrep/master/Formula/ugrep.rb

I'll commit a Homebrew formula once the required GitHub notoriety level is reached. I'll also work on an RPM package when I find the time.
