### ISSUE TITLE
Does ugrep support negated patterns in .gitignore?

### ISSUE THREAD

**Issue by arrufat** [Genivia/ugrep#240]
I think it does not.

From the [documentation](https://git-scm.com/docs/gitignore):

> An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again.

I like to use this kind of `.gitignore` pattern in my projects:

```.gitignore
/*
!/CMakeLists.txt
!/.editorconfig
!/.gitignore
!/LICENSE
!/README.md
!/src/
```

That is, using it as a white list, so I don't need to bother about temporary files, or build directories, etc.

However, when I use `ugrep --ignore-files` it still finds matches in directories not in the `.gitignore`.

Thanks in advance :)

**Comment by genivia-inc** [comment]
Yes, this feature is supported and tested.

But why are you're using a leading `/*`? You're basically telling ugrep to only ignore the files and directories at the root specifically, not the subdirectories.

I suppose it depends on how to interpret `/*`. Ugrep right now ignores the files and directories that match the `/*` pattern, so `/file` and `/dir` for example, but not `/dir/file` since the `/*` glob doesn't match this.

To ignore all paths from the root specify `*` or more explicitly specify `/**` that matches any path from the root.

**Comment by arrufat** [comment]
Right, adding an extra `*` worked like a charm.
Thank you!

**Comment by arrufat** [comment]
Thank you for your reply.
I was asking this because the pattern I described works as I expected using ripgrep.

If I put files in the `/src/` directory, `git status` shows them as untracked (expected behavior).

If I change the first rule to `*` or `/**`, then ugrep doesn't find files inside `src/` for instance (neither does ripgrep in that case either).
Moreover, `git status` does not show newly added files inside `/src/` either.

So, there's some misalignment between how git (and ripgrep) interpret the rules in the `.gitignore` file and how ugrep does it.

**Comment by arrufat** [comment]
Ah, thank you, adding `/*/` makes it work as I intended. Thank you :)
