### ISSUE TITLE
Gui for ugrep?

### ISSUE THREAD

**Issue by harryray33** [Genivia/ugrep#247]
Is there any sort of frontend for ugrep, or is it just a CLI?

Thanks.

**Comment by genivia-inc** [comment]
Good question.

The TUI is a separate module defined in ugrep/src/query.cpp. This module relies on ugrep/src/vkey.cpp for keyboard access and ugrep/src/screen.cpp for terminal display. It calls ugrep's "API functions" that initiate multi-threaded searching and stops searching (e.g. when the pattern is changed the current search should stop). The ugrep "API" could be more cleanly designed, so it would be more easy to use by another application, but that is a matter of naming and documentation I suppose, which I haven't worked on (yet) as ugrep was evolving.

There's also some logic in ugrep/src/query.cpp to deal with searching standard input as a special case, because standard input may be searched multiple times so we need to store its contents in a buffer and replay it on demand.

In principle it should be possible to develop a GUI that replaces ugrep/src/vkey.cpp and ugrep/src/screen.cpp for keyboard input and display output in a GUI window. The vkey functions are all called with VKey::function() and the display functions are all called with Screen::function(). The ugrep/src/query.cpp logic includes low-level line editing logic (the regex pattern) and more interactive features. Query functions and variables are static in a class Query, as you can see in query.hpp. Protected and private member variables are suffixed with `_`.

PS. I wanted to extend ugrep's TIU with a window (a split window) to show a list of matching files, like with option `-l`, and a separate window showing the matches in a file selected from the list or the top one in the list. It can be done in a TUI, just need to figure out how this would work in practice in an intuitive way.
