### ISSUE TITLE
Line numbers with --hyperlink

### ISSUE THREAD

**Issue by fabian-thomas** [Genivia/ugrep#252]
#133 has added support for terminal hyperlinks. Especially when using --heading it would be nice to have line numbers in the link as well and to have line numbers also have a link.

 A recent pull request on ripgrep adds exactly this, just for reference: https://github.com/BurntSushi/ripgrep/pull/2483

**Comment by genivia-inc** [comment]
Good point! I remember vaguely that line numbers didn't work properly with hyperlinks under testing with terminals that support hyperlinks (it has been almost two years since hyperlinks were added, so I don't recall the details of this specific test.) I am curious if these terminals were updated to accept hyperlinks with colons? How would the terminal interpret a link with a colon + line number? I understand it can be a useful addition, but I've never used it myself, so I'm asking.

**Comment by fabian-thomas** [comment]
It seems like [vscode supports file hyperlinks with lines](https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/command-line.md#opening-vs-code-with-urls). Even columns work. I myself use a custom xdg-open script that handles these file links and passes them to emacs.
All of this is independent of terminals. Terminals just need to recognize the escape sequence and pass the embedded link to xdg-open which then handles the rest.

**Comment by genivia-inc** [comment]
We could expand the `--hyperlink` option to also take a parameter `--hyperlink=nk` to include line number and column number as well? This offers more flexibility in the future to adjust hyperlinks. Also the `GREP_COLORS` specification has a `hl` parameter that can be update to take parameters to include line/column numbers with `hl=nk`.

**Comment by fabian-thomas** [comment]
That would work for me, but probably not out of the box for other people. As I understand, usual file:// links do not have support for line and column. Editors like vscode add their custom schemes (vscode://) as mentioned above.

I think we would need something stronger, like the option provided in ripgrep. Something like:
`--hyperlink-format 'vscode://{host}/{file}:{line}:{column}`

**Comment by genivia-inc** [comment]
No problem, since it can simply be done with a short-hand form `--hyperlink='vscode://file/%f/%n/%k'` where the `%` fields are the same as the `--format` fields. Then also the specified colors can be `hl=vscode\://file/%f/%n/%k`. There is a minor problem with using a colon in the `--colors` arguments, since colons separate grep colors traditionally. Perhaps an escape `\:` is best.

I don't follow what `host` should be as a parameter, probably it's always fixed to whatever machine you're working on or is it just `file`?

I don't like the idea of hardcoding `vscode:` at all. It is too specific.

**Comment by fabian-thomas** [comment]
> No problem, since it can simply be done with a short-hand form `--hyperlink='vscode://file/%f:%n:%k'` where the `%` fields are the same as the `--format` fields. Then also the specified colors can be `hl=vscode\://file/%f\:%n\:%k`. There is a minor problem with using a colon in the `--colors` arguments, since colons separate grep colors traditionally. Perhaps an escape `\:` is best.

Sounds fine. 

> I don't follow what `host` should be as a parameter, probably it's always fixed to whatever machine you're working on or is it just `file`?

Yeah, that is the hostname of the machine. Helps when you are doing remote development. Your pc can then figure out on which machine the file you are asking for is present.

> I don't like the idea of hardcoding `vscode:` at all. It is too specific.

Me neither. If one can specifiy the scheme we are fine.

**Comment by genivia-inc** [comment]
The basic hyperlink info that ugrep follows is sourced from: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

The use of `file://` and `localhost` is taken from this info.

I wonder if it wouldn't be easier and less confusing to just allow the specification of parameters with `--hyperlink=...` and pseudo color parameter `hl=...`:
- `--hyperlink=vscode` to specify a `vscode://` prefix instead of the default `file://`
- `--hyperlink=vscode#` to specify that line numbers should be included
- `--hyperlink=vscode##` to specify that line and column numbers should be included

So that `#` generates the `file://...:<num>` format and `##` generates the `file://...:<num>:<num>` format.

In hindsight, the use of `%` fields names from `--format` is an overkill perhaps, but also requires escaping the colons in the `hl` color, which can be confusing and may lead to errors if escaping is not used.

I think I will go in this direction for a first iteration.

**Comment by genivia-inc** [comment]
I've committed an update v3.11.2, but will not create an official release yet until I get feedback about the updated `--hyperlink` behavior. I tested it marginally, but I am not a power user of Windows terminals to be 100% confident the vscode cfg-open actions work as expected. So please check it out. The binaries are in bin/win32 and bin/win64. They link against Ws2_32.lib for `gethostname()` to populate the host name in the hyperlink instead of a fixed `localhost`.

**Comment by fabian-thomas** [comment]
Thanks for implementing this so quickly!

Tested it on arch linux. Hostname works. Basic functionality is working too. Two things I noticed:
- does not work yet with `--heading`. The line numbers should have links themselves. And the section headers should then have no line number in their link.
- line numbers are not embedded in the label of the link. My terminal underlines everything but the ending line number plus colon (`:1`) as link

Column support would be nice to have but is not a deal breaker.

**Comment by genivia-inc** [comment]
So with `--heading` the line numbers individually displayed should have the full link with line number? Makes sense.

I do not follow what you mean with _"line numbers are not embedded in the label of the link. My terminal underlines everything but the ending line number plus colon (:1) as link"_ The links are formatted as _file://{host}/{...path...}/{file.ext}:{num}_ and include the line number after a colon if `--hyperlink=+` is specified.

**Comment by genivia-inc** [comment]
OK. I think you are alluding to the fact that `--hyperlink=+` should include line numbers with all file:// links outputted. So `--hyperlink=+` adds the link to the filename header output (when present e.g. with `-H`) and separately also to the line number output (when present with `-n`). Note that `--hyperlink=vscode+` adds line numbers the same way, but replaces file:// with vscode://.

**Comment by genivia-inc** [comment]
OK. Try it now with the latest 3.11.2 update. The ugrep.exe are in bin/win32 and bin/win64.

**Comment by genivia-inc** [comment]
A column number can be added to the link as well, but it is not clear to me what would need to be linked in the output. For example, the line number in the output can have the file+line link as done in the latest update. The column number in the output can have a separate the file+line+column link. Or perhaps better, should both the line and column number in the output have the same file+line+column link? Like when line 99 and column 77 are displayed as 99:77 then both share the same link? This makes it easier to click on it.

**Comment by fabian-thomas** [comment]
> So with `--heading` the line numbers individually displayed should have the full link with line number? Makes sense.

Exaclty.

**Comment by fabian-thomas** [comment]
> A column number can be added to the link as well, but it is not clear to me what would need to be linked in the output. For example, the line number in the output can have the file+line link as done in the latest update. The column number in the output can have a separate file+line+column link. Or perhaps better, should both the line and column number in the output have the same file+line+column link? Like when line 99 and column 77 are displayed as 99:77 then both share the same link? This makes it easier to click on it.

Yes, file, line and column should all be one link.

**Comment by fabian-thomas** [comment]
I can't test the changes since I get a segfault when running ugrep with:
`ugrep --line-number --heading --hyperlink=file+ pattern`

**Comment by genivia-inc** [comment]
Two things:
1. I just now noticed `--heading` is not working yet.
2. It might be best to produce one link that spans the filename, line number and column number.

**Comment by genivia-inc** [comment]
I've made a couple of changes to the logic to output file info headers/headings. The problem was that the pathname "disappeared" with option `--heading`, so `--hyperlink` couldn't produce it which in turn leads to a crash.

A new update is committed.

**Comment by fabian-thomas** [comment]
Now both heading and no-heading work fine for me. Columns also work. Thank you again!

One final minor thing I noticed:
- the heading should only have the file in the link. Not line and column.

**Comment by genivia-inc** [comment]
Yep. That was a side effect of the mixed logic that treats the first pathname output as the heading when `--heading` is used. Not difficult to work around with an extra logic test. I've made a minor change and committed the update.

**Comment by fabian-thomas** [comment]
It's fixed 👍🏼
