### ISSUE TITLE
required equals sign for flag with value

### ISSUE THREAD

**Issue by carlwgeorge** [Genivia/ugrep#255]
I noticed something inconsistent today with ugrep.  Most CLI tools allow you to provide long arguments with a value either with our without an equals sign, e.g. `--include=meson.build` or `--include meson.build`.

```
[carl@teal:~/packaging/copr/hyprland/hyprland-source]$ grep --recursive --include=meson.build cairo
subprojects/wlroots/meson.build:		'cairo-tests=disabled',
src/meson.build:    dependency('cairo'),
src/meson.build:    dependency('pangocairo')
[carl@teal:~/packaging/copr/hyprland/hyprland-source]$ grep --recursive --include meson.build cairo
subprojects/wlroots/meson.build:		'cairo-tests=disabled',
src/meson.build:    dependency('cairo'),
src/meson.build:    dependency('pangocairo')
```

I tried to pass an include pattern to ugrep, and it only works with the equals sign.

```
[carl@teal:~/packaging/copr/hyprland/hyprland-source]$ ugrep --recursive --include=meson.build cairo
subprojects/wlroots/meson.build:		'cairo-tests=disabled',
src/meson.build:    dependency('cairo'),
src/meson.build:    dependency('pangocairo')
[carl@teal:~/packaging/copr/hyprland/hyprland-source]$ ugrep --recursive --include meson.build cairo
ugrep: missing argument for --include
For more help on options, try `ugrep --help' or `ugrep --help --include'
```

**Comment by genivia-inc** [comment]
In general this is necessary to allow arguments to be optional. This syntax is not uncommon and personally I am a big fan of using this syntax consistently that makes it immediately clear what is passed to a long argument.  GNU grep and BSD grep do the same as ugrep, but BSD grep has some historical/legacy exceptions, such as `--include FILE`. GNU grep does not have this exception, at least not shown in the GNU grep man page, see e.g. https://man7.org/linux/man-pages/man1/grep.1.html

**Comment by genivia-inc** [comment]
Can we close this? The GNU grep manual does list `--include=GLOB`. Only BSD grep doesn't in this case, but otherwise also requires an `=`.

**Comment by genivia-inc** [comment]
@carlwgeorge 
> Does ugrep have any long option flags where the parameter to the flag is optional? In other words, each flag should either be standalone (e.g. --text) or take a parameter (e.g. --include=<parameter>), not both.

Yes, of course. Just like GNU grep there are some parameters that are optional:
~~~
--color[=WHEN], --colour[=WHEN]
~~~
So that is why we should not ditch the `=`. It would make long option syntax inconstant.

It is regrettable that some (new) utilities still do not use `=` with long options. But that's their fault (since once you do that, there is no way back without upsetting users.)

**Comment by genivia-inc** [comment]
I do not use `getopt` since I need ugrep to be portable to Windows and also because I want to produce a helpful error message with suggested alternatives when a long option does not match.

**Comment by carlwgeorge** [comment]
It seems that for grep the equals sign *is* required only if the parameter to the flag is optional.

`grep --color never foo`
- `--color` is the flag
- `never` is the pattern
- `foo` is the file to search in

`grep --color never foo bar`
- `--color` is the flag
- `never` is the pattern
- `foo` and `bar` are the files to search in

`grep --color=never foo bar`
- `--color=never` is the flag
- `foo` is the pattern
- `bar` is the file to search in

After checking the man page, it seems this flag and the alternate spelling `--colour` are the only grep flags that allows an optional parameter, and thus the only flags that require an equals sign.  I do see what you mean that ugrep has several additional flags like this.  I think that only requiring an equals sign only when the flag parameter is optional is a sane way to handle this.

This project advertises it's strong compatibility with grep, but I feel like this subtle option parsing difference is a bigger compatibility problem than it appears.  It could be disruptive for folks who want to use ugrep as a drop in replacement for grep in their existing scripts and one-liners that use the common `--flag <parameter>` (space instead of equals) syntax.  This is why I would prefer for ugrep to match the option parsing behavior from grep.  I know that you closed this already, but I'm hopeful that the above information might cause you to reconsider.  It is of course your prerogative to decline and keep this closed.

**Comment by genivia-inc** [comment]
Sorry, I'm still not convinced this is an issue. I've never seen frequent use of `--flag <parameter>` with grep anywhere. I can't find much about this on the web. The GNU grep man page does not list long options with spaces either. All long options with arguments are shown with `=`. There may be anecdotal cases, perhaps in legacy systems. But for grep, it's always been `--flag=<parameter>` as far as I can tell.

When the `=` is omitted, then ugrep complains that an argument is required, so this will never go unnoticed. That's important to correct the command line and it is very simple to do given that ugrep tells you that the argument is missing for a specific option.

And finally, there are many different versions of grep. There is GNU grep and BSD grep for example. Both differ somewhat in options too, but are still considered compatible (and "drop-in replacements"), because they share a base set of well-documented grep options. But there are small differences!

BSD grep takes an optional NUM with `--context` :

`-C[num], --context[=num]`

But GNU grep does not:

`-C NUM, -NUM, --context=NUM`

So if GNU grep allows omission of the `=`, then BSD grep and GNU grep are no longer compatible. When a space is used with GNU grep then `--context NUM` still works. But not with BSD grep, since `--context NUM` uses the default `--context` value and `NUM` is another command-line arguments. That's why spacing is bad. That's my point.
