### ISSUE TITLE
ug does not read conf file

### ISSUE THREAD

**Issue by damanis** [Genivia/ugrep#267]
**Version**: 3.12.2.
**Compiled**: manually (build.sh).
**Error**: `ug` command ignores `~/.ugrep` configuration file.
Previous version, 3.12.1, also compiled manually, worked as expected.

**Comment by genivia-inc** [comment]
Strange, there is no difference between v3.12.1 and v3.12.2 with respect to config file reading. The logic is the same.

Works on all my machines.

Are you sure?

**Comment by genivia-inc** [comment]
Note that `--pretty` is now the default for **ug**. This means that if this option is not desired, a .ugrep config must set `no-pretty`. Then you can still have `color`, `line-number`, `heading`, `break` and `tree` etc in the .ugrep file for these specific options (because `--pretty` sets all these).

**Comment by genivia-inc** [comment]
Let me know if this is a problem and what the details are when you tested this further. For now, I'm closing this until I hear back.

**Comment by damanis** [comment]
@genivia-inc 
You right, adding `no-pretty` to `~/.ugrep` solve the issue.
Thank you.
