### ISSUE TITLE
Case-insensitive file name matching: currently -j doesn't apply to -g globs

### ISSUE THREAD

**Issue by pvarga-dni** [Genivia/ugrep#268]
When specifying `-j` (smart-case matching), this only applies to the regexp used to search file contents, not the glob pattern(s) eg. `-g` used to filter files' names.

I think it should either apply to those as well or there should be case-insensitive variants of those command line flags. 

_Used_: `ugrep 3.9.6`

**Comment by genivia-inc** [comment]
You can use `ALT-g` for option `-g` interactively in the TUI to specify globs. File globbing is case sensitive though.

Press CTRL-Z or F1 for an option list, which shows `M-g` to set globs.

**Comment by genivia-inc** [comment]
It would be possible to have a new option for case-insensitive globbing. It's just a bit much for yet another option that may not be as often used, perhaps.

Thanks for the suggestion. I'll think about it.

**Comment by pvarga-dni** [comment]
I have also looked at `ripgrep` and it has these command-line flags: `--glob-case-insensitive` and also `--iglob`. However, at least according to the documentation, these don't offer an ideal user experience because when `--glob`/`--iglob` are used, other ignore rules - such as taking `.gitignore` files into account - won't be in effect...

**Comment by genivia-inc** [comment]
Adding such an option is almost trivial to do in ugrep. The glob matching is done with a single fast glob matcher, see my  [Code Project article](https://www.codeproject.com/Articles/5163931/Fast-String-Matching-with-Wildcards-Globs-and-Giti) for details on my fast gitignore-style glob matcher. The article also mentions case-insensitive glob matching, of ASCII globs that is, not Unicode in general. When making this glob matcher case-insensitive (when an option is enabled) then it will apply to all globs, including the .gitignore globs.

Does that sound like a feature you and others may want to have?

**Comment by pvarga-dni** [comment]
@genivia-inc Yes, however I think to follow the "principle of least surprise", it should only apply to user-supplied globs (command line arguments, input in the TUI), and not to globs from `.gitignore`

**Comment by genivia-inc** [comment]
> @genivia-inc Yes, however I think to follow the "principle of least surprise", it should only apply to user-supplied globs (command line arguments, input in the TUI), and not to globs from `.gitignore`

`--glob-ignore-case` will apply to all glob-related options, which are `-g` (`--glob`), `-O` (`--flag-file-extension`), `-t` (`--file-type` since it uses globs),  `--include`, `--exclude`, `--include-dir`, `--exclude-dir`, `--include-from` (to import globs), `--exclude-from` (to import globs). This applies to files and directories found along the search paths as well as files and directories found in archives such as zip and tar.

If we omit .gitignore or any `--ignore-file` from case-insensitive glob matching, then things get a bit more interesting. A simple way is to temporarily turn off `--glob-ignore-case` when a .gitignore file is found. This is necessary, because glob matching is done simultaneously "at once" per file and per directory by the main thread. It's not done separately for .gitignore globs. The way that works is rather elegant by building up sets of globs of files to skip (exclude) and files to (only) include. This approach works really well and fast with ugrep. Like I said, `--glob-ignore-case` will have to be temporarily turned off when a .gitignore file is found. Not sure if that hampers practical use cases, but it might lead to surprises, perhaps.

As an alternative, there is always a way to do things. One way will require more logic to place globs in new special glob include/exclude glob sets that are specifically only used for case-insensitive glob matching. That will still enforce it, even when .gitignore files are found. It's a heavy-weight solution to work with internally and I don't really like it because it duplicates data and the work that happens behind the scenes.

**Comment by genivia-inc** [comment]
Ah, I just realized there is a much simpler way to leave .gitignore globbing as it is when `--glob-ignore-case` applies to all other globs specified on the command line. These .gitignore globs are pushed on vectors, so we know "where they are" to be treaded differently. This keeps the logic simple. No code bloat.

**Comment by genivia-inc** [comment]
I've already completed an update a couple of days ago that adds `--glob-ignore-case` and `--iglob=GLOB,GLOB,...` options. The `--glob-ignore-case` does not apply to `--ignore-files` such as .gitignore.

The ugrep version with these new options will be released soon, together with the other planned additions. I'm working on an indexer for ugrep to speed up searching by skipping over all static files that do not match, see #136.

**Comment by genivia-inc** [comment]
Implemented in ugrep v3.12.5.
