### ISSUE TITLE
No error message when searching directory without recursion

### ISSUE THREAD

**Issue by mohd-akram** [Genivia/ugrep#270]
It would be useful to have an error message printed when running `ugrep` on a directory without providing a recursive flag, similar to grep which prints `grep: dir: Is a directory`.

**Comment by genivia-inc** [comment]
Thanks for the question.

No, I don't believe that would be nicer. Many other unix utilities, like `ls` for example, do accept a directory without requiring flags. Only `rm`, `mv` and `cp` do warn about this, but that makes sense for these tools, because these affect the filesystem contents and specifying a directory is ambiguous. Specifying a directory with `ugrep` is not ambiguous at all. When a directory is specified, it basically represents the files stored in it at the first level. So `ugrep` simply searches the specified directory only at one level deep, unless `-r` or `-R` is specified, just like `ls` does. Than `ugrep` man page mentions this behavior.

Note that `ug -l ""` is similar to `ls`. Not exactly the same, but you get the idea.

**Comment by mohd-akram** [comment]
I see, I was not aware that ugrep actually searches the first level of the directory by default. I almost remember that *not* being the case before, but I'm not sure.
