### ISSUE TITLE
`make test` error in Ubuntu 18.04

### ISSUE THREAD

**Issue by stdedos** [Genivia/ugrep#276]
Hello @genivia-inc,

Would you be interested to spend 5 minutes to figure out what this `make test` error is?

https://github.com/stdedos/ugrep/actions/runs/5849656652/job/15858225852

It is build on Ubuntu 18.04 - so understandably it uses older dependencies.

**Comment by genivia-inc** [comment]
Whoa, this is not supposed to happen, ever.

The ugrep engine uses a decompression stream (the zstreambuf class I wrote) that handles all compressed input. It decompresses files only when the corresponding libraries are installed. When zstreambuf encounters a decompression library error reported by the library itself with a not-OK (error) return value, it propagates this error to ugrep with a message. In this case, `ZSTD_isError(ret)` is true after `ret = ZSTD_decompressStream(...)` is called to decompress input.

This looks very likely a zstd library failure for some reason. It could be an old issue perhaps. or the zstd was updated later and produces output that is not compatible with old zstd library versions.

Otherwise, I don't know why it would fail on a zstd-compressed file in the ugrep test suite.

**Comment by stdedos** [comment]
There is also an innate Gitlab state for this

![image](https://github.com/Genivia/ugrep/assets/133706/27927de1-1ac2-4818-a15b-30150bae575b)

**Comment by genivia-inc** [comment]
Yeah, I remembered that too late. Was not able to change the state without reopening and closing...

**Comment by genivia-inc** [comment]
OK. Looks like GitHub has a bug, because I cannot change the state with the drop-down below. Trying one more time...
