### ISSUE TITLE
idea: mark matches with tags

### ISSUE THREAD

**Issue by yangshuairocks** [Genivia/ugrep#28]
Right now ugrep has a `--colors=COLORS, --colours=COLORS` parameter to let the user mark different parts of the matches with different colors. However, this is only useful in a console environment. When the result of ugrep was redirected to a file, all colors will disappear. If there is an option like `--tags` to let the user mark different parts of the matches using different text string, it will be more useful. For colors, we only need a single parameter for a matching part. For example, for selected lines we provide a color. But if we mark selected line with text, there will be a begin selected line and an end selected line.

**Comment by genivia-inc** [comment]
Thanks for the feedback. Interesting idea, which reminds me of the old trick with grep to trick it into producing matches marked by user-define "tags" by exploiting `GREP_COLORS`. That trick does no longer work with GNU grep, possibly due to reliability and security concerns.

I'll take a look at introducing an option to produce tagged matches instead of colors. In addition, it would be possible to indicate which of the specific sub-patterns among alternations matched. For example, searching for `\d+|\w+` marks numbers as 1 and words as 2. However, if the user specifies tags with option `--tags` there are many ways these tags could be defined and without a tag numbering. Some food for thought to design this properly.

**Comment by genivia-inc** [comment]
I propose the following new option:
~~~
--tag[=TAG[,END]]
            Disables colors to mark up matches with TAG.  If END is specified,
            the end of a match is marked with END.  The default is `___'.
~~~
As I mentioned earlier, it would be nice to mark matches by sub-pattern index or group capture index. However, that turns out to be very expensive with a cost that we cannot hide even when such an enhanced tag option is not used. Instead I opted to enhance `--format` with a new field `%g`. This field is the group capture index produced by option `-P` and the sub-pattern index when `-P` is not used. For example, `--format='%g: %o%~'` produces pattern-indexed (`%g` group) matches (`%o` match only) on the output.

**Comment by genivia-inc** [comment]
As a side note: the `--tag` option does not mark the start of a matching line (e.g. to distinguish it from context lines). However, this is already accomplished when line numbers are enabled with option `-n` because the separator changes from `:` to a dash `-`.

The `--tag` option is useful for enhanced viewing without colors and to allow output to be marked for further processing by another utility down the pipe.

**Comment by genivia-inc** [comment]
I've added option `--tag` to the latest release v2.1.0. Thanks for posting the idea.

**Comment by yangshuairocks** [comment]
Thank you for the hard work! It works great!
