### ISSUE TITLE
Q mode usability

### ISSUE THREAD

**Issue by nkh** [Genivia/ugrep#282]
I installed ug on my machine few years ago and I used it 1 minute total.

I first installed it for speed, I sometimes have some large amount of data and need to find specific files, yes it's because I forget where they are, not that I get new data all the time ;)

Speed is indeed very good but being a grep and rg user I've never really missed the speed and waiting 10% of the time more doesn't make a difference in my case.

the second interest was interactive queries, coming from fzf I very quickly stopped trying ug:
- the low rate of refresh even with Q set to 1
- the unsightly [end] block
- the colors
- the confirmation for quitting
- the [searching start] flickering

and the feeling that search results are not kept but everything started again, I understand the effect on memory usage even though I wonder if the search itself wouldn't be faster if the query is analyzed and the next search is found to be a subset of the previous results.

of course none of those are not fixable with a few options but I believe that because of those points there is very little incentive for people to leave FZF which is a pity because I've seen a lot of people wanting to do non fuzzy searches and sometime to go from one to the other, something I believe ug is better fitted for

I hope these points can be of help and even if they sound negative my intent was to give honest feedback and maybe a few ideas for improvement

**Comment by genivia-inc** [comment]
> the second interest was interactive queries, coming from fzf I very quickly stopped trying ug:
> 
> * the low rate of refresh even with Q set to 1
> * the unsightly [end] block
> * the colors
> * the confirmation for quitting
> * the [searching start] flickering

A few notes since you may have missed it in the man page and the README and help page that tells you what to do:

- The delay can be set to almost zero with -Q=1 (just create an alias for `ug -Q=1` e.g. `uq`). The reason there is a delay is **because ugrep will search the entire directory tree (file system) by default. This will burn up your CPU if typing every key will cause a new search to start and cancel**. FZF is a lightweight search engine, but ugrep is not.
- [end] block is not helpful? How? It's the same as the `more` and `less` commands, so looks familiar.
- colors can be changed in the .ugrep config, this is simply the GNU grep default since ugrep defaults to GNU grep
- confirmation in quitting is disabled with no-confirm in .ugrep config file
- flickering is only visible on Windows machines. I don't know why it would be in your case. It only refreshes when the search is still going on.

Ugrep is very easy to configure if you spent a few minutes reading the instructions.

**Comment by genivia-inc** [comment]
> I first installed it for speed, I sometimes have some large amount of data and need to find specific files, yes it's because I forget where they are, not that I get new data all the time ;)
> 
> Speed is indeed very good but being a grep and rg user I've never really missed the speed and waiting 10% of the time more doesn't make a difference in my case.

Well, the [new ugrep with benchmarks](https://github.com/Genivia/ugrep-benchmarks) show that ugrep is almost always significantly faster than rg and grep. Some patterns take seconds to search with rg and grep when ugrep only takes a few tens of a second.

There are still opportunities to speed up ugrep so ugrep will continue to get faster.

Development on ugrep started in earnest only two years ago (it was a prototype [RE/flex](https://github.com/Genivia/RE-flex) grep example before that) with new optimizations and new features. Now is the time to converge to an even faster and more capable ugrep.

**Comment by nkh** [comment]
I wouldn't call FZF light weight, nor Rg slow, since I'm trying to use ug more I did use it this afternoon and for the use case I had I don't need benchmarks to know that ug is slower, of course it's because the setting are different, they find a completely different number of files, so more tweaking is necessary before I have a first hand well setup ug. Something I'm looking forward to. 

You certainly have reasons for not interrupting the running processes but in the human waiting for feedback realm, the delay is felt, and I run a linux machine, plenty ram and fast ssd. keeping files in ram doesn't slow down search, or please explain to me why as I may be wrong and I'm curious, on the other hand most searches are iterative which means less matches for each search which means fewer file processing. But we all have good reasons for architectural decision I just want to be a ball plank.

 I'm happy to read that there are options to mitigate some of my concerns about the UI, but don't take my word for it, put someone you trust in front of FZF and ug -Q1 and hear what they say about the UI look and feel. It's of course normal as FZF has had years to polish things up, with the same amount of effort I have no doubt they would be both as pleasant to use. And I need to spend more time in the docs and try all the tweaks.
 
 It's great to hear that there are more opportunities for speed improvement even if it's not my use case, it will help other. if ug is just around two years old then I must have caught one of the first release, I'm happy the project is a success.

Looking familiar and looking good is not the same, and I have the less colors changed (will do the same with ug) but less doesn't have [end] blink 10 times a second. 

thank you for answering or commenting the points I listed

- the low rate of refresh even with Q set to 1 -> architectural
- the unsightly [end] block -> option, not sure which one in the GREP_COLORS
- the colors -> option
- the confirmation for quitting -> option, an a good one!
 the [searching start] flickering -> not answered

Once I'm more familiar with ug I'll also write about the things I like, I can tell you that --format is going to be one of them.

Thank you for the answers.

**Comment by genivia-inc** [comment]
> I wouldn't call FZF light weight, nor Rg slow, since I'm trying to use ug more I did use it this afternoon and for the use case I had I don't need benchmarks to know that ug is slower, of course it's because the setting are different, they find a completely different number of files, so more tweaking is necessary before I have a first hand well setup ug. Something I'm looking forward to.

Lightweight because of low thread and CPU utilization to search. My comment has nothing to do with the size of the tool or features. Hope this clarifies that.

Also, there will always be some patterns for which one or the other tool runs faster. Different algorithms give different performance results. There are some things that I know how and where to optimize in ugrep. It's not difficult, just making sure there are no bugs. Ripgrep has bugs actually, likely because of optimizations that create many logic flows that aren't all tested and verified. That is a nightmare (for me, at least).

> I'm happy to read that there are options to mitigate some of my concerns about the UI, but don't take my word for it, put someone you trust in front of FZF and ug -Q1 and hear what they say about the UI look and feel. It's of course normal as FZF has had years to polish things up, with the same amount of effort I have no doubt they would be both as pleasant to use. And I need to spend more time in the docs and try all the tweaks.

In order to address concerns, I need to know what machine is used. The windows terminal is not a good one and ugrep's response will feel slower.

Also, if you restart a search by typing, then the previous search must be cancelled. If the previous search is searching a huge compressed file then this cannot be terminated immediately as this will cause problems with the compression libraries such as memory leaks if terminated without proper close. That is why the decompression has to complete first, which will increase the response time for the next search.

I have yet to hear from someone that this can be done. I don't believe it is possible, unless running forked processes that can be killed. But that is a design that has a lot of overhead. And no, IPC with a forked process is not a better solution.

Things are not as trivial as one might believe.

> Looking familiar and looking good is not the same, and I have the less colors changed (will do the same with ug) but less doesn't have [end] blink 10 times a second.

What machine and terminal are you using? I don't see this at all on Linux-based machines.

> thank you for answering or commenting the points I listed
> 
> * the low rate of refresh even with Q set to 1 -> architectural

No. This is fundamental. Ugrep is a "classic" grep tool with a TUI. Any TUI must terminate and rerun a search with 8 threads in the background. This adds latency. Slowing down search to improve the TUI response time is not a good option either. If you want to limit search overhead, just use option -J1 to run only one search thread. That can speed up the TUI response time.

> * the unsightly [end] block -> option, not sure which one in the GREP_COLORS

Not in GREP_COLORS. It's just the same as `more` and `less` show at the end. Without it, it is not clear when the search ended. Believe me. I had an implementation without the [end] but had to scroll way past the end to feel confident that the search ended. Consider the implications when there is no [end].

I don't see flickering on Linux-like machines and nobody else has complained about that either. Windows has this problem due to their terrible terminal designs and the fact that only polling 10 times a second allows responses to window events to be registered, instead of Linux events that do not need polling. So again, what machine/OS are you using?

The fact that the ugrep TUI window is responsive to mouse scrolling and resize is important too.

> * the colors -> option
> * the confirmation for quitting -> option, an a good one!
>   the [searching start] flickering -> not answered

See above.

**Comment by genivia-inc** [comment]
Still looking for responses to my questions (inline) to answer your questions and a few more to understand your concerns.

- What machine and OS are you using when you encountered some flickering in the TUI?
- When does the flickering actually happen?
- Is the TUI response latency on all machines/OS similar? Or quicker/slower?
- Have you run ugrep on other machines/OS? If so, which ones?
- Have you tried the latest ugrep release? What is the release you're using?

**Comment by nkh** [comment]
-  What machine and OS are you using when you encountered some flickering in the TUI?
     - Linux generic #86-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux
     - Tmux over Konsole
     
-  When does the flickering actually happen?
    - when changing the search string
  
-  Is the TUI response latency on all machines/OS similar? Or quicker/slower?
     - no  problem with flickering even with software written in Bash
     
- Have you run ugrep on other machines/OS? If so, which ones?
    - no
    - 
- Have you tried the latest ugrep release? What is the release you're using?
    - ugrep 3.7.2 x86_64-pc-linux-gnu +sse2 +pcre2_jit +zlib +bzip2 +lzma +lz4 +zstd
    - building the latest right now

**Comment by genivia-inc** [comment]
Ah, finally... thanks for the details.

Test results to enter a search string, change options, move cursor, scroll screen:

- No flickering issues w/ Tmux and w/o Tmux on MacOS terminal and X11 xterm.
- No flickering issues w/ Debian Tmux and w/o either (not tried Konsole)
- No flickering issues with ugrep w/ and w/o Tmux using Android termux.

Not entirely surprising, because there is no terminal polling performed by ugrep on *nix systems. Flickering is a known issue with Windows ugrep.exe because of polling to allow reactive window resizing.
