### ISSUE TITLE
`--pager` should start `$PAGER`

### ISSUE THREAD

**Issue by walles** [Genivia/ugrep#286]
With `ugrep 4.0.4 x86_64-apple-darwin22.4.0 +avx2 +pcre2jit +zlib +bzip2 +lzma` on macOS.

# Repro

```
PAGER=date ugrep --pager xyz /etc/services
```

# Expected Result

`ugrep` should have started `date`, since that's what the user's `$PAGER` variable is set to.

# Current Result

`less` starts.

# Workaround

```
PAGER=date ugrep --pager=date a /etc/services
```

# Notes

I have `PAGER`set to `moar`. This makes both `git` and `man` default to `moar`. I was surprised `ugrep` didn't work the same way.

**Comment by genivia-inc** [comment]
Thanks for the feedback.

The `$PAGER` env var is not used by ugrep with option `--pager`. It is also not mentioned the ugrep man page and README, since it mentions `less -R` as the default. The `$PAGER` var is used with option `-Q` when pressing CTRL-Y to view a file.

The question is, should ugrep use `$PAGER` as a default pager for option `--pager`?

**Comment by genivia-inc** [comment]
Since colors should be visible in a pager, the only way we can use `$PAGER` correctly is to let ugrep check if the specified `$PAGER` is `more` or `less` and then add option `-R` if that is the case. If we don't use `-R` the output will be garbled.

If `$PAGER` is not `more` or `less`, then color output will be disabled to send the results to whatever `$PAGER` might be, such as `cat` for example.

Perhaps that is reasonable to do. Even though GNU grep for example has no pager to compare to, to see what it does in these cases.

**Comment by genivia-inc** [comment]
Since most users use `ug` for interactive searching rather than the `ugrep` command (which is basically the same, but `ug` has additional options enabled), they add their favorite long options to the .ugrep file. For example, to define a pager:
~~~
pager=less -R
~~~
Won't that work for you? Is there are compelling reason to obey `$PAGER`? GNU grep doesn't use it.

**Comment by genivia-inc** [comment]
OK. Implemented. The update will be released with the next release cycle in 3 weeks or about, so will keep this open until then.

Thanks for the suggestion!

**Comment by genivia-inc** [comment]
It looks like `moar` does not support `+linenum` to start listing from `linenum` like `more` and `less` do. Perhaps a suggestion to add this feature. See #296 for the reason why.

**Comment by walles** [comment]
> It looks like `moar` does not support `+linenum` to start listing from `linenum` like `more` and `less` do. Perhaps a suggestion to add this feature. See #296 for the reason why.

Do you think you could open a feature request for that?

https://github.com/walles/moar/issues

Would make it easier for me to track.

**Comment by genivia-inc** [comment]
Just to let you know: I've added `moar` to the internal checks of ugrep 4.3 when in query mode `-Q`, so `moar +linenum` works when `PAGER` is moar to view a file with CTRL-Y.
