### ISSUE TITLE
--ignore-files doesn't work?

### ISSUE THREAD

**Issue by stephentalley** [Genivia/ugrep#295]
I'm certain I'm doing something wrong, but I can't seem to get --ignore-files to actually ignore anything.
With this test:
```
#!/bin/bash

dir=/tmp/test
ignorefile=/tmp/myignore

rm -rf "$dir"
mkdir -p "$dir"/{good,bad}
mkdir -p "$dir"/subdir/{good,bad}
echo bad/ > "$ignorefile"
echo bad >> "$ignorefile"
echo hello > "$dir"/hello.txt
echo hello > "$dir"/bad/hello.txt
echo hello > "$dir"/good/hello.txt
echo hello > "$dir"/subdir/hello.txt
echo hello > "$dir"/subdir/bad/hello.txt
echo hello > "$dir"/subdir/good/hello.txt
cd "$dir"
ugrep -lr --ignore-files="$ignorefile" hello .
```
…I would expect to see:
```
hello.txt
subdir/hello.txt
good/hello.txt
subdir/good/hello.txt
```
…but instead I see:
```
hello.txt
subdir/bad/hello.txt
subdir/hello.txt
good/hello.txt
subdir/good/hello.txt
bad/hello.txt
```

Apologies if I'm missing something basic, but why are results under the bad directories shown?

Also, what is the difference between --exclude-from and --ignore-files? I cannot see any difference from the reading of the man page.
```
% ugrep -V
ugrep 4.0.5 x86_64-pc-linux-gnu +avx2 +pcre2jit +zlib +bzip2 +lzma +lz4 +zstd
License BSD-3-Clause: <https://opensource.org/licenses/BSD-3-Clause>
Written by Robert van Engelen and others: <https://github.com/Genivia/ugrep>
```

**Comment by genivia-inc** [comment]
See #118.

This will be updated in the upcoming v4.1.0 release available soon (I'm on a short break).

You're right in observing the difference. The difference is that the GNU grep `--exclude-from=FILE` rules differ from gitignore rules, where the latter ignores both files AND directories for each glob specified. I wish git hadn't decided to be different that way, considering it's a bad design IMHO as GNU grep get's it. In both GNU grep and gitignore, the glob `foo/` ignores directories specifically. So when the glob `foo` ignores both files and directories with gitignore rules, then sometimes you need a `!foo/` to undo this ignore for directories. So ugly, sigh...

Anyway, we all got so much used to this. So the upcoming v4.1.0 release will adopt the gitignore rules as they are and I will stop "ranting" about it. It's only a single line of code to change in ugrep.cpp.

**Comment by stephentalley** [comment]
Thanks for the clarification of the differences.

However, the core issue remains: I cannot seem to add **any** line to $ignorefile to make it actually ignore the bad directories. None of these lines work, either together or individually:

```
bad
bad/
bad*
bad*/
```
What am I missing?

**Comment by genivia-inc** [comment]
Perhaps because the ignore file specified is not a local file that is found in recursive searches? `ignorefile=/tmp/myignore`.

If you want to do that, then just use `--exclude-from=/tmp/myignore` which is a GNU grep option that is extended by ugrep to support gitignore-style globs. The globs for directories requires a terminating `/`, which git does not need.

**Comment by stephentalley** [comment]
Hmm, is there a reason for disregarding ignore-files when they're not in the search domain?

I was hoping ugrep behaved like fd, which allows **any** gitignore-style file to be specified with --ignore-file=_/any/path/to/gitignore/file_, and always abides by it.

It seems like if a user is explicitly calling ugrep with --ignore-file=_/any/path/to/gitignore/file_, then that file should be abided by regardless of whether it is encountered as part of the search.

I could maybe see treating non-absolute ignore files (e.g. --ignore-file=.myignores) the way you suggest. But absolute paths, IMO, should **always** be considered.

So to summarize:
|Option                          |Meaning                                                                    |
|--------------------------------|---------------------------------------------------------------------------|
|--ignore-file=_file_            |Use ignore patterns in _file_ whenever _file_ is encountered when searching|
|--ignore-file=_/path/to/file_   |Use ignore patterns in _/path/to/file_ always                              |

What do you think?

BTW, in my use case, the ignore files I want to use are also used by other tools (namely git and fd), and so converting them to --exclude-from format is not an option.

**Comment by genivia-inc** [comment]
The `--ignore-files` option serves two purposes: firstly to respect .gitignore in recursive searches and secondly to allow alternatives, such as `--ignore-files=.ignore` to respect .ignore in recursive searches. That's why option `--gitignore-files` is plural: any and all .gitignore files found in recursive searches will be respected.

> I was hoping ugrep behaved like fd, which allows any gitignore-style file to be specified with --ignore-file=/any/path/to/gitignore/file, and always abides by it.

Hmm, I can't seem to find this feature mentioned anywhere in the fd README: https://github.com/sharkdp/fd

On a related note, [git-grep](https://git-scm.com/docs/git-grep) doesn't have an option to change the .gitignore file name and has no way of specifying a globally-applicable .gitignore as you suggest.

**Comment by stephentalley** [comment]
> The `--ignore-files` option serves two purposes: firstly to respect .gitignore in recursive searches and secondly to allow alternatives, such as `--ignore-files=.ignore` to respect .ignore in recursive searches. That's why option `--ignore-files` is plural: any and all .gitignore files found in recursive searches will be respected.

So I think my suggestion above still respects that goal.

> > I was hoping ugrep behaved like fd, which allows any gitignore-style file to be specified with --ignore-file=/any/path/to/gitignore/file, and always abides by it.
> 
> Hmm, I can't seem to find this feature mentioned anywhere in the fd README: https://github.com/sharkdp/fd

The man page is probably a better resource:

    --ignore-file path
        Add  a  custom  ignore-file in '.gitignore' format.

> On a related note, [git-grep](https://git-scm.com/docs/git-grep) doesn't have an option to change the .gitignore file name and has no way of specifying a globally-applicable .gitignore as you suggest.

I don't use git-grep, but I do use multiple .gitignore-style files in various git commands. git doesn't have anything quit as flexible as --ignore-files, but it does allow multiple files to be used simultaneously via various paths and the core.excludesFile option (see gitignore(5)).

As a result, I have several ignore files that I can cherry-pick for various tools, occasions, and repos. It would be nice to integrate ugrep into that workflow.

**Comment by genivia-inc** [comment]
~~~
--ignore-file path
    Add  a  custom  ignore-file in '.gitignore' format.
~~~
This option has a very different meaning that is more closely aligned with the grep notion of `--exclude-from=FILE`, that is, a globally-defined set of exclusions you can pick and choose to use, similar to GNU grep's purpose to introduce `--exclude-from`. In fact, you can still use `--exclude-from` perfectly for your use case and purpose, but add `/` to directories to exclude. This works without issues with any other tool that supports gitignore-style syntax. So I really don't see a use case that isn't already supported and requires a new option. GNU grep exclusions are designed for this use case. Not the .gitignore files, which are *locally-associated* with git projects and (sub)directories therein.

**Comment by stephentalley** [comment]
But --exclude-from uses a different format than .gitignore, which would preclude me from using my existing .gitignore-style files without converting them.

To clarify, I'm not suggesting you add a new option. I was suggesting that --ignore-files could be modified to suit both the use case you suggest (specify the name of a gitignore-style file to consider when encountered during a search), and the one I'd like to use (always consider regardless of location).

fd's --ignore-file option does exactly what I'd hope ugrep would do. Note that it does not require the specified file to exist in the search domain, or even within a git repo. It can exist anywhere and will still be considered.

**Comment by genivia-inc** [comment]
> But --exclude-from uses a different format than .gitignore, which would preclude me from using my existing .gitignore-style files without converting them.

No, it does not use a different syntax with ugrep.

.gitignore rules syntax to exclude both `foo` files and directories:
~~~
foo
~~~
.gitignore rules and exclude-from globs syntax to exclude both `foo` files and directories:
~~~
foo
foo/
~~~
Because this is standard syntax, this works with fd too. Otherwise, fd is not compliant.

For globs that specify files to exclude you just need to keep the glob as it is. There is no difference. Also the `!` syntax works with ugrep in exclude-from files and .gitignore.

I'm reluctant to update `--ignore-files` to behave in two difference ways. It will be confusing to read the help pages if there are two behaviors. Only a new option avoids this, but I don't see the point since what you want aligns with the  exclude-from mechanism using ugrep's gitignore-style syntax and by adding `/` in some cases.

Adding a `/` is nicer too, because consider the case where you want to exclude files but not exclude directories:

.gitignore rules syntax to exclude `foo` files but not directories:
~~~
foo
!foo/
~~~
exclude-from globs syntax to exclude `foo` files but not directories:
~~~
foo
~~~
Clean and simple.
