### ISSUE TITLE
[FR] Add option not to confirm for exiting (exit immediately by pressing ESC, C-c, etc)

### ISSUE THREAD

**Issue by NightMachinary** [Genivia/ugrep#30]

**Comment by genivia-inc** [comment]
You mean with CTRL-Q? This exits immediately. A key press combo is "safer" than a single key press like ESC. CTRL-C is obvious, but for now it pulls up the help page so that users are informed of all possible key combos. Perhaps CTRL-C will be redesigned to replace CTRL-Q in the future.

**Comment by NightMachinary** [comment]
@genivia-inc I know the current design is pretty good, but I still think an option not to confirm `ESC` will be nice. (Particularly since even a mistaken exit doesn't matter much at all.) Perhaps a long-term, efficient solution is to allow a config to bind custom keys to commands (like `fzf` does), and just add a `exit-no-confirm` command.

**Comment by genivia-inc** [comment]
Yes, I didn't want to appear to ignore the suggested option, something like `--[no-]confirm`. This also got me rethinking the role of CTRL-C, which should terminate the program without further producing any output. By comparison, CTRL-Q does produce output. So when `ugrep -Q` is used in a pipeline CTRL-C terminates the pipeline too, whereas CTRL-Q exits and continues the pipeline.

**Comment by genivia-inc** [comment]
ugrep v2.1.2 supports CTRL-\ to terminate the process (`SIGTERM`) and CTRL-C behaves like ESC.

If the user pressed CTRL-C instead of ALT-C (turn count on/off), e.g. by accident, then the program does not terminate immediately. Previously the help page would pop up. I think it is best for the UI design to prevent accidental keyboard input to cause potential mayhem. CTRL-\ isn't easy to type accidentally, so that's OK.

**Comment by NightMachinary** [comment]
@genivia-inc How about making a double-escape also act as exit? No one accidentally double-presses ESC, and it's still easy to use. I personally like to keep my keyboard hotkeys one-keyed; Combinations like C-c or C-\ are hard to type.
