### ISSUE TITLE
[FR] ugrep+: Is it possible to do ocr search with tesseract?

### ISSUE THREAD

**Issue by IlIllIl** [Genivia/ugrep#304]

**Comment by genivia-inc** [comment]
Any CLI tool can be used as a filter with ugrep provided that the tool sends the text results to standard output. See [the `--filter` option](https://github.com/Genivia/ugrep#using-filter-utilities-to-search-documents-with---filter).

Since [Tesseract](https://en.wikipedia.org/wiki/Tesseract_(software)) has a CLI, it should be possible to use it as a filter, provided it can send the text to standard output. I haven't tried it.
