### ISSUE TITLE
[Question] Why have separate binaries for ug and ugrep if they are the same?

### ISSUE THREAD

**Issue by daniejstriata** [Genivia/ugrep#315]
I was wondering why there are 2 binaries when I compile the source in the bin directory. Can `ug` be an alias of `ugrep`?

**Comment by genivia-inc** [comment]
The logic internally checks for `ug` program name, but that does not appear to work with some command shells unfortunately. I had symlinked `ug` to `ugrep` in earlier versions, but found out with feedback that is not working with some command shells installed on Linux/BSD OS.

It's not problem to symlink if symlink execution by a shell uses the symlinked name, not the target name to symlink points to.

Hard links might be an option, but the symlink experience has polluted my mind not to trust links.

**Comment by daniejstriata** [comment]
Thanks for taking your time in explaining this.

**Comment by daniejstriata** [comment]
@genivia-inc Would it not be more efficient if the TUI mode could be accessed with a command line switch instead of creating copies of the same binary? Then if you want to use the TUI you can call it and therefore setup an alias?

**Comment by genivia-inc** [comment]
Both `ug` and `ugrep` commands support the TUI and should be. But the `ug` command specifically enables `--pretty`. Making `ug` an alias is possible, but not something that can be done automatically when installed (without modifying one or more sh dot files) and not something that would work on Windows, for example.

**Comment by daniejstriata** [comment]
Thanks again!

**Comment by yg-i** [comment]
@genivia-inc I have installed ugrep via winget just now, and it seems that only (a symlink to) ugrep.exe can be found in `C:\Users\{username}\AppData\Local\Microsoft\WinGet\Links`. Does this mean that I should manually create three copies of ugrep.exe named ug.exe, ug+.exe, ugrep+.exe in the same folder, in order to take advantage of the full range of available commands?

**Comment by genivia-inc** [comment]
No, because it should work with your installation. Try the `ug -l -2 ""` command and see if `--pretty` output is produced with a directory tree format `--tree` for option `-l` (ell, not 1) up to `-2` directories deep.

Note: on my end, I cannot assume that symlinks work on all platforms and with all shells. It won't work with Linux+bash for example, which doesn't return `ug` for `argv[0]` as should be, but instead returns `ugrep` when `ug` is installed as a symlink to `ugrep` (see my previous comments).

**Comment by yg-i** [comment]
Thanks for the response. It does seem that `ug -l -2 ""` is producing exactly the format you described:
![image](https://github.com/Genivia/ugrep/assets/148152939/2d43cf93-ccf4-4380-962a-0520978c895d)


For what it's worth, changing ug to ug+, ugrep, or ugrep+ all produce the following output:
![image](https://github.com/Genivia/ugrep/assets/148152939/0e712bb2-da2e-43e2-b3b8-27d9342f0316)
![image](https://github.com/Genivia/ugrep/assets/148152939/1b64c135-50e8-43ec-bf69-3aad415e86f9)
![image](https://github.com/Genivia/ugrep/assets/148152939/f6a0d1e0-6d38-47d9-a090-817c441e3b19)



No, because it should work with your installation. Try the ug -l -2 "" command and see if --pretty output is produced with a directory tree format --tree for option -l (ell, not 1) up to -2 directories deep.

> Note: on my end, I cannot assume that symlinks work on all platforms and with all shells. It won't work with Linux+bash for example, which doesn't return ug for argv[0] as should be, but instead returns ugrep when ug is installed as a symlink to ugrep (see my previous comments).

Understood. The symlink in my WinGet/Links folder appears to have been created by WinGet itself, and it's linking to `C:\Users\{username}\AppData\Local\Microsoft\WinGet\Packages\Genivia.ugrep_Microsoft.Winget.Source_8wekyb3d8bbwe\ugrep.exe`

**Comment by genivia-inc** [comment]
It looks like `ug+` is implemented differently with the Winget installer. I have implemented `ug+` as a script to execute `ug` so it loads the config file. But your `ug+` output does not show a directory tree as expected (like `ug`).

Related to this is the #301 PR.
