### ISSUE TITLE
[FR] Don't disable multi-line when using context

### ISSUE THREAD

**Issue by NightMachinary** [Genivia/ugrep#32]
`ugrep` can just show the `x`-many context lines after the last line of the match and before the first line of the match.

**Comment by genivia-inc** [comment]
Thanks for the feedback. Multiline matching with context options that are line-based is a problem that is not trivial to address to make it work under all circumstances, while correctly replicating GNU/BSD grep output. I worry that it may significantly impact performance as the buffer window over the file (for efficient matching) must be quite a bit larger to cover extreme cases and there may be situations when the context could actually drop off erroneously. For example, this problem is in fact exactly what pcre2grep warns about:

> The  block  of  memory that is actually used is three times the "buffer
>        size", to allow for buffering "before" and "after" lines. If the buffer
>        size  is too small, fewer than requested "before" and "after" lines may
>        be output.

I don't want any surprise errors or truncated output to occur. I made sure that `ugrep` does not error out when files cause problems like this. In other words, there are no hidden limits.

I will consider this a long-term enhancement.

**Comment by genivia-inc** [comment]
I have a development version of ugrep prepared that doesn't disable multiline matching when using context option (`-A`, `-B`, `-C`, and `-y`). Because this changes some of the critical internals, we will be spending more time to test this out thoroughly.

Some thought about this. If memory mapping is disabled either explicitly or if the file is too large for mmap (currently max 1GB by default), the buffering strategy is to hold the before and after context lines in the buffer's window while searching a file. The buffer will be increased on demand to fit the context, potentially without limits or until the `realloc` syscall fails (e.g. when allocating more than 2GB on some systems). In that case we must truncate the amount of context in order to continue searching without interruption. Only if the context gets very large with a lot of very long lines (exceeding 2GB or more for `realloc` to fail), then we would run into context truncation.

**Comment by genivia-inc** [comment]
Progress update.

After careful consideration, I do not want to introduce any artificial limits on the size and number context lines (`-A`, `-B`, `-C`, `-y` or inverted lines matched (`-v`).

Therefore, I had to abandon my first attempt to support multiline matches when context option `-A`, `-B`, `-C`, or `-y` is used or inverted match option `-v`.

Let me explain that the files that are searched are not stored in their entirety in memory, except when meeting the size for mmap (memory mapped files) optimizations. Instead, a sliding window is used. This window cannot grow beyond a certain size and is certainly limited to 2GB as I pointed out earlier. That is the reason why other grep tools like pcregrep cannot show the context correctly when the context is too large for their internal buffers to handle.

My new approach is to register an event handler functor with the RE/flex [`AbstractMatcher` class](https://www.genivia.com/doc/reflex/html/classreflex_1_1_abstract_matcher.html), which I had to implement in that class as an updated (the official RE/flex update is forthcoming). This event handler is invoked when the buffer shifts, i.e. drops contents that are normally no longer searched. This content is then captured by the event handler and displayed as context or as inverted matches. The approach sounds easy, but there are several edge cases that makes this effort a bit more complicated (e.g. handling `-K`, `-m`, `--max-files` correctly), which calls for thorough testing to ensure all cases are covered correctly.

What are the benefits?
1. no artificial limits on the size of the context or number of inverted lines displayed and thus no truncated output or error messages;
2. the performance is very good, because the matcher is not interrupted and no partial matching is needed to shift the buffer and display context, which would be more expensive, i.e. temporarily store the matcher state (partial matching) in order to extract the buffer contents to display context, like pcregrep.

Because I started over, it took me more time than I anticipated. But it is worth the extra effort to do this right (hence our company motto _"relentlessly pursuing perfection"_).

I have a prototype version with updated options `-y` and `-v` (and `-yv`) implemented and thoroughly tested. Next up to address are `-A` and `-B` (`-C` sets both `-A` and `-B`). The logic and event handlers are similar to `-y`. I'm also improving the speed of matching with these options.

Once that's done and tested, I will release an update.

**Comment by genivia-inc** [comment]
The v.2.3.0 update is ready and tested. Our core search engine consisting of the RE/flex AbstractMatcher class for matching with the RE/flex matcher, RE/flex fuzzy matcher, and the PCRE2-based matcher, had to be extended to include buffer shift events to allow for an efficient streaming implementation of the `-A`, `-B`, `-C`, and `-y` options. This streaming implementation with the new event handlers has no limits on file size and memory usage, unlike some other grep tools that support multi-line matching (e.g. pcregrep).

To achieve this, four new event handlers were added to efficiently handle `-v`, `-y` (and `-vy`), `-C` (and `-A`/`-B`), and `-vC` (and `-vA`/`-vB`), respectively. These options may be combined with any other options, such as `-W` and `-X` to display binary matches in hexadecimal, including mixed text and binary matches with `-W`. The more challenging part was to support `-vWC` (inverted context matches with hexadecimal output for binary context matches). New test cases for these combinations were added to make sure ugrep performs are expected.
