### ISSUE TITLE
[DISCUSSION] Refactoring the interactive UI to work as a frontend 

### ISSUE THREAD

**Issue by NightMachinary** [Genivia/ugrep#33]
Refactoring the interactive UI to work as a frontend that can use any search tool (`ripgrep`, `ucg`, `ag`, `fzf` in noninteractive mode, ...) seems like a good idea to me, as I don't know of any such interactive tool currently available on Github. (Seems to me most people use vim/emacs frontends for this.)

It can potentially bring more exposure to this project.

**Comment by genivia-inc** [comment]
Interesting idea. We could start a new project (e.g. fork from ugrep perhaps). There will be a difference, because `ugrep -Q` uses threads for efficiency (i.e. to directly control the concurrent search engine) instead of forking a search engine.

**Comment by genivia-inc** [comment]
Since the participation in this discussion is low, I will close this discussion until further notice. I may have time to revisit this later. Please note that the UI is also still evolving as we learn more from practical use cases and feedback from users. If someone likes to take this up as a new project to create a generic front-end, then I am happy to help of course.
