### ISSUE TITLE
Cannot use unescaped brace in regex

### ISSUE THREAD

**Issue by mohd-akram** [Genivia/ugrep#340]
The parsing of braces is opportunistic in grep and other regular expression engines (I tried Node.js and Python). If it cannot parse a count, it parses it as a literal:

```shell
$ echo { | grep -E {
{
$ echo { | ugrep -E {
ugrep: error: error at position 4
(?m){
    \___empty expression

$ echo a{b} | grep -E a{b}
a{b}
$ echo a{b} | ugrep -E a{b}
ugrep: error: error at position 6
(?m)a{b}
      \___invalid repeat
```

**Comment by mohd-akram** [comment]
It turns out these regular expressions result in undefined behavior according to POSIX:

> *+?{
The \<asterisk>, \<plus-sign>, \<question-mark>, and \<left-brace> shall be special except when used in a bracket expression (see [RE Bracket Expression](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09_03_05)). Any of the following uses produce undefined results:
> - If these characters appear first in an ERE, or immediately following an unescaped \<vertical-line>, \<circumflex>, \<dollar-sign>, or \<left-parenthesis>
> - If a \<left-brace> is not part of a valid interval expression (see [EREs Matching Multiple Characters](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09_04_06))

It should be noted that in JavaScript's unicode regular expression mode, these regular expressions are also not supported.

**Comment by genivia-inc** [comment]
Thank you for your feedback. Indeed, some forms have undefined behavior. I try to allow a few more special cases in "GNU grep" mode, i.e. when ugrep is renamed to grep (or fgrep, egrep) which auto-enables some options to be a bit more permissive with regex forms. I still like ugrep to produce an error message rather than accept undefined behavior and then decide what to make of it.
