### ISSUE TITLE
drop in replacement didn't work?

### ISSUE THREAD

**Issue by rdp** [Genivia/ugrep#347]
```
$ grep "libstdc++.dll.a" . -r
# works
$ ugrep "libstdc++.dll.a" . -r
ugrep: error: error in regex at position 12
(?m)libstdc++.dll.a
            \___invalid quantifier
```

Maybe expected? Thanks :)

**Comment by genivia-inc** [comment]
The drop-in replacement works if you rename ugrep to grep, egrep and fgrep. Then it obeys the `ugrep -G` option to behave like grep. Otherwise, it is similar to egrep. You can't expect ugrep as a command to be the same as grep. It is a different command. Rename or (sys)link ugrep works.

There are comments about this in the README.

**Comment by genivia-inc** [comment]
I've updated the README to avoid confusion about the drop-in comment, with a link to the section in the README that describes the drop-in steps to take.

When ugrep is installed, we should not replace grep, egrep and fgrep automatically. That's not acceptable to users (and would likely be rejected by package managers, I would). Instead, users should rename/copy ugrep or symlink ugrep or create aliases as he/she wishes.

**Comment by rdp** [comment]
That does satisfy my initial confusion, and will hopefully help followers, thank you (though I'll admit it looks a bit daunting in the README, maybe could be a bit more terse and just link to it?), thanks for your help and attention! :)
