### ISSUE TITLE
support named match

### ISSUE THREAD

**Issue by jonassmedegaard** [Genivia/ugrep#35]
would be really nice if ugrep supported named matching.

My use-case is scanning for copyright and licensing information.  I have [a large collection of patterns](https://metacpan.org/pod/Regexp::Pattern::License) and would like to scan for them all at once, and be told which one matched.

More fine-grained, I would also like to be able to detect if certain subpattern was found within a larger pattern.  A Concrete example is that the GPL-2 license has 6 variants and the first [had a typo](https://github.com/pombredanne/gpl-history/commit/a2abba1) - would be nice if I was able to do a single scan for all licenses, and additionally be told if a file detected as GPL-2 was a "flawed" on (there are other types of flaws, e.g. outdated postal address to Free Software Foundation, or a typo for newest postal address of "Franklin Steet" with a missing "r").

**Comment by genivia-inc** [comment]
Perhaps the `--format` option largely does what you want with fields `%O` (output matching line) or `%o` (output match only) and `%g` (group capture index of each match). The group capture index without option `-P` is the pattern number, e.g. `foo|bar` has patterns 1 and 2. You can also use `-e foo` and `-e bar`. With option `-P` the group captures should be explicitly specified, e.g. `(foo)|(bar)`. The same principle applies to patterns from a file, i.e `-f` and strings from a file, i.e. `-F` with `-f`. Each pattern from a file is put in an alternation.

So try `--format='%g:%O%~'` with a set of patterns and see what happens. If necessary, you can post-process the output with another `ugrep` or through `sed` or a script to do something with the pattern numbers and corresponding matching lines.

**Comment by jonassmedegaard** [comment]
Quoting Robert van Engelen (2020-05-20 04:48:41)
> Perhaps the `--format` option largely does what you want with fields `%O` (output matching line) or `%o` (output match only) and `%g` (group capture index of each match). The group capture index without option `-P` is the pattern number, e.g. `foo|bar` has patterns 1 and 2. You can also use `-e foo` and `-e bar`. With option `-P` the group captures should be explicitly specified, e.g. `(foo)|(bar)`. The same principle applies to patterns from a file, i.e `-f` and strings from a file, i.e. `-F` with `-f`. Each pattern from a file is put in an alternation.
> 
> So try `--format='%g:%O%~'` with a set of patterns and see what happens. If necessary, you can post-process the output with another `ugrep` or through `sed` or a script to do something with the pattern numbers and corresponding matching lines.

Yes, with numbered group patterns I can get a result describable as 
"file1 matched pattern #27, file3 matched patterns #29 and #30".

I could then write a wrapper to a) parse the input patterns on my own, 
noting down how they are ordered, and b) mangle the output replacing 
matched numbers with names.

What I am requesting with this issue is to have ugrep provide directly 
meaningful output describable as "file1 matched GPL-2, file3 matched 
GPL-2 and FSF-TYPO".

To use an example similar to yours, I want to be able to do this:

```
ugrep -r -nkw 'main' -f c/strings -f c/comments --named myproject
```

and the output tells for each match of 'main' if it was found in strings 
or comments.


I have no clue how complex it would be to implement the details, but 
propose for for explicit named patterns e.g. on command-line to use same 
syntax as in PCRE:

  '(?P<GPL-2>You can apply it to (the|(??<FSF-TYPO>he) GNU (Library|Lesser))'

Predefined patterns could (as a speed optimization) have their named 
patterns "demoted" to either numbered patterns or non-capturing patterns 
when loaded, depending on options set.

**Comment by genivia-inc** [comment]
I sure like named patterns in PCRE.

I perused the [PCRE specification](https://www.pcre.org/current/doc/html/) to see if it is possible to extract the name of a named pattern that matches a (sub)pattern. There does not appear to be an API function that gives us the name or names of matched sub-patterns as far as I can tell. You can get a sub pattern by name with [pcre2_substring_get_byname](https://www.pcre.org/current/doc/html/pcre2_substring_get_byname.html) and map names to capture indices with [pcre2_substring_nametable_scan](https://www.pcre.org/current/doc/html/pcre2_substring_nametable_scan.html), but not vice versa. As far as I can tell all API functions require a name up front. Sure, named patterns are embedded in a regex, so we could extract them with some logic in order to find if a name has a matching subpattern, but that seems clumsy, appears costly when matching, and is perhaps even error prone when scraping these from strings. Not saying it is not possible, but some experimentation will tell.

However, I have been thinking that there is a relatively simple approach that should work well with `-P` perl regex and also with the default RE/flex regex by extending the `%g` format field with an optional bracket list of names.

Allow me to explain.

Consider `--format='%[other|GPL|BSD]g:%F%N%O%~'` which has the field `%[other|GPL|BSD]g` with a list of names/text separated by bars that will be displayed corresponding to the group capture index. The default group capture index is 1, so that's why `other` is placed at the front of the list of specific names. Field `%F` displays the file name if filenames are output, `%N` displays the line number if `-n` is used, and `%O` displays the matching line.

With this addition to `--format` fields, it's not hard to write a regex pattern that produces the desired output with names instead of anonymous numbers. Just use a group capture for each license pattern. If multiple captures must be used for the same license, then the extra corresponding entries in the bracket list should appear as well.

Furthermore, If option `-f` is used to ignore comments and strings, then that won't matter at all. But please note that zapping comments and strings only works without perl matching with option `-P`, using the default RE/flex fast DFA-based matcher. On the other hand, option `-P` allows richer regex patterns if you need them, but you will be giving up some of the performance and also negative patterns won't work.

As a bonus, this approach can be used to color output by matching sub pattern. For example, in bash we can use `$'...'` to embed control characters like so to produce three different colors:

    --format=$'%[\033[31m|\033[32m|\033[33m]g%O\033[m%~'

This colorization can be combined with the license names GPL, BSD, MIT, etc. to make it stand out when you are looking for "bad ones".

I tried it out and this works like a charm. It is worth a try and can be added to ugrep right now without us having to fight with PCRE functions and dealing with the complexity of extracting the names of matching sub-patterns.

**Comment by jonassmedegaard** [comment]
If I understand you correctly, then again you are exploring what is possible with a smaller well-defined challenge. it is quite nice to be able to grep more fine-grained for specific licenses, but my main use-case is to a) not know ahead which licenses I am looking for and b) scan for hundreds of patterns.

I am breaking it inot pieces that I think is generally usable on their ow. but I envision the ideal end goal to be ugrep supporting something like this:

  ugrep -f licenses myproject

which expands to

  ugrep -f licenses/DEFAULT myproject

whichs (through some new syntax in that file) expands to

  ugrep -f licenses/{BSD,CC,GNU,MISC,MIT} --filter={RICHTEXT,METADATA} --file-magic-label={RICHTEXT,METADATA}

which (consulting meta hints in {licenses,default}/{RICHTEXT,METADATA}) expands to

  ugrep -f licenses/{bsd_0_clause,bsd_1_clause,bsd_2_clause,bsd_3_clause,bsd_4_clause,...,cc_by_sa_3_5,cc_by_sa_4,...,lgpl_3,lgpl_3_only,lgpl_3_or_newer,...,public_domain,public_domain_cc0,...,wtfpl_1,wtfpl_2,...} --file-magic-label={PDF,BITMAP_IMAGE,OPENDOCUMENT,...,RAWBINARY} --filter=png,t1,...,pdf,docx,...:'exiftool %' --filter=pdf,doc,docx,oow,low,...:'anytotxt %' --filter=raw:'strings %' myproject

(yes, some files are filtered twice to grep _both_ content and metadata).

I hope you find the idea interesting.

I recognize ugrep being a general purpose tool, and I don't mean to try distort that. On the contrary, I do think that the license scanning case is just one out of several that could benefit from this kind of clustered patterns.  Another use case I am aware of is scanning logfiles for "interesting" activities, where "interesting" can be categorized and refined, and again you may not know ahead what you are looking for (but quite useful to be able to ne able to narrow down to look closer).

Debian has a projecct "logcheck" where some patterns are maintained within the project but also each package in Debian can add additional patterns specific to that tool.  The logcheck project has lost some attention in recent years, one reason being that it is relatively slow to scan - and ugrep could help revitalize that project.

**Comment by genivia-inc** [comment]
Version v2.1.3 supports `%[name1|name2|....]g` expansion in `--format` to names corresponding to sub-patterns (w/o option `-P`) or group captures (with option `-P`).

This is the most general way I can think of to support named matches that works for `-P` and without.

Each set of patterns may require its own `--format` with `%g` fields, but on the other hand customizing the `--format` output for different tasks and patterns makes sense IMHO.

Frankly, I don't know if there is a reliable way to extract named patterns from PCRE regex that could supplant this feature with a more convenient alternative. I can't find a PCRE function to retrieve names. So this is something to experiment with and see if there aren't any unforeseen issues to scrape the names from regex patterns. Potential issues could be the use of different syntax for named patterns like `(?P<name>X)` versus `(?<name>X)` versus `(?'name'X)` and the fact that duplicate named patterns appear to give different results for different regex libraries.

**Comment by genivia-inc** [comment]
> Debian has a projecct "logcheck" where some patterns are maintained within the project but also each package in Debian can add additional patterns specific to that tool.  The logcheck project has lost some attention in recent years, one reason being that it is relatively slow to scan - and ugrep could help revitalize that project.

It is an interesting project. It can definitely improved with a tool like ugrep. I wonder though if search speed is the only issue here. It could be lack of accuracy if the patterns are not maintained and tested on a regular basis.

> What I am requesting with this issue is to have ugrep provide directly
> meaningful output describable as "file1 matched GPL-2, file3 matched
> GPL-2 and FSF-TYPO".

I'm not convinced this output (or very similar) can be generated with a grep tool without some programmatic work wrapped around it to produce such detailed sentences. Another issue is the use of multiple sub-pattern group matches ("file3 matched GPL-2 and FSF-TYPO"). That is something that can be relatively easily implemented in C/C++ with PCRE2 to handle the patterns like the one you suggested:

    (?P<GPL-2>You can apply it to (the|(??<FSF-TYPO>he) GNU (Library|Lesser))

But even with PCRE2, there does not appear to be a robust way as far as I can tell to extract the names of named patterns. Granted, with some coding you could iterate through the names (assuming you have them!!) to get the group capture numbers to check for sub-pattern matches.

IMHO such a specific use of named pattern extraction seems very specific and not a good use case for a grep tool if you want to stick to the regex above without modification. Also pcregrep won't work. The numbered `-o` option can output matching sub-patterns, but there is no way to produce these sentences unless some serious script wrapping is done around pcregrep to analyze the sub-pattern matches and convert them to sentences. That requires some serious scripting with hardcoded logic probably.

There are other ways to get almost exactly what you want, if license patterns are more organized without relying on nested (named) sub-pattern matches.

Consider for example the two patterns:

    (You can apply it to the GNU (?:Library|Lesser))|(You can apply it to he GNU (?:Library|Lesser))

This enumerates the two GPL-2 and GPL2-TYPO patterns. Let's put these two in a file, say `licenses`:

    (You can apply it to the GNU (?:Library|Lesser))
    (You can apply it to he GNU (?:Library|Lesser))

Now we can run ugrep as follows:

    ugrep -l -f licenses --format='%f matches %[GPL-2|GPL-2-TYPO]g%~'

to produce:

    file1 matches GPL-2
    file2 matches GPL-2-TYPO

That's almost exactly what we want.

Please note that `-l` (dash ell) produces the first match found only, so don't use `-l` if multiple matches are desired.

A list of patterns and a corresponding list of names like "GPL-2" is all we need. This can be automated with a script that produces the list of patterns and the list of names from an associative array of names to patterns.

**Comment by jonassmedegaard** [comment]
Quoting Robert van Engelen (2020-05-23 22:57:28)
> > Debian has a projecct "logcheck" where some patterns are maintained within the project but also each package in Debian can add additional patterns specific to that tool.  The logcheck project has lost some attention in recent years, one reason being that it is relatively slow to scan - and ugrep could help revitalize that project.
> 
> It is an interesting project. It can definitely improved with a tool like ugrep. I wonder though if search speed is the only issue here. It could be lack of accuracy if the patterns are not maintained and tested on a regular basis.

Yes, there are indeed other challenges than grep speed to keep that 
project alive (I tried to hint at that by writing "one reason being" 
above.


> > What I am requesting with this issue is to have ugrep provide directly
> > meaningful output describable as "file1 matched GPL-2, file3 matched
> > GPL-2 and FSF-TYPO".
> 
> I'm not convinced this output (or very similar) can be generated with a grep tool

I did not mean to say that I expect ugrep to _verbatim_ emit sentences 
as above, only some output humanly meaningful like it (I tried to hint 
at that by writing "describable as" above.


> Another issue is the use of multiple sub-pattern group matches ("file3 matched GPL-2 and FSF-TYPO"). That is something that can be relatively easily implemented in C/C++ with PCRE2 to handle the patterns like the one you suggested:
> 
>     (?P<GPL-2>You can apply it to (the|(??<FSF-TYPO>he) GNU (Library|Lesser))
> 
> But even with PCRE2, there does not appear to be a robust way as far as I can tell to extract the names of named patterns. Granted, with some coding you could iterate through the names (assuming you have them!!) to get the group capture numbers to check for sub-pattern matches.
> 
> IMHO such a specific use of named pattern extraction seems very specific and not a good use case for a grep tool if you want to stick to the regex above without modification. Also pcregrep won't work. The numbered `-o` option can output matching sub-patterns, but there is no way to produce these sentences unless some serious script wrapping is done around pcregrep to analyze the sub-pattern matches and convert them to sentences. That requires some serious scripting with hardcoded logic probably.
> 
> There are other ways to get almost exactly what you want, if license patterns are more organized without relying on nested (named) sub-pattern matches.
> 
> Consider for example the two patterns:
> 
>     (You can apply it to the GNU (?:Library|Lesser))|(You can apply it to he GNU (?:Library|Lesser))
> 
> This enumerates the two GPL-2 and GPL2-TYPO patterns. Let's put these two in a file, say `licenses`:
> 
>     (You can apply it to the GNU (?:Library|Lesser))
>     (You can apply it to he GNU (?:Library|Lesser))
> 
> Now we can run ugrep as follows:
> 
>     ugrep -l -f licenses --format='%f matches %[GPL-2|GPL-2-TYPO]g%~'
> 
> to produce:
> 
>     file1 matches GPL-2
>     file2 matches GPL-2-TYPO
> 
> That's almost exactly what we want.
> 
> Please note that `-l` (dash ell) produces the first match found only, so don't use `-l` if multiple matches are desired.
> 
> A list of patterns and a corresponding list of names like "GPL-2" is all we need. This can be automated with a script that produces the list of patterns and the list of names from an associative array of names to patterns.

Yes, I am aware that I can write a wrapper tool which does the regex juggling.

My proposal was for ugrep to extend its existing regex processing to extract names for named captures.

Seems you consider refining the regex parsing unsuitable for ugrep.  I think I have lost hope that you can be convinced on the matter - too bad :-(

**Comment by genivia-inc** [comment]
> Seems you consider refining the regex parsing unsuitable for ugrep.  I think I have lost hope that you can be convinced on the matter - too bad :-(

It is a technical issue, not by choice.

Numbered groups are no problem. The approach I've outlined earlier works reliably.

If there is a project (using PCRE2) that already reliably uses/extracts names from regexes and maps them to named sub-patterns matched, then I'd like to know so we can move forward. Otherwise, it is only a guess this could be done.

Do you have a pointer to an open source project or a blog to convince me this can be reliably done? If so, I'll reopen this issue for reconsideration.

**Comment by jonassmedegaard** [comment]
Thanks for extending output format syntax to (if I understand you correctly) support labeling numbered match by a custom label.  That will be helpful both as-is for a wrapper and also as a step towards solving this issue, it seems:

Seems from reading PCRE2 documentation related to PCRE2_INFO_NAMETABLE that PCRE2 internally ties all matches to numbers, and "named captures" really is only are named labels to those numbers. So it seems my dream is to progress from this current interface:

```shell
ugrep -r --format='%[other|GPL|BSD]g:%F%N%O%~' -f licenses/pattern_with_groups_GPL_BSD myproject
```

...to this:

```shell
ugrep -r --format='%[other|*]g:%F%N%O%~' -f licenses/pattern_with_groups myproject
```

> If there is a project (using PCRE2) that already reliably uses/extracts names from regexes and maps them to named sub-patterns matched, then I'd like to know

Not sure, but this seems like such an example: https://github.com/Cisco-Talos/clamav-devel/commit/fd6af5

**Comment by jonassmedegaard** [comment]
Here is another code example which seem to do the needed lookup of names in a compiled regex: https://github.com/BurntSushi/rust-pcre2/blob/1cc3194/src/ffi.rs#L106

Comment for that code chunk says "Build and return an ordered sequence of all capture group names in this compiled regex" which sounds promising to me...

**Comment by genivia-inc** [comment]
The leads look promising. I'll take write some test cases.

Here are my thoughts if this works out:

For the `--format` fields, `%g` currently shows one (i.e. the first) numbered sub pattern match or just `1` by default. Perhaps we need a new field, say `%G`, that shows ALL numbered or named sub pattern matches separated by the optional argument provided to `%G`, e.g. `%[ and ]G` shows `GPL2 and TYPO` when both sub patterns are matched. Field `%G` is more flexible and shows none, one, or more numbered or named sub pattern matches.

**Comment by jonassmedegaard** [comment]
> The leads look promising.

Phew! That puts my hope up.

**Comment by genivia-inc** [comment]
I found the [pcre2_pattern_info](https://www.pcre.org/current/doc/html/pcre2api.html#SEC23) function that we needed to implement this feature, which now works in v2.1.4 with `--format` fields `%G` and `%g`:

       %G     list of group capture indices/names of the match (option -P).

       %[NAME1|NAME2|...]G
              NAMEs corresponding to the group capture indices of the match.

       %g     the group capture index/name of the match or 1 (option -P).

       %[NAME1|NAME2|...]g
              NAME corresponding to the group capture index of the match.

- The group capture index `%g` corresponds to the index of the sub-pattern matched among alternations in the pattern when option `-P` is not used.  For example `foo|bar` matches `foo` with index 1 and `bar` with index 2.  With option `-P`, the index corresponds to the index of the group captured in the specified pattern.
- The names specified in `%[NAME1|NAME2|...]G` and `%[NAME1|NAME2|...]g` should correspond to the index of the sub-pattern matched, starting with 1.  If no name arguments are specified or if no corresponding name is found, the index is output or the name of a named match is output for named sub-patterns when ugrep is compiled with PCRE2.
- The separator used by `%G` may be changed by preceding the field with a `%[SEP]$`.  When `[SEP]` is not provided, reverts the separator to the default separator or the separator specified by `--separator`.

An example with four named sub-patterns with names in the output separated by `with` (using `%[ with ]$`), `%G` to list the matching names (or numbers if named groups are not defined), `%$` to restore the separator to a colon, `%s` to output the separator, `%O` to output the matching line, and a final `%~` newline (note that `\n` also works, but `%~` is more convenient since shells may or may not interpret `\n` as an escaped LF):

    ugrep -P --format='%[ with ]$%G%$%s%O%~' '(?P<foo>foo)|(?P<ba>ba(?:(?P<r>r)|(?P<z>z)))' foobar.txt

this produces (ellipsis added for clarity):

    foo:...foo...
    ba with r:...bar...
    ba with z:...baz...

**Comment by jonassmedegaard** [comment]
Fantastic!

**Comment by genivia-inc** [comment]
I would like to keep in touch about your project and see if the recent ugrep additions help or hamper your project/challenge. I think it is a good use of ugrep to speed up the license search and report matches.

**Comment by jonassmedegaard** [comment]
Quoting Robert van Engelen (2020-05-29 02:03:40)
> I would like to keep in touch about your project and see if the recent ugrep additions help or hamper your project/challenge. I think it is a good use of ugrep to speed up the license search and report matches.

Thanks for your interest in my use case.  I will make sure to keep you informed!
