### ISSUE TITLE
`ugrep` does not handle `procfs` pseudofiles correctly

### ISSUE THREAD

**Issue by MrDrMcCoy** [Genivia/ugrep#350]
When I want to see mount options for a filesystem, I typically query `/proc/mounts` like so:

```shell
grep btrfs /proc/mounts
```
This does not work with `ugrep`, which returns nothing and exits with a status of  `1` for the same query:

```shell
ugrep btrfs /proc/mounts
```

However, it returns the results as expected when `cat` abuse is introduced:

```shell
cat /proc/mounts | ugrep btrfs
```

Shell redirection also yields results as expected:

```shell
ugrep btrfs < /proc/mounts
```

**Comment by genivia-inc** [comment]
Two things to consider:
1. ugrep does not read special devices by default, unlike grep. This is stated in the ugrep.com site and in the README. The reason is that devices may hang ugrep. That is not acceptable in the TUI that becomes unresponsive. Use option `-Dread` to read devices, like grep does. GNU grep hangs on named pipes when not in use, which is super annoying (some people figured this out after much frustration apparently).
2. For recursively searching and descending into directories with special devices, see an older post #193 in which approaches and solutions were discussed. It is very important to make sure ugrep never hangs, a file handle is set to non-blocking, since nonblocking is ignored for regular files (ugrep.cpp:3575). Whereas standard input from redirect or pipe is blocking unless it is a CHR or FIFO device (ugrep.cpp:3991). This does not mean that the approach is perfect.

**Comment by genivia-inc** [comment]
There are different approaches possible, each with some caveats:
1. skip empty regular files (`stat` returns zero size), even when special (like proc/mount)
2. skip empty regular files, but not when `-Dread` to read special files (like proc/mount)
3. do not skip empty files for non-recursive searches, but skip empty regular files and devices in recursive searches, unless `-Dread` to read special ones

**Comment by genivia-inc** [comment]
The following table clarifies when a search is performed. Note that GNU/BSD grep have changed over the years on how special files are dealt with e.g. when recursing open them as nonblocking.

Searching depends on **Recurse**, **-Dread**, **Regular File** if the regular file is **Empty**:
![image](https://github.com/Genivia/ugrep/assets/13117347/668d6dcd-dbee-438e-9e14-30fad082ae4d)

Note that Recurse means option `-r` or if no target are specified. Searching a dir as a target is not recursing.

An alternative approach is to perform a search for scenario N N Y Y with the possibility of getting blocked, so the recursive case Y N Y Y opens the file nonblocking. Likewise for N Y Y Y and Y Y Y Y.

The first two red N in the table describe your case. The first without -Dread which ugrep does not set by default, but GNU grep does, and the second is with -Dread. The second red N should really be a Y actually.

**Comment by genivia-inc** [comment]
Finishing up work on release 5 to include the proc FS handling changes in the Alternative table above, pending testing.

**Comment by MrDrMcCoy** [comment]
Thanks so much for this work!
