### ISSUE TITLE
background coloring artifact due to scrolling when the first character of a continuation line is matched

### ISSUE THREAD

**Issue by vinc17fr** [Genivia/ugrep#366]
A coloring bug occurs in ugrep 5.0.0 under the following conditions:
* background coloring is used for matches;
* the first character of a continuation line is matched;
* scrolling is needed (i.e. the bottom of the terminal has been reached).

For instance, consider `GREP_COLORS="mt=41"` (i.e. matches will be in white over a red background) and a 80-column terminal with a file containing the following line:
```
..............................................................................abcdef
```
(78 periods followed by "abcdef", so that `cdef` appears on the next line).

Go to the bottom of the terminal and type
```
ugrep c file
```
The `c` is colored as wanted, but the spaces after the end of the text also have a red background.

Note that this issue does not occur when matching another letter, only the letter `c` (the one that appears at the beginning of the continuation line).

This issue is reproducible under Debian/unstable with xterm and under Android/Termux.

**Comment by vinc17fr** [comment]
It seems that what `less` does to avoid the issue is to output a space followed by a backspace (there are also some escape sequences) before handling the `c`.

**Comment by genivia-inc** [comment]
Yes, that is what I was referring to. That's what I already know. It's not that complicated. What is not trivial is to decide what's best, having to emit an EL for "each time a colored item ends" seems an overkill and causes flicker. Some more experimentation may be needed to decide on a better solution than what has been tried and proposed before (that caused other problems when adopted, caveat emptor also applies to free advice).

The ugrep TUI handles color output differently, to improve the terminal output and avoid such artifacts. It outputs EL for each line ending (and does a lot more than that, to properly display Unicode wide characters and colors etc).

The normal ugrep output (not in the TUI) is not controllable, just like GNU grep source code says it can't emulate a terminal and use ncurses, since normal output can be sent to tty or piped to `less`.

**Comment by vinc17fr** [comment]
The `less` solution does not emit any EL.

**Comment by genivia-inc** [comment]
Got it. But `less` uses the terminal properties (rows, columns, etc) to "fit" text, so it "knows" when to use the trick, or perhaps I am misunderstanding when `less` does the space/backspace trick.

Grep streams the output. It is also not 100% guaranteed to work if placement decisions to use such tricks are based on column positions, because Unicode double width glyphs (e.g. emojis) take two columns and can cause miscalculations (e.g. early line wrap). The ugrep TUI checks which glyph ranges are double width using some tricks that I came up with. Streaming colored text is a different ballgame. Perhaps emitting some correcting ESC codes at the end of a line can render the background color correctly. Whatever might work this way should also be carefully tested to make sure it works when piped to `less` and `more`.

**Comment by vinc17fr** [comment]
> Got it. But `less` uses the terminal properties (rows, columns, etc) to "fit" text, so it "knows" when to use the trick, or perhaps I am misunderstanding when `less` does the space/backspace trick.

Yes, after some tests, it appears that `less` uses the space/backspace trick only at the end of the physical line, and it is able to take double-width Unicode characters into account for that. This trick is not used when no escape sequences have been sent in the line (i.e. no changes of colors). This makes sense.

> [...] Whatever might work this way should also be carefully tested to make sure it works when piped to `less` and `more`.

Well, if the output is piped or redirected to a file, I don't think that commands should try to do any terminal-related correction, because it is not possible for the command to know how the output will be used. Said otherwise, this terminal related issue should be considered only by commands that send output directly to a tty (i.e. they should first test whether the standard output is attached to a tty).

**Comment by genivia-inc** [comment]
Some observations:
- I don't see this coloring artifact appear on X11 xterm on MacOS (XQuartz)
- if I emit an EL at the end of each matching line, then the coloring artifact is removed, see case A)
- but if I emit an EL at the end of each matching line when the line ends with the match, then the match text disappears, see case B)

A) with EL before \n
<img width="569" alt="image" src="https://github.com/Genivia/ugrep/assets/13117347/427a1bb0-a88e-4cb8-950a-e09dae3ee0fb">
and also
<img width="569" alt="image" src="https://github.com/Genivia/ugrep/assets/13117347/d03ad2f7-7b29-44df-97e4-da14eb0f95cf">
without EL we get the coloring artifact (current ugrep versions, here I've used `ne` to override in my test version):
<img width="569" alt="image" src="https://github.com/Genivia/ugrep/assets/13117347/2200e74a-a968-433e-8cd5-fc095b2d7ff1">

B) with EL before \n makes the matching `c` disappear!
<img width="569" alt="image" src="https://github.com/Genivia/ugrep/assets/13117347/18f9b477-510a-4822-995d-f686c31b50c1">
without EL (current ugrep versions, here I've used `ne` to override in my test version):
<img width="569" alt="image" src="https://github.com/Genivia/ugrep/assets/13117347/ac6726f7-5f98-4418-a0f1-ed64b9457c07">

**Comment by genivia-inc** [comment]
- if I emit space+backspace+EL at the end of each matching line just before the \n, then the coloring artifact is removed but the line may scroll up unnecessarily, see case C)
- emitting space+backspace properly requires accurately tracking the column position of the screen output, which I don't think is feasible in all cases, because the output may be cat'ed to other output to the terminal, see case D)

C) with space+backspace+EL before \n
<img width="569" alt="image" src="https://github.com/Genivia/ugrep/assets/13117347/7fa25cec-469f-4098-ae92-d1b565ce789e">
without space+backspace+EL
<img width="569" alt="image" src="https://github.com/Genivia/ugrep/assets/13117347/a360b136-1dca-4487-bc36-2531c2f46e4a">

D) with space+backspace only after emitting 80 columns, which means EL is placed here without space+backspace, making the matching `c` disappear:
<img width="569" alt="image" src="https://github.com/Genivia/ugrep/assets/13117347/0738bee0-b9fa-4067-b0d1-cc7de19048f9">

**Comment by genivia-inc** [comment]
> Yes, after some tests, it appears that `less` uses the space/backspace trick only at the end of the physical line, and it is able to take double-width Unicode characters into account for that. This trick is not used when no escape sequences have been sent in the line (i.e. no changes of colors). This makes sense.

It looks like space+backspace hack may cause line skips/scrolls when streaming text to the terminal. This happens unless we don't emit \n and we know for sure we are at the end of a line. This condition cannot be 100% guaranteed for several reasons:
1. the text output may end up appended after some other text send to the terminal (it is possible, not likely)
2. not emitting a \n means that terminal screen width rescaling will not longer retain the screen content correctly (lines appended)
3. determining the column position on terminals is difficult to always get correct, because Unicode characters sets are represented differently (single width or double width) on different terminals. We also should take into account remote terminals. Some use single width, other use double width. The ugrep TUI tests this by emitting some Unicode characters then asks the terminal for the column position. This tells the TUI how various Unicode characters are displayed, which sets are single column and double column.

The `less` tool does not concern 1) and may have the problem 2), unless it emits \n before space+backspace but that does not remove the color artifact.

**Comment by vinc17fr** [comment]
> 1. the text output may end up appended after some other text sent to the terminal (it is possible, but not likely)

Indeed, but in such a case, I would say that this additional text will be more a problem than the fix potentially not working in such a case.

> 2. not emitting a \n means that terminal screen width rescaling will no longer retain the screen content correctly (lines appended)

I don't understand what you mean. If you mean "increase the terminal width" (i.e. with the effect to add columns), there is does not seem to be any issue.

> 3. determining the column position on terminals is difficult to always get correct, because Unicode characters sets are represented differently (single width or double width) on different terminals.

AFAIK, this is standard (information provided by the C library). Terminals that do not honor this standard will break curses applications. See for instance [Debian bug 1027733](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1027733) (GNU Screen uses obsolete hardcoded widths instead of the `wcwidth` function, and this has eventually been fixed in Debian).

> We also should take into account remote terminals. Some use single width, other use double width.

This means that some version of the software is not up-to-date (possible in practice), or that the terminal is buggy. Not much an issue here.

> The `less` tool does not concern 1)

It does, and it is even buggy at the point that this can corrupt the terminal status in practice, because external text (typically stderr) can be sent to the terminal in the middle of an escape sequence. See [Debian bug 949139](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949139), which I reported 4 years ago.

> and may have the problem 2), unless it emits \n before space+backspace but that does not remove the color artifact.

You do not need this \n.

For instance, in xterm, I haven't seen any issue with
```
printf foo ; for i in `seq 3` ; do printf "..............................................................................ab \bc\n" ; done | ugrep --color=always 'c'
```
i.e. I have added just a space+backspace before "c". The appended text "foo" doesn't break the fix (while it is an issue with `less`).

Note that this fix could be optional.

**Comment by genivia-inc** [comment]
I disagree. I ran various tests with various possible ways to address this, with and without \n and EL and so on. I am not going to report all the things I tried. I just broke it down in a few points. I am not happy with the results. If there was a perfect solution then I would have done this already. If it was that easy, the GNU grep devs would have done that already too, no? Instead, there's the buggy use of EL.

IMHO trying to work around a terminal bug should not be a hack that requires a much logic, especially when a pager already does this.

Just to be clear. The `less` utility controls its full screen layout, like ugrep does in the TUI, which make sense to use `wcwidth_l` and other logic. It's not an issue in the TUI and it is not an issue when using a pager.

Without TUI and pager, the text streams to the tty whatever the tty is. To calculate column position with `wcwidth_l` for every character converted from UTF-8 to UCS-4 is out of the question. It's too slow for streaming a lot of text to a tty and will be noticeable. Also tab character and control codes like \r and backspace must be taken into account, as well as a possible start from a column other than column one. It's easy when you ignore all the details.

**Comment by vinc17fr** [comment]
> I ran various tests with various possible ways to address this, with and without \n and EL and so on. I am not going to report all the things I tried.

You haven't tried the following: a space+backspace before the coloring escape sequence (without \n and EL) appears to work most of the time, and all the time if the end of line can be guessed correctly. This needs to split coloring into two parts if the colored part appears on 2 lines. At worst, the background problem would still occur when the end-of-line cannot be correctly detected. But at least this would solve the most common cases without any drawback.

Here's a testcase: [out-80col.txt](https://github.com/Genivia/ugrep/files/14746654/out-80col.txt), which gives in xterm:
![out-80col](https://github.com/Genivia/ugrep/assets/8422499/919f1a80-7b08-4e4b-824d-fa2ad6019d76)

With this testcase, each colored "cd" gets split escape sequences with an associated space+backspace, but the goal is to show that there is nothing wrong when the space+backspace occurs at a "bad" place. In practice, a split and a space+backspace would be used only when needed.

Note: using one escape sequence per colored character would even eliminate the need to detect the end of line, and this would still be very efficient. When using `grep --color .` or `ugrep --color .`, each colored character gets its own escape sequence, and you can see that this is still quite fast.

> If it was that easy, the GNU grep devs would have done that already too, no?

Perhaps because the solution has never been suggested?

> IMHO trying to work around a terminal bug should not be a hack that requires a much logic, especially when a pager already does this.

This is not a terminal bug, but the poor way VT100 was designed in the past.

> Without TUI and pager, the text streams to the tty whatever the tty is. To calculate column position with `wcwidth_l` for every character converted from UTF-8 to UCS-4 is out of the question. It's too slow for streaming a lot of text to a tty and will be noticeable.

Except that you don't output a lot of text without using a pager. I recall that the trick should be used **only** when the (u)grep output is a tty. That's why I think that using one escape sequence per colored character would be the best workaround.

**Comment by genivia-inc** [comment]
> ...appears to work most of the time...

"most of the time" is not acceptable. It's not giving POLA assurance wrt. to this problem.

> This is not a terminal bug, but the poor way VT100 was designed in the past.

Most folks find this behavior counter-intuitive and inconsistent across terminals, hence a "bug". Not all terminals behave this way. Like aqua xterm. Therefore, it's not something that can be consistently counted on as a "feature".

Another possible workaround is to define the selected line `sl=` color to include EL to erase the line with the given background for it, like `--colors=mt=yB:sl=KE` to draw a black `K` background with `E` to erase it, where `E` is a pseudo-color that emits EL (`\033[K`) which is something ugrep does not do, ignoring `E`. Adding this feature to ugrep allows an `E` to be specified when and where people want it in a color code:

<img width="569" alt="image" src="https://github.com/Genivia/ugrep/assets/13117347/7d8f3e98-b53a-424b-a4d8-ed22987d529f">

But this is still a hack to define a black background to the selected lines (or whatever color you want as background). It's not perfect. For example, when the line ends with the match, then the background is not erased:

<img width="569" alt="image" src="https://github.com/Genivia/ugrep/assets/13117347/1a2cc737-e4df-4e15-a835-38caef5b3b13">

I'm unhappy with all and any such hacks so far.

**Comment by genivia-inc** [comment]
I just thought of this, but another way to show background colors without the artifact is to invert the foreground color and leave the background color alone. For example
```console
$ ug --colors='mt=hyi' PATTERN FILE
```
shows matches in black on bright yellow (assuming the terminal background is black).
