### ISSUE TITLE
optionally filter same content multiple times

### ISSUE THREAD

**Issue by jonassmedegaard** [Genivia/ugrep#39]
Sometimes it makes sense to grep multiple filters of a file.

Example: Looking for copyright info in a PDF file - some hints may exist in the document _content_ and therefore found by grepping with `--filer=pdf:'pdftotext %'`, whereas other hints may be properly stored in XMP metadata found by grepping with `--filer=pdf:'exiftool %'`.

Would be helpful if possible to tell ugrep to not replace a filter (as I blindly assume is the current behaviour) but optionally _add_ another layer of input for same file, e.g. by using suffix "+" to extension:

```shell
ugrep -r copyright --filer=pdf:'pdftotext %' --filer=pdf+:'exiftool %' Documents

**Comment by genivia-inc** [comment]
I understand, but:
- stacked filters can be created with a simple script that is invoked as a command, rather than the command directly. This script can use unix pipes to stack multiple filters, e.g. the `stack.sh` script with the line `tool1 $1 | tool2` will work to filter with `tool1` then `tool2` to produce output to search with ugrep using `--filter='ext:stack.sh %'` (for the specified `ext` filename extension(s));
- parallel filters (i.e. multiple non-stacked filters for the same file) are a no-go: grepping is and always has been a one-pass affair to search a file at most once. So the number of files searched corresponds to the number of files specified to search. However, a simple script `both.sh` with the line `tool1 $1; tool2 $1` will output after filtering with `tool1` followed by filtering with `tool2`. The collective output is then searched by ugrep for matches with `--filter='ext:both.sh %'` (for the specified `ext` filename extension(s)).

**Comment by jonassmedegaard** [comment]
Quoting Robert van Engelen (2020-05-22 19:08:43)
> - stacked filters can be created with a simple script that is invoked as a command, rather than the command directly.
[...]
> - parallel filters (i.e. multiple non-stacked filters for the same file) are a no-go: grepping is and always has been a one-pass affair to search a file at most once.

Makes sense. Thanks for being conservative!
