### ISSUE TITLE
Bash autocompletion lost --no-confirm

### ISSUE THREAD

**Issue by jack6th** [Genivia/ugrep#394]
ugrep 6.0
--no-confirm works but it is not in the bash autocompletion list.

**Comment by genivia-inc** [comment]
The `--no-` prefix can be used with most options. So showing all `--no-` options in a list will be cumbersome, since it "spams" the output. There are a few use cases for `--no-` that we could add to the list. But I respectfully don't believe that `--no-confirm` should be one of them. It is useful in .ugrep configuration files but not so much from the command line. But I could be wrong.

**Comment by genivia-inc** [comment]
See commit [ee64cc7](https://github.com/Genivia/ugrep/commit/ee64cc7c8e066b96a01dca5fc34c7fc5795413a5)

**Comment by jack6th** [comment]
Here is how I find the --no-confirm option.
I open man page with 'man ug'.
I find --confirm option with /confirm in the man page. But I do not find --no-confirm there.
I input 'ug --no(press double TAB)' and there is no --no-confirm option.
I tried 'ug -Q --comfirm false' and it does not work.
I tried 'ug -Q --comfirm off' and it does not not work.
I tried 'ug -Q --comfirm 0' and it does not not work.
I tried 'ug -Q --no-comfirm' and it works.
If all the options available are listed in the autocompletion list and man page I think it is helpful.

**Comment by genivia-inc** [comment]
The updated completions use `--no-confirm` as I've closed this. But ug 6.0.0 still lists `--confirm` and there is not plan to release a ug update only to fix such as tiny change that has no impact.

**Comment by genivia-inc** [comment]
> I tried 'ug -Q --comfirm false' and it does not work.
> I tried 'ug -Q --comfirm off' and it does not not work.
> I tried 'ug -Q --comfirm 0' and it does not not work.

You do know that `--confirm` does not accept arguments, right? See `--help confirm` and the man page.

**Comment by jack6th** [comment]
I have tried [ee64cc7](https://github.com/Genivia/ugrep/commit/ee64cc7c8e066b96a01dca5fc34c7fc5795413a5) and it is faster.
Thanks for your work.
And I am sorry that I do not read the man page and --help from beginning to end.
But it is another issue if --confirm no longer auto-completes.
If user set --no-confirm in the .ugrep or alias, he need --confirm option to enable it on the command line.
How about list all the options available in the auto completion list ?
I do not think it is cumbersome.
aria2c list 283 options in the autocompletion.
It's simple and useful.

**Comment by genivia-inc** [comment]
> How about list all the options available in the auto completion list ?

Well it does include all short and long options. It also includes several `--no-` long options, but not all. It doesn't make sense to list all long options again with the prefix `--no-`, because these are rarely ever used on the command line. Those could be used in config files or in aliases, for example.

**Comment by genivia-inc** [comment]
Completions are updated in release 6.1.
