### ISSUE TITLE
support collections of filters (and related options)

### ISSUE THREAD

**Issue by jonassmedegaard** [Genivia/ugrep#40]
Sometimes you want to apply a set of filters - would be nice if possible to store "presets" of common collections (and-f c/zap_comments
yet related command-libe options).

To explain what I mean, take this example from `README.md`:

```shell
ugrep -r -nkw 'main' -f c/zap_strings -f c/zap_comments myproject
```

Would be useful if ugrep supported "filters" that was instead shell-parsed lines of command-line options  - e.g. using shebang `#!ugrep` to distinguish from "regular" filter files - like this (as file `$GREP_PATH/code`:

```shell
#!ugrep

-f c/zap_strings
-f c/zap_comments
# not implemented yet 
# -f c/zap_bugs
```

to apply them as a set:

```shell
ugrep -r -nkw 'main' -f c/code myproject
```

A nifty extension would be that when filter is a folder then look for file `default` inside the folder, allowing to compose a defauly set of filters from a collection:

```shell
ugrep -r -nkw 'main' -f c myproject
```

Now, that in itsef is little different from writing it all out explicitly, but the imagine adding `code` and `non-code` files for each language collecyion and introducing a meta collection called `CODE` with files `code` and `non-code` which a) includes all of the language-specific files, and adds `CODE/default as symlink to `CODE/code` - then you can can grep for "main" across any supported code language:

```shell
ugrep -r -nkw 'main' -f CODE myproject
```
Enhancing it further, a appropriate --filter options could be added for languages like SVG and Postscript using only semi-plaintext content, and things like Smalltalk where sourcecode is binary images.

**Comment by genivia-inc** [comment]
This feature is somewhat similar to `GREP_OPTIONS`, but without using it for defaults but rather explicitly. Recall that GNU grep abandoned `GREP_OPTIONS` (and the idea of configuration scripts such as `.greprc`) for the simple reason that the `grep` invocation becomes dependent on other contextual variables and thus may not produce replicable results when the environment changes.

I understand that this is a little different, since we're specifying options via a file. However, the same can be done with an `alias` or a shell script. Whenever an `alias` or a shell script can get you where you want then that should be the preferred simpler approach. A shell script can also be documented.

This isn't my sole opinion. There are many discussions on this subject and I happen to agree that simplicity is preferable over complexity, i.e. don't make options and behaviors too complex to prevent surprises ([pols](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)). A feature should have few if none "but if...".

On the other hand, your post reminds me of how shell scripts invoke an embedded script written in a programming language, e.g. Python, Perl, and SWI-Prolog. For example:

~~~
#!/usr/bin/python
...
Python program here
...
~~~
Note: this is just an illustrative example, one should actually use `#!/usr/bin/env python` rather than the above).

However, we should keep in mind that `ugrep -f -` already reads patterns from stdin:

~~~
ugrep <options here> -f - <<END
...
Patterns here
...
END
~~~

**Comment by jonassmedegaard** [comment]
Quoting Robert van Engelen (2020-05-22 19:28:51)
> This feature is somewhat similar to `GREP_OPTIONS`, but without using it for defaults but rather explicitly.

No, that was only an implementation detail (of what I could imagine).

> I understand that this is a little different, since we're specifying options via a file. However, the same can be done with an `alias` or a shell script.

ugrep currently offers to load predefined filters.

What I want is extending that do supportchain-loading _collections_ of filters.

Current shared filters could probably be implemented as aliases as well - but then they would no longer be shared.

The mechanism of loading shared presets is clever.  I would like to extend it to be equally clever across collections of filters.

I want to do "grep code/comments for FOO" (instead of "grep langA/comments or langB/comments or langC/comments for FOO"

It becomes particularly interesting when it is no 2 or five parts bu several hundred.

Yes, I can write a wrapper around ugrep to hide the complexity - what I propose is for ugrep to not be complex.

My use-case is "grep licensing for DETAIL" with hundreds of parts, sometimes relevant to break into subsets (GNU family, or Apache-2-compatible, or OSI-approved) but rarely relevant to pick as individual smallest parts (each specific license or trait).

Same for log scanning: thousands of patterns grouped in hundreds of sets - typically loading all sets at once, and often needing to exclude or only load one or a few sets - but rarely needing each individually.


...and quite relevant to use shared collections.


So please forget about identifying collections using a shebang, that clearly inspires the wrong thinking.
Instead, please look at the coomands I presented, and keep in mind that each reference may represent 50 words if typed individually on a command.

**Comment by genivia-inc** [comment]
I understand. But I think it is bad practice to enable/disable command line options and their arguments via another option that loads them. That's all I am saying.

And there is no absolute need to do so. Pretty much the same can be accomplished with an `alias` or shell script that invokes ugrep (just once I should say) to perform any complex tasks with the patterns specified with `-f`.

The script can use a `case` to create several collections of patterns and options, if you wish. A collection is selected by passing a name to the script, e.g. as the first argument, like so:

~~~
#!/bin/bash
case $1 in
  license)
    options = ...
    ;;
  copyright)
    options = ...
    ;;
  *)
    echo "Invalid class name"
    exit 1
esac
# invoke ugrep with the options and pass the rest of the script arguments to it:
ugrep $options "$@"
~~~

So `mygrep license -nk dir` searches `dir` with options `-n` and `-k`, using the collection named `license`.

**Comment by genivia-inc** [comment]
It would be great if you could participate in discussing issue #46 or have a look at it. We are discussing the possibility of introducing configuration files.

**Comment by jonassmedegaard** [comment]
I shared my 2 cents for that other issue - thanks for bringing attention to it.

For the record, I am still frustrated you closed this issue - I think it is a valid and quite useful mechanism and suspect I possibly just failed at getting it explained properly.

**Comment by genivia-inc** [comment]
> For the record, I am still frustrated you closed this issue - I think it is a valid and quite useful mechanism and suspect I possibly just failed at getting it explained properly.

I understand, and sorry for closing this issue, but the problem extending `-f` is that it breaks compatibility with GNU/BSD grep so it was a non-starter.

I do have to admit that I was wrong to state the following earlier, since we can allow this as long as the implementation is consistent and easily understandable:

> I understand. But I think it is bad practice to enable/disable command line options and their arguments via another option that loads them. That's all I am saying.

**Comment by jonassmedegaard** [comment]
Thanks for clarifying (or repeating and me missing it the first time?).

If the reason you closed this bugreport was that the option `-f` should not carry this additional functionality, then I suggest to reopen the bug and let us explore other ways to achieve the functionality proposed here.

As I tried to communicate above, using `-f` is not essential to the issue raised here.

**Comment by genivia-inc** [comment]
The master branch is updated to a 2.4.0 pre-release version with new configuration file features, see #46.
