### ISSUE TITLE
loading -f from workingdir is maybe bad practice or even potential security risk

### ISSUE THREAD

**Issue by jonassmedegaard** [Genivia/ugrep#41]
Scripting languages has had the convention of implicitly including current working dir before traversing a lookup $PATH - but have in recent time (despite the big headache that involves) shifted to _not_ use $CURDIR except when explicitly requested (e.g. by checing if path begins with `./`.

I propose to tighten the logic of the -f option to be similarly cautious. I cannot point at a concrete problem (but Python and Perl developers had the anti-pattern for 10s of years before acknowledging it was a problem).

**Comment by genivia-inc** [comment]
True, but the reasons for shells and programming languages to not implicitly include the working dir is for safety so that the intended program is executed rather than a stub in the working directory.

But this has very little to do with ugrep, that reads patterns from files located in the working directory by default, like GNU grep does. It's already by default and safe.
