### ISSUE TITLE
provide reasonable defaults

### ISSUE THREAD

**Issue by marc-guenther** [Genivia/ugrep#43]
Any software should default to the options that make most sense to the most users in most situations.

For a grep tool, I would expect it to:
- ignore hidden/ignored files (ie. no build artifacts, no vcs files, etc)
- pipe it's output through a pager (when running in a tty)
- show color output (when running in a tty)

`ugrep` already does the third, but not the other two.

This is especially frustrating, as `ugrep` apparently already supports these modes of operation, but requires you (read, every first time user of the software) to read through a massive README file in order to find out how to enable these options, then write some shell aliases for them (as apparently, there is no configuration file?).

Context: I was so used to `git grep`, and missed it a lot when we switched to Mercurial. Ordinary `grep` gives tons of unwanted results from inside `.hg` and temporary build products, which `git grep` didn't. Luckily I stumbled upon `ag`, which did exactly what I was looking for, so I never looked back to `grep`.

Unfortunately it currently has a bug where it ignores all VCS ignore files, so I looked for alternatives (there are quite a few now, and interestingly, every single one is faster then all the others!). None of these did what `ag` did.

`ugrep` was one of the alternatives I tried, and I spent the better part of an hour to make any sense of it (the `README` is, sorry, quite intimidating), and try to get it to do what seemed reasonably to me (ignore `.hg`, and ignore everything from `.hgignore`. And in the end I gave up, did a simple `ln -s .hgignore .ignore` (workaround for the `ag` bug), and now happily continue to use `ag`.

I also read the stanza about _people who have never heard of shell aliases_. That's what prompted me to spent another 20min writing this entry, as I very strongly disagree. Yes, I am very well aware of shell aliases, and, No, I do not think that every first time user should be required to write these in order to use the tool in a meaningful way. The default behaviour of the tool is what every new user sees for the first time, and if it doesn't make sense, some of them will just walk away and never look back.

**Comment by genivia-inc** [comment]
Thank you for your feedback!

> - ignore hidden/ignored files (ie. no build artifacts, no vcs files, etc)
> - pipe it's output through a pager (when running in a tty)

Simply run:

$ ./build.sh --enable-pager --enable-hidden

I'll highlight that in the README if that wasn't clear. Otherwise aliases work fine too as this is suggested by the GNU grep dev folks too rather than `GREP_OPTIONS` etc which can cause confusion. That made a lot of sense to me, quite frankly.

I agree that hidden files are probably best to ignore by default. For now, we did want to stick to GNU/BSD grep defaults. But it is easy to override the configuration as suggested above.

It's a matter of opinion, but many people that I spoke with don't believe that enabling a pager by default is a good idea, that's why I removed it by default. There are several reasons for this. One of the main complaints is that a pager restores the screen which is frustrating if you have only one terminal screen, because you can't see the results any longer after a search unless you use tmux perhaps.

> ugrep was one of the alternatives I tried, and I spent the better part of an hour to make any sense of it (the README is, sorry, quite intimidating)

The man page is for most folks the first to look at, right? The README is a full tutorial with more details and lots of examples for common and special options and features.

If you love `ag` better, that's fine. There are many things to like about it. But we needed a better tool for more challenging jobs at hand and it will continue to grow to cover many other interesting cases.

> I also read the stanza about people who have never heard of shell aliases. That's what prompted me to spent another 20min writing this entry, as I very strongly disagree.

You did a good job. I love your feedback.

**Comment by genivia-inc** [comment]
It's right at the top of the README and pretty hard to miss on how to use `./build.sh` to set the default you want:

> To produce colorized output with filename headings by default:
> 
>     $ cd ugrep
>     $ ./build.sh --enable-pager
> 
> To see the details of all build configuration options available, including
> `--with-grep-path`, `--with-grep-colors`, `--enable-color`, `--enable-pretty`,
> `--enable-pager`, `--disable-hidden`, and `--disable-mmap`:
> 
>     $ ./build.sh --help

Your feedback makes a lot of sense. So I'll update this to:

> To ignore hidden files and output the result with a pager by default:
> 
>     $ cd ugrep
>     $ ./build.sh --disable-hidden --enable-pager

**Comment by genivia-inc** [comment]
I agree that no-hidden files should be the default, like many other unix utilities and newer grep tools. Therefore, starting with v2.1.7 hidden files and directories are ignored. To search hidden files and directories, use the new short option `-.` (`--hidden`).

Thanks again for your contribution!

**Comment by marc-guenther** [comment]
Thanks for your detailed answers! :)

> It's right at the top of the README and pretty hard to miss on how to use ./build.sh to set the default you want:

Ah, well, I still completely missed that part of the README, as I'm on a Mac, and the Homebrew installation instructions were the first thing (as they should be). Compiling this from scratch didn't even cross my mind.

And of course, defaults that you have to enable manually aren't really defaults, are they? And I guess most people install through a package manager, so while the ability to bajke your own defaults into the binaries is certainly nice, it still means that every first time user has to do it manually, which is the whole point of me posting here.

> I agree that no-hidden files should be the default, like many other unix utilities and newer grep tools. [...]

Cool, thanks a lot! :)

Regarding aliases:
> [...] Otherwise aliases work fine too as this is suggested by the GNU grep dev folks too rather than GREP_OPTIONS etc which can cause confusion. That made a lot of sense to me, quite frankly.

Oh, env variables, yet another way to configure defaults... Yes, that's what I use with `less` (see below). One of the other grep tools (I think `ripgrep`) uses a configuration file, which I would prefer, as it is not dependent on which shell you use, and you don't have to spawn a new shell when you make changes to it. But it clutters your home directory with yet another dot file, so I don't know.

Regarding pagers:
> [...] One of the main complaints is that a pager restores the screen which is frustrating if you have only one terminal screen, because you can't see the results any longer after a search unless you use tmux perhaps.

Yes, I completely agree, that this would not be desirable. But that is just a setting of `less`. You already use `less -R` (to allow color), adding `-X` would turn off that behaviour.

I use these settings and very happy with them: `LESS=deFRQX`
-R allow color escape sequences
-X do not switch to second buffer, and do not clear screen
-F quit immediately if entire output can be displayed on one screen
-e quit the second time less reaches EOF
-d do not output waning message on dumb terminals
-Q quiet, never ring terminal bell

Regarding the README:
> The man page is for most folks the first to look at, right? The README is a full tutorial with more details and lots of examples for common and special options and features.

Well, erm, no, actually quite the opposite. The man page I will only use after I already have the software installed, and use it for some time, and maybe want to look up some option.

The README on the other hand is THE single most important entry point for new users. If it doesn't (at a quick glance!) contain the information they are looking for, they will move on.

Biggest problem with the current README is, while it documents everything (which is better than the opposite we see so often), that it documents everything, and it does it on one huge page. Which means you have to scroll around all the time, and it's very hard to find anything.

Take for example the Speed Comparison, which is very interesting, and something you can be proud of, but for me as a new user, I don't really care how fast it finds the results that I don't wanna see (sorry!). The first thing I need is correct output. And then, when it does that, I will be amazed every single time, wow, how does it display these results so fast, that's cool!

> Let me add that my quote was not meant to be disrespectful, [...]

Sorry about that. I obviously didn't know about those comments. And I can completely understand your viewpoint, you spent a lot of time implementing all these very cool ideas (and documented them!), and then all what people care about is if paging is enabled or disabled by default. That, I guess, could be quite frustrating.

I just wanted to point out the view of a new first time user, which can be quite different. And as you are actively looking for users (as you should be, and I hope you succeed), I thought it worth while to bring up these points.

Happy coding!

**Comment by marc-guenther** [comment]
Oh, and just to contradict everything I wrote above, [someone was just confused](https://github.com/ggreer/the_silver_searcher/issues/1382#issuecomment-637216063) about exactly the default behaviour I was proposing here...

Guess you just can't make it right for eveyone ;)

**Comment by genivia-inc** [comment]
> Oh, and just to contradict everything I wrote above, someone was just confused about exactly the default behaviour I was proposing here...

LOL. That happens from time to time. I can understand that the semantics of this option can be confusing. Perhaps `--unhide` to show hidden files might be more clear than `--hidden` and `--hide` might be more clear than `--no-hidden`. But `ag` uses `--hidden` too, so let's keep it that way.

We should still make hidden files ignored by default. Perhaps the new simple `-.` "dot option" (short for `--hidden`) with ugrep is sufficiently easy and intuitive to use.

Also, `--stats` shows what constraints were applied to the search results. But I'm now thinking that it should also show `--no-hidden` by default unless `-.` was used, i.e. showing `--hidden`, to prevent confusion.

**Comment by genivia-inc** [comment]
OK, so let's wrap this up.

> The README on the other hand is THE single most important entry point for new users. If it doesn't (at a quick glance!) contain the information they are looking for, they will move on.
> 
> Biggest problem with the current README is, while it documents everything (which is better than the opposite we see so often), that it documents everything, and it does it on one huge page. 
> 

I fully agree and it is a challenge. The first part of the README focusses on the important things which are the use cases to highlight features. I think that is OK, but I understand that it really depends on where people come from. My biggest concern to put really simple use cases up front is that one gets the impression that this is just a clone of (some other) grep. I am afraid that that will turn the target audience away.

> Which means you have to scroll around all the time, and it's very hard to find anything.

I've made navigation easier with 🔝 links at the end of each section to return to the table of contents.

> I just wanted to point out the view of a new first time user, which can be quite different. And as you are actively looking for users (as you should be, and I hope you succeed), I thought it worth while to bring up these points.

I'm not yet at this point too active to post elsewhere to encourage potential users to check out ugrep, because I want to spend time right now on getting ugrep in a really good shape first and foremost with new features. This also means getting feedback and contributions from first-time users. The worst one can do is overpromise something in a blog or article, causing potential users to turn away forever or complain. Also, when there are many users it becomes increasingly harder to change features, however minor the change is. Soon a tool becomes static. That may start a downhill trajectory of maintenance issues and even bugs that never get fixed as they become features that people actually use.
