### ISSUE TITLE
ugrep -H --xml doesn't escape XML special chars in //file/@name attribute

### ISSUE THREAD

**Issue by stephentalley** [Genivia/ugrep#430]
When ugrep creates XML output, file names with XML special characters cause the XML to be invalid:

    % file=/tmp/'foo & bar'.txt
    % echo hello > "$file"

    % ugrep -H --xml hello "$file"
    <grep>
        <file name="/tmp/foo & bar.txt">
            <match>hello</match>
        </file>
    </grep>

    % ugrep -H --xml hello "$file" | xmllint --format -
    -:2: parser error : xmlParseEntityRef: no name
    <file name="/tmp/foo & bar.txt">

These characters should be escaped when part of the file name:

    "   &quot;
    '   &apos;
    <   &lt;
    >   &gt;
    &   &amp;

This, for example, would be valid XML:

    <grep>
        <file name="/tmp/foo &amp; bar.txt">
            <match>hello</match>
        </file>
    </grep>

Not sure if there are other attributes other than `name` that should be considered as well?

Thanks again for your work on this tool!

**Comment by genivia-inc** [comment]
OK, but it makes little to no sense to encode these characters as entities in the XML output, because the general consensus is to avoid them at all cost in filenames (pathnames) to ensure there are no issues with tools and portability problems. Some tools and some OS forbid them in pathnames. As such, I never deemed it necessary to handle these in XML as special.

See also: https://en.wikipedia.org/wiki/Filename

**Comment by stephentalley** [comment]
Users don't always control the names of the files they need to grep.

But more importantly, if it is a legal file name for the file system, then it should probably be supported by the tool.

**Comment by genivia-inc** [comment]
IMO only the `&` and the single quote `'` should be escaped in XML attributes. XML is forgiving when `<` and `>` are used in attributes, which rarely if ever leads to interoperability issues as there aren't any tags in XML attributes.

**Comment by genivia-inc** [comment]
OK, I've added new fields `%i` and `%I` in the upcoming ugrep release to output pathnames in XML.

The `--xml` format will be output with `%I` instead of `%H` as follows:
<pre>
--format-begin='&lt;grep&gt;%~'
--format-open='  &lt;file%["]$%[ name="]I&gt;%~'
--format='    &lt;match%["]$%[ line="]N%[ column="]K%[ offset="]B&gt;%X&lt;/match&gt;%~%u'
--format-close='  &lt;/file&gt;%~'
--format-end='&lt;/grep&gt;%~'
</pre>
