### ISSUE TITLE
Arrow keys don't work in ConEmu

### ISSUE THREAD

**Issue by mrkingmidas** [Genivia/ugrep#435]
In TUI, the arrow keys do not work in the search field. Instead, something like `[D`, `[C`, `[A`, `[B` is inserted.
I couldn't find anything in the ConEmu settings to work around the problem. If you turn on the debug console and enter "arrows" there, it works.

In a separately launched cmd.exe it also works correctly.

Windows 10 21H1, ConEmu 230724, lang: ru, codepage: 866

**Comment by genivia-inc** [comment]
Cursor movement keys typically produce ANSI escape codes with `[A`, `[B`, `[C` and `[D` and these show up, which gives us a clue. It could be a timing issue perhaps? After the escape code is sent by the terminal, there should be another code (a `[` then a letter) within 50ms. When you try the HOME key, does it also not work to move the cursor to the far left?

**Comment by genivia-inc** [comment]
Ugrep recognizes escape sequences `O` then `A`, `B`, `C`, `D` that ConEmu appears to produce. I don't see `[A` etc.

**Comment by genivia-inc** [comment]
Done an analysis on this issue.

ConEmu does something weird to generate key events that is different to other Windows terminals (perhaps not compliant?)

The ugrep key processing (in src/vkey.cpp) calls `WaitForSingleObject(hConIn, timeout)` then `PeekConsoleInputW(hConIn, &rec, 1, &nread)` to check if a key was pressed when a console event occurred. All is good so far.

Subsequently, `PeekConsoleInputW()` returns an `INPUT_RECORD` in `rec`. We check if a key event occurred with `rec.EventType == KEY_EVENT` which is the case when a cursor key is pressed and then `rec.Event.KeyEvent.bKeyDown` is checked which must be true when a key was pressed (as opposed to released).

When cursor keys are pressed, we observe the generated escape sequences ESC `O` `A` (or other sequences, depending on the OS and terminal).

However, for the `O` and `A` after ESC we get `rec.Event.KeyEvent.bKeyDown` is false. This is different from other Windows terminals and unexpected, because we receive key presses (generated ones) to complete the sequence. This trips up the key processing routine with ConEmu.

I have a solution for this.
