### ISSUE TITLE
update git development practices

### ISSUE THREAD

**Issue by andreasstieger** [Genivia/ugrep#441]
Hello, your friendly openSUSE package maintainer here. 

As you can imagine, we try to review upstream changes prior to handing the off to the distribution users, generate a sensible changelog and correlated it to the code changes. I noticed a couple of things with your project, and would like to suggesting that you review your git practices in the following way:

* I see that you are pushing a release with a single commit. For example "Release 7.0" fc26ea0b48da58e93e1f9fe654541877d2752c35. I recommend that develop the functionality with intermediate commits that can be independently reviewed and reasoned about. In particular if they fix more than one issue and implement multiple improvements. The final release should then result in a tag.
* ffd990f also seems to fix multiple issues without the changes being broken out. 
* You seem to push development state late. If you feel like you should develop non-publicly that is okay.
* Likewise, considering https://github.com/Genivia/ugrep/compare/v7.0.3...v7.0.4 you seem to be both changing and versioning the executable without a corresponding code change. Binaries are not needed until you make a release.  Consider looking at not versioning the `.exe` files, and checking github actions for building binaries.

Thank you for your consideration.

 [![openSUSE Tumbleweed package](https://repology.org/badge/version-for-repo/opensuse_tumbleweed/ugrep.svg)](https://repology.org/project/ugrep/versions)

**Comment by genivia-inc** [comment]
Sure. Typically there are a few commits before a release. Release 7.0 was different, because I decided to rewrite an important part of the search engine, which involves a lot of off-repo dev work because there is absolutely no point in committing unfinished parts. This effort cannot be incrementally committed. During the revision, a few minor issues were reported on GitHub, which were addressed at the same time, because it affected the engine under revision.

From v7.0.3 to v7.0.4 an a-typical set of commits were made for testing by users to fix a few minor ugrep.exe problems that were aggravatingly obscure (unclear and missing API doc details), before releasing update v7.0.4 with the minute source code changes included. That could perhaps have been handled better via a separate branch that included source code changes, but these were just one line of code, so why bother.

Please note that official exe updates require a release to propagate to the winget workflow, so the only way to update official exe binaries is through a release, hence v7.0.4.

**Comment by andreasstieger** [comment]
Thanks, for the reply. I'll close this for now as there is no specific code change needed. Great tool in any case.

**Comment by genivia-inc** [comment]
Thanks. Let me assure you that all releases are official after extensive testing on our end. But testing cannot be absolutely guaranteed, so we keep adding more tests on our end. A couple of commits were made for Windows binaries in bin/win64 after 7.0.3 to prepare 7.0.4 when something in the TUI did not work on Windows, which was something specific to a user's localization and setup we believe.
