### ISSUE TITLE
Negative character class with -i flag gives unexpected result in Version 7.1.0

### ISSUE THREAD

**Issue by pdc666** [Genivia/ugrep#445]
[test.txt](https://github.com/user-attachments/files/17958936/test.txt)
Using the -i flag with a regex containing [^...] gives starnge results:
```
$ ugrep -i '.[^e].' test.txt
bad
bed
BAD
BED
```
Gnu grep gives the result I expect:
```
$ grep -i '.[^e].' test.txt
bad
BAD
```
Adding the -P flag gives the correct result in ugrep:
```
$ ugrep -iP '.[^e].' test.txt
bad
BAD
```

**Comment by genivia-inc** [comment]
That's weird. Thanks for reporting.

The match result is fine with option `-U` to match ASCII only. So it is a problem somewhere down in the Unicode negative character class conversion/handling.

**Comment by genivia-inc** [comment]
Nope. It is not a problem with the RE/flex regex engine, because the DFA for pattern `b[^e]d` to match case insensitive UTF-8 is correct as it excludes `e` and `E`:
![image](https://github.com/user-attachments/assets/024cef56-7f7b-4cfb-a05a-928e39590959)

Can't be something

**Comment by genivia-inc** [comment]
An easy fix is in place and will release an update soon. Can't believe why I missed this problematic logic flow that cancels out.

**Comment by genivia-inc** [comment]
One annoying thing about GNU grep is that it refuses to accept `-i 'b[_-z]d'`. But `'b[_-z]d'` without option `-i` is fine, which means that you cannot simply add `-i` without running into an error. The reason is that it converts `'b[_-z]d'` to upper case `'B[_-Z]D'` first, which has an invalid ASCII range.

This is avoided in RE/flex and ugrep, but we should take a closer look at making sure ugrep accepts (negative) character class ranges that GNU grep accepts.
