### ISSUE TITLE
Per-directory configuration?

### ISSUE THREAD

**Issue by rrthomas** [Genivia/ugrep#46]
Some other similar utilities such as `sift` have the very useful feature of having a per-directory configuration file, which is searched for in the same way as `.git`, i.e. in the current directories, then in parent directories. This provides a convenient way to set up search parameters on a per-project basis.

An alternative (or complement) would be a `UGREP_OPTIONS` variable, like `GREP_OPTIONS` for GNU grep, which could be combined with something like `direnv` to achieve the same result.

Forgive me if I've overlooked equivalent functionality in ugrep, which I continue to enjoy getting to greps with (err, getting to grips with!).

**Comment by genivia-inc** [comment]
Clearly this issue is open for discussion. We have a great opportunity to design something new and nice. The discussion and suggestions are quite useful to focus on a good design, considering what works, what may cause trouble, and what ultimately could become confusing, resulting in problems for users. We may want to follow the coveted *principle of least astonishment* (PoLS).

When ugrep is used in a shell script then it must produce the results that are expected by the script.

**If ugrep produces results that differ from grep, because a configuration file exists somewhere that affects the results, then we miserably failed to offer a safe and reliable alternative to grep. In fact, most other grep tools that claim to be alternatives to grep really aren't safe and reliable alternatives at all, because of this.**

If configuration files affect the search results then people are likely still going to use two different search tools: one for use in their terminal and another one for shell scripts. So we can no longer rename `ugrep` to `grep` and `egrep`.

Now, I would argue that it is great to have a configuration file as long as it restricts the defaults to options that do not result in conflicts with command line options or lead to situations where it is difficult to discern what is going on, i.e. when it becomes difficult to understand why search results are missing or when search results are different than expected. We should be very concerned about introducing annoying "gotchas". That would mean that our PoLS design miserably failed. This sounds obvious, but all things considered it isn't really that obvious. So let's explore this.

Let me start with my 2 cents on this. I'm thinking that when we reduce the option defaults that can be specified in a configuration file to the following category then we should definitely be OK:
- the cosmetic terminal display output options `--color`, `--colors=COLORS`, `--pager`, `--pretty` and `--heading` since these only affect terminal display output
- the query UI `--no-confirm` option
- the hidden files and directories search option `--hidden` and `--no-hidden`.
- options with long arguments, when typically specified repeatedly and when their absence has no meaning or has a negative impact on the results; I can think of only one which is `--filter=COMMANDS` for example to search PDF files with `--filter='pdf:pdftotext % -'`

The next category of options are "could be OK" to use as configuration defaults, because these can conflict with the search options given on the command line, but this does affect the search results with potential detrimental effects when running grep in shell scripts, configurations scripts, Makefiles etc:
- exclude files and directories from searches, such as `--ignore-files` to ignore files and directories specified in files like `.gitignore` in recursive searches
- other related options `--exclude=GLOB`, `--exclude-dir=GLOB`, `--exclude-from=FILE`, and `--exclude-fs=MOUNTS` and also their overriding forms `--exclude=!GLOB` and `--exclude-dir=!GLOB`

The third category is really bad, because there is no easy way to override them on the command line:
- all options that produce different search results or those that affect matches, such as `-n`, `-v`, `-C`, `-i`, `-w`, etc.
- option `-I` (ignore binary)
- options that affect recursion, like `-R` and `-S` (follow symlinks) and `-p` (ignore symlinks) that affect the search
- all max options like `-m` (max lines), `--depth`, etc.

For the second category another problem is that all exclusions take priority over inclusions. So when you specify on the terminal `ugrep --glob='**/backup/**'` to search files in backup directories, then the exclusion `--exclude-dir=backup` or `--exclude-dir=bak*` when defined by default removes all matches and no results are produced. Just something to be aware of that can easily happen and can lead to frustration. Furthermore, we already have an option `--exclude-from=FILE` to enforce gitignore-style exclusions. Yes, it is an option to remember, but we at least know what is going on.

For the third category the problems are far worse and obvious. I understand that people want to define ways to produce results without thee effort of having to remember command line options, but on the other hand it is more frustrating when trying to revert them from the given defaults. It's mentally more straining to remember their "undo" variants. Consider for example option `-i` (ignore case) when defined as a default in a configuration file. There is no standard option to disable case-insensitive search, other than us defining a new long option `--no-ignore-case`. However, this option is mentally confusing because it has a double negation in its name. But we need such an option if we allow configurations to defined `-i` (ignore case) by default, to be able to override the default on the command line. And no, we cannot use `-I` like sift because `-I` has a common meaning in grep tools already (ignore binary). That is something I don't like about sift, since it reduces the number of useful short options significantly and assigns new meanings to the ones that are pretty standard.

Of course, we can define a new option perhaps `--raw` that removes all defaults. But how easy is this to remember to use when results are missing when we don't even know that something is missing?

I would rather consider the opposite, say `--config` to read a configuration file. Since that won't be used with ugrep in scripts, using ugrep in scripts should be safe and reliable.

For our discussion I came up with the following suggestion for a configuration file that can be placed in the user's home directory or in a local directory where it affects the `ugrep` command:
~~~
# ugrep run commands config file
#
# a command may start with an optional no- prefix to disable and is one of:
#   color
#   colors=COLORS
#   confirm
#   decompress
#   filter=COMMANDS
#   filter-magic-label=LABEL:MAGIC
#   heading
#   hidden
#   pager
#   pretty

################################################################################
#
# SAFE AND USEFUL DEFAULTS
#
################################################################################

# the color scheme to use by default (also enables color by default)
colors=cx=hb:ms=hug:mc=ib+W:fn=h35:ln=32h:cn=1;32:bn=1;32:se=+36
# the argument is a colon-separated list of one or more parameters `sl='
# (selected line), `cx=' (context line), `mt=' (matched text), `ms=' (match
# selected), `mc=' (match context), `fn=' (file name), `ln=' (line number),
# `cn=' (column number), `bn=' (byte offset), `se=' (separator).  Parameter
# values are ANSI SGR color codes or `k' (black), `r' (red), `g' (green), `y'
# (yellow), `b' (blue), `m' (magenta), `c' (cyan), `w' (white).  Upper case
# specifies background colors.  A `+' qualifies a color as bright.  A
# foreground and a background color may be combined with font properties `n'
# (normal), `f' (faint), `h' (highlight), `i' (invert), `u' (underline).

# enable/disable color by default
color
# no-color

# enable/disable query UI confirm
confirm
# no-confirm

# enable/disable decompression by default
# decompress
no-decompress

# search PDF files
filter=pdf:pdftotext % -
# search any PDF file even when no pdf extension is present
# warning: this significantly reduces performance!
# filter-magic-label=pdf:%PDF-

# enable/disable headings by default
# heading
no-heading

# enable/disable searching hidden files and directories by default
# hidden
no-hidden

# enable/disable a pager by default
# pager=less -R -X
no-pager

# enable/disable pretty output by default
# pretty
no-pretty
~~~
And perhaps the following, if configurations are loaded explicitly with an option like `--config`.
~~~
################################################################################
#
# PROBABLY BAD DEFAULTS
#
################################################################################

# load patterns from the following files
# file=c++/zap_comments
# file=c++/zap_strings

# exclude files and directories specified in the following files when encountered in recursive searches
# ignore-files=.ignore
# ignore-files=.gitignore

# exclude files and directories specified by the following gitignore-style files
# exclude-from=~/.gitignore
# exclude-from=~/.ignore

# exclude files and directories that match the following gitignore-style globs
# exclude=a.out
# exclude=Makefile*
# exclude-dir=backup

# override the exclusions by including the following files and directories
# exclude=!Makefile.am
# exclude-dir=!/**/archived/backup
~~~
I hope this offers some interesting food for thought.

**Comment by rrthomas** [comment]
@genivia-inc thanks for this thoughtful analysis. It's a good point you make that ugrep is aiming (unlike many other tools, as far as I can tell) to work well both as an interactive tool (which is the niche that most "grep replacements" seem to aim at) and for batch use.

Splitting configuration options into groups could be difficult to understand. For example, what happens if a certain option is not permitted in a configuration file: is it ignored? Does ugrep stop with an error?

I can see a couple more options here:

1. Ignore configuration files by default in non-interactive mode. But there's a problem with how ugrep determines it is being used interactively: it can only be heuristic.
2. Make it depend on the name with which ugrep is run: if it's run as any standard name (grep, egrep etc.) then it should behave as closely as possible to that binary. But further it should have two names of its own, say, "ugrep" for "ignore configuration files" and "ug" for "use configuration files". Then it's very clear which way you're running it. (Of course, you can layer shell aliases on top of both of these.)
3. I think that both having comprehensive "opposite" options is a good idea, so that every "--foo" should have a "--no-foo" and vice versa, where that makes sense. Similarly, for belt-and-braces scripting, something like "--raw" is a good idea (but that could be provided by the naming scheme I mention above in 2).

**Comment by jonassmedegaard** [comment]
I think git is cool in being context-dependent.  But I think an important detail of that is that it _requires_ an explicit context and need to be told explicitly if it should operate without such context.
Example: Try run `git diff foo bar` outside of a git - it will fail.  You need to do `git diff --no-index foo bar` to make it work.

If you want ugrep to be like git then do so, but do it _consistently_ - otherwise let it behave like grep which is to say it is _not_ context-dependent.

**Comment by jonassmedegaard** [comment]
heck, you could install a git-ugrep wrapper for git, and have the best of both worlds...

**Comment by genivia-inc** [comment]
Thanks @rrthomas

> 1. Ignore configuration files by default in non-interactive mode. But there's a problem with how ugrep determines it is being used interactively: it can only be heuristic.

Good point. There is only a simplistic heuristic way to determine interactive use (terminal stdin and perhaps also stdout could be considered), so it is never guaranteed. This could be a problem when you run a search interactively and then pipe it out to a command or pipe more data from stdin, possibly giving different results based on config settings, which would be one of those gotchas.

> 2. Make it depend on the name with which ugrep is run: if it's run as any standard name (grep, egrep etc.) then it should behave as closely as possible to that binary. But further it should have two names of its own, say, "ugrep" for "ignore configuration files" and "ug" for "use configuration files". Then it's very clear which way you're running it. (Of course, you can layer shell aliases on top of both of these.)

Yes, I would argue that names should affect basic options (`-E` for `egrep`, `-F` for `fgrep`, `-G` for `grep`) which is the case in the latest release. A config file should not be read in those cases, as if `--raw` is in effect. However, I worry though that this approach won't work with aliases. If someone aliases `egrep` to run `ugrep`, then their `egrep` command behaves differently than a symlinked or renamed `egrep`. I can think of scenarios where this screws up badly.

Allow me to argue that we can turn this on its head by adding a new option `--config=FILE` to read a config file (or a default config file when `FILE` is not specified), so that an aliased command that is interactively used can simply use `--config=FILE`. This should be very clear to the user as to what is going on and it will not affect batch use at all, which is good and what we want to achieve perhaps. Also, a config file that is explicitly loaded would be allowed to define any settings without restrictions. Further, any other command line options should be parsed after the config file is loaded, to allow overriding, e.g. `ugrep --hidden --config=conf` searches hidden files, even if `conf` defines `--no-hidden`.

> 3. I think that both having comprehensive "opposite" options is a good idea, so that every "--foo" should have a "--no-foo" and vice versa, where that makes sense. Similarly, for belt-and-braces scripting, something like "--raw" is a good idea (but that could be provided by the naming scheme I mention above in 2).

Yes, we already have that for most options and I'll add a few more that I have missed such as `--no-ignore-case` and `--no-line-number` for the binary true/false options. There are several options that don't make a whole lot of sense when negated, like `--no-include-from`, which should be left as is without negation.

**Comment by rrthomas** [comment]
Thanks for your further analysis.

> I worry though that this approach won't work with aliases. If someone aliases egrep to run ugrep, then their egrep command behaves differently than a symlinked or renamed egrep. I can think of scenarios where this screws up badly.

I wouldn't worry about this: I think the difference between alias and executable name is a fairly common one, and many programs change their behavior based on the latter but of course can't tell about the former.

> Allow me to argue that we can turn this on its head by adding a new option --config=FILE to read a config file (or a default config file when FILE is not specified)

I'm not sure how this works for the case of a per-project configuration file, which won't be at a consistent location. You could introduce a special notation for this, but then you have another problem. The "grep replacements" we're discussing mostly support this sort of "per-project" configuration for a good reason: it's really useful! And, they support it implicitly, because then you don't have to configure an alias or write a script or whatever.

Hence, I think the idea of having two separate names (effectively two separate programs, but that's just an implementation detail) is fine. grep itself does this with grep/egrep/fgrep, and I don't recall having seen a complaint that someone tried to `alias egrep=grep` and it didn't work as expected. The interactive program (what I called "ug") can "do the right thing", and the scripting program (what I called "ugrep") can do the "least surprising thing". Incidentally, those who prefer not to be surprised could use "ugrep" interactively with suitable aliases and `--config` arguments; and the default `--config` argument, if any, should be per-user (again, principle of least surprise, and the way most other tools work).

**Comment by genivia-inc** [comment]
@jonassmedegaard 

> I think git is cool in being context-dependent. But I think an important detail of that is that it _requires_ an explicit context and need to be told explicitly if it should operate without such context.
> Example: Try run `git diff foo bar` outside of a git - it will fail. You need to do `git diff --no-index foo bar` to make it work.

Good point. That is perhaps the benefit of `git` as a tool that is context dependent on repos. It is more specifically tuned for such use cases. A general grep tool is designed to do one thing and do it well, without specificity. It should not be designed to (only) handle specialized use cases. Generality means that command line options can be provided to achieve certain tasks to match use cases, and by combing tools together, as in the Unix philosophy.

Talking about the philosophy, simplicity and minimalism are important. On the other hand, if a certain task is hard to achieve by combining Unix tools together or by requiring elaborate scripting, then adding new features is definitely a good idea as long as those features are relatively easy to document and understand, and are orthogonal, i.e. do not impact the behavior of other options. If a feature or option is complex to document, for example when it has caveats and exclusions, then it is probably not a good feature to have in the first place. This is the main reason I worry about the proper path forward to provide configuration files.

> If you want ugrep to be like git then do so, but do it _consistently_ - otherwise let it behave like grep which is to say it is _not_ context-dependent.

Fully agree!

**Comment by genivia-inc** [comment]
> Hence, I think the idea of having two separate names (effectively two separate programs, but that's just an implementation detail) is fine. 

Sure, but this can be achieved with an alias as a common approach to specialize a command. Have you considered `alias ug=ugrep --config=myconfig` perhaps to "do the right thing"? I can't see any gotchas or caveats with that.

More specifically, here are some considerations and choices I can think of right now:
1. The `myconfig` file is located in a working directory and/or in the home directory.
2. The working directory is checked first, then the home directory, same as sift.
3. If the file does not exist then an error will be produced.
4. We can provide an alternative, say `--config=?myconfig` to not produce any errors if `myconfig` does not exist.
5. We could allow multiple `--config`, each executed in order, to increase the specificity of the resulting search.
6. A full path `--config=path/myconfig` will be honored and take precedence.

Again, we want to make sure that any such feature should not be overly complex to document and use.

**Comment by rrthomas** [comment]
I can't see how any of the options you propose would work automatically (without a particular alias) for projects, where the configuration file is located in the top directory of the project. In particular, I can't see how to make a simple alias work for that. So that I could run "ug foo ." and pick up project-related settings if I'm in a project (by whatever criteria that is determined).

**Comment by genivia-inc** [comment]
Let me add the following for discussion:

7. Instead of `--config=FILE` allow `---FILE` as a shorthand and `---` for the default config file, also `---?FILE` will ignore `FILE` when non-existent.
8. The config files may be stored in the `.ugrep` subdirectory of the home directory, with a file called `defaults` for the defaults that the user wants to use.
9. The `--stats` report shows which config files were loaded.

With this approach, you can use `ugrep ---git` to emulate git, simply by dropping a `git` config file in the `~/.ugrep` directory. Same if you want colors and results formatted as `ag` with `ugrep ---ag` for example. The list goes on and on.

With this an alias like `alias ugit='ugrep ---git'` makes even more sense, IMO.

I neglected to mention earlier that points 1-9 assume that there are no limits on the options that the config file may have, unlike my first in-depth post. The reason being that this is safe as the options are explicitly specified, yet indirectly via a config file.

> I can't see how any of the options you propose would work automatically (without a particular alias)

I'd think that one can just add the following `ugit` script to your `bin` to define the `ugit` command:
~~~
ugrep ---git $@
~~~
Something like this can be included with the ugrep install or we leave it to the users to decide.

**Comment by rrthomas** [comment]
Sorry, I feel I'm missing something here: how would a git configuration file work? How would it determine, for example, whether the user is in a git directory?

**Comment by genivia-inc** [comment]
I should have explicitly stated in 8. that the config file is loaded from the working directory or from the home directory, which was implied by points 1 and 2 actually. Loading from the working directory provides context-dependent searching.

8. The config files may be stored in the .ugrep subdirectory of the working directory for context-dependent searching and in the home directory which is used when the config file is not found in the working directory, as per points 1 and 2.

10. The `ugrep ---` command loads the default configuration file, e.g. suggested is something like `.ugrep/default`.
11. The `ug` command is intended for interactive use and is equivalent to `ugrep ---` with the default configuration file.

> How would it determine, for example, whether the user is in a git directory?

Simply when the default configuration file in this directory defines options for context-dependent search of the git directory with `ug` as per suggestions 8, 10 and 12.

**Comment by rrthomas** [comment]
> Simply when the default configuration file in this directory defines options for context-dependent search of the git directory with ug as per suggestions 8, 10 and 12.

Sorry, I feel I'm still missing something: does this mean that the user has to put a configuration file in every sub-directory of a git repository?

**Comment by genivia-inc** [comment]
> Sorry, I feel I'm still missing something: does this mean that the user has to put a configuration file in every sub-directory of a git repository?

You suggested to take a look at sift, right? So its the same as what sift expects, unless you have a better idea.

**Comment by genivia-inc** [comment]
In addition, @jonassmedegaard had a brilliant suggestion to look into extending `-f` to define options in addition to search patterns. That breaks compatibility with grep. However, we can in fact load options explicitly with something like `--config=FILE` or perhaps short `---FILE`.

**Comment by rrthomas** [comment]
> You suggested to take a look at sift, right? So its the same as what sift expects, unless you have a better idea.

With sift, the user can just put a `.sift.conf` file in the root directory of the git repository.

**Comment by genivia-inc** [comment]
> With sift, the user can just put a .sift.conf file in the root directory of the git repository.

Same thing, if we include parent directories of the working directory (but up to some point, e.g. at least up to the home directory but not beyond). We should add features to ugrep that are generic only, not git-specific.

**Comment by rrthomas** [comment]
Right, I didn't see you mention parent directories anywhere. And in general, one would not want to search parent directories (in particular, for scripting).

**Comment by genivia-inc** [comment]
One more item that has two reasonable choices:

13a. When multiple configuration files are specified with `---CONF`, these are combined in the order specified.
13b. When multiple configuration files are specified with `---CONF`, the last in the list is used and the previous discarded.

For 13a, when `ug ---conf` is used this will either extend `ug` with more options beyond the context-dependent ones, or the context-dependent options are discarded, i.e. assuming that `---conf` overrides the defaults.

One more, which is for consistency and borrowed from sift:

14. Command line options are parsed in the following order: first the configuration file is loaded, followed by the remaining command line options.

**Comment by rrthomas** [comment]
On the whole I think configuration files should be cumulative (option 13a), with an option that can be used either on the command line or in configuration files to reset the current configuration to defaults.

**Comment by genivia-inc** [comment]
> Right, I didn't see you mention parent directories anywhere. And in general, one would not want to search parent directories (in particular, for scripting).

Perhaps you're not understanding or you need to be more clear. It is either the local working directory or a git root directory, which by the way can be a parent of the working directory. Which is it?

This is what the [sift doc](http://sift-tool.org/docs) actually says:

> ## Configuration
> ### Config file locations and format
> 
> sift allows customizations through config files. The global config is expected at $HOME/.sift.conf and a local config is used if the file .sift.conf exists in the current directory.
> 
> The config file may only contain a subset of the available options. The local configuration overrules the global configuration for all options set in the local config.

I just want to reiterate that all of the points 1-14+ in this discussion are up for public discussion based on technical arguments in support or against. These are not meant to be adopted right away or exactly as stated.

**Comment by rrthomas** [comment]
I'm sorry, I think I was unclear. What I mean is that for searching, for example, a git repository, it would be most useful to search parent directories (with the same rules as `.gitignore`), but one would not want that sort of searching on by default (in particular, for scripting).

Indeed it looks like I misunderstood how sift works. It supports `.gitignore` files in the current directory and parent directories; it does not support `.sift.conf` in parent directories, but I think it should.

**Comment by genivia-inc** [comment]
A quick update: I completed a prototype two days ago to start getting feedback with some practical use cases and to spot potential problems. This prototype implements 1, 2, 3, 7, 9, 13c, 14, 15, where 13c and 15 are added:

13c. Generate an error when multiple configuration files are specified on the command line, however `ug ---conf` is ok (normally `ug` loads the default configuration file). Only one configurations file is loaded, at the most.

15. When `ug` or `ugrep ---` is used but no configuration file is present, then generate a default `.ugrep` in the home directory after confirming with the user if that is OK.

The man page for this is quite straightforward:
~~~
NAME
       ugrep, ug -- file pattern searcher

SYNOPSIS
       ugrep [OPTIONS] [-A NUM] [-B NUM] [-C[NUM]] [PATTERN] [-f FILE]
             [-e PATTERN] [-N PATTERN] [-t TYPES] [-J [NUM]] [--sort[=KEY]]
             [--color[=WHEN]|--colour[=WHEN]] [--pager[=COMMAND]] [FILE ...]

DESCRIPTION
       The  ugrep utility searches any given input files, selecting lines that
       match one or more patterns.  By default, a  pattern  matches  an  input
       line  if the regular expression (RE) matches the input line.  A pattern
       matches multiple input lines if the RE in the pattern  matches  one  or
       more newlines in the input.  An empty pattern matches every line.  Each
       input line that matches at least one of the patterns is written to  the
       standard output.

       ugrep accepts input of various encoding formats and normalizes the out-
       put to UTF-8.  When a UTF byte order mark is present in the input,  the
       input  is  automatically normalized; otherwise, ugrep assumes the input
       is ASCII, UTF-8, or raw binary.  An input encoding format may be speci-
       fied with option --encoding.

       If  no  FILE  arguments are specified and standard input is read from a
       terminal, recursive searches are performed as if -R is  specified.   To
       force reading from standard input, specify `-' as a FILE argument.

       Hidden files and directories are ignored in recursive searches.  Option
       -.  (--hidden)  includes  hidden  files  and  directories  in recursive
       searches.

       The ug command is equivalent to ugrep ---, which allows for  customiza-
       tion with configuration files, see CONFIGURATION.
~~~
with a new section `CONFIGURATION`:
~~~
CONFIGURATION
       The  ug command is intended for context-dependent interactive searching
       and is equivalent to ugrep ---.   More  specifically,  the  ug  command
       implicitly  loads  the default .ugrep configuration file, unless a con-
       figuration file is explicitly specified with ug ---CONF.

       The ---CONF option loads the configuration file .ugrep-CONF located  in
       the  working  directory  or, when not found, located in the home direc-
       tory.  An error is produced when no configuration file was found.

       The default configuration file is .ugrep when argument CONF is  absent.

       A configuration file contains `NAME=VALUE' pairs per line, where `NAME`
       is the name of an option and `VALUE' is an argument.  The  `=VALUE'  is
       optional  and  may  be  omitted depending on the option.  No spacing is
       allowed surrounding the `='.  Empty lines and lines starting with a `#'
       are ignored.

       Command  line options are parsed in the following order: first the con-
       figuration file is loaded, followed by the remaining options.
~~~
This is what I have so far.

Note that there are no limitations on what options can be used in the configuration file. Not sure if that is a good idea.

**Comment by rrthomas** [comment]
Some comments:

7. I'm not sure of the benefit of inventing a new syntax here. `ug`, as I understand it, takes a config file by default; for `ugrep` it would be sufficient to allow `--config` not to take an argument.
13c. I still think configurations should be able to override one another, just as command-line arguments can. I agree that there are situations in which this will produce confusing results, and for those situations it should be possible to reset the current configuration.
15. Rather than suddenly have a usually non-interactive tool ask for user interaction, it would be simpler to have a command that generates a default configuration file. For `ug` there's no need to print a warning if it doesn't exist—the user might be happy with the defaults! For `ugrep`, of course there should be an error if `ugrep ---` (or with my suggestion, `ugrep --config`) finds that the file is missing. The error message could then suggest "Run `ugrep --default-config` to generate a default configuration file". (You didn't say what is in the default file, but a commented-out list of all the default settings is a common good model.)

**Comment by genivia-inc** [comment]
> I'm not sure of the benefit of inventing a new syntax here. ug, as I understand it, takes a config file by default; for ugrep it would be sufficient to allow --config not to take an argument.

The `---CONF` argument allows users to build collections, see #40.

I know where you are coming from, but this would be a powerful new feature for ugrep. For example, `ug ---licenses` performs an in-depth analysis of license information in the project. The `.ugrep-licenses` config file includes a collection of search terms to apply. This file could be made available for download for example, when it performs a generic task. Think of this as a search script, which has many possibilities and applications. Also, it virtually offers user-definable options of the form `---OPTION`. So instead of thinking about this as just another way to define and use a configuration file, it makes ugrep programmable.

> Rather than suddenly have a usually non-interactive tool ask for user interaction, it would be simpler to have a command that generates a default configuration file.

Perhaps. Either let `ug` save a default configuration file or let the user do this explicitly with `--save-config` or something like that is a minor point. Note that sift saves a config file with `--write-config` based on the current defaults (from another config file) and the options specified on the command line. We haven't yet addressed that.

Either way, the new or default configuration will be saved to `.ugrep` which offers a good start to customize the command. The saved `.ugrep` config includes suggested options, something like the following which I actually have right now in the prototype to make this more informative and easier for the user:
~~~
# ugrep configuration file to customize the `ug' and `ugrep ---' commands.
#
# Each line consists of the name of a long option followed by `=' and its
# argument, when applicable.  No spacing is allowed surrounding the `='.
#
# Empty lines and lines staring with a `#' are ignored.
#
# Try `ugrep --help [WHAT]' for more information.

### The color scheme to use
# colors=cx=33:mt=1;31:fn=1;35:ln=1;32:cn=1;32:bn=1;32:se=36
# colors=sl=:cx=hb:ms=ihc:mc=hc:fn=hm:ln=hg:cn=hg:bn=hg:se=y
### The argument is a colon-separated list of one or more parameters `sl='
### (selected line), `cx=' (context line), `mt=' (matched text), `ms=' (match
### selected), `mc=' (match context), `fn=' (file name), `ln=' (line number),
### `cn=' (column number), `bn=' (byte offset), `se=' (separator).  Parameter
### values are ANSI SGR color codes or `k' (black), `r' (red), `g' (green), `y'
### (yellow), `b' (blue), `m' (magenta), `c' (cyan), `w' (white).  Upper case
### specifies background colors.  A `+' qualifies a color as bright.  A
### foreground and a background color may be combined with font properties `n'
### (normal), `f' (faint), `h' (highlight), `i' (invert), `u' (underline).

### Enable/disable color
color
# no-color

### Enable/disable query UI confirm ESC to exit y/n
confirm
# no-confirm

### Enable/disable decompression by default
# decompress
no-decompress

### Search PDF files with the pdftotext utility
# filter=pdf:pdftotext % -
### Search any PDF file even when no pdf extension is present
# filter-magic-label=pdf:%PDF-
### Warning: this significantly reduces performance!

### Enable/disable headings for terminal output
# heading
# no-heading

### Enable/disable searching hidden files and directories by default
# hidden
# no-hidden

### Enable/disable line numbers by default
# line-number
# no-line-number

### Enable/disable a pager for terminal output
# pager=less -R
# no-pager

### Enable/disable pretty output to the terminal
# pretty
# no-pretty
~~~
A few more suggestions are probably useful to include.

The `--stats` command shows which configuration file was used and which options were enabled/disabled in that file, for example:
~~~
Searched 1 file: 1 matching
Configuration /Users/engelen/.ugrep:
  --color
  --confirm
  --no-decompress
The following pathname selections and restrictions were applied:
  --no-hidden (default)
~~~
That seems useful to have, IMO.

**Comment by genivia-inc** [comment]
> Rather than suddenly have a usually non-interactive tool ask for user interaction, it would be simpler to have a command that generates a default configuration file.

I propose the `--save-config` and `--save-config=CONF` options will do that, where:
- `--save-config` saves a `.ugrep` config file in the working directory, with several safe-to-use options that are currently set by default or explicitly with ugrep's arguments.
- `--save-config=CONF` saves the `.ugrep-CONF` file to the working directory, also with options that are currently set.
- `--save-config=-` saves the configuration to stdout.

What I mean with "safe-to-use options" are options that don't typically cause issues such as different search results, e.g `-v` is not an option saved. They can however be manually added to a config file, e.g. to support custom searches with specific `---CONF`, which in itself is a separate use case that can be covered this way.

**Comment by rrthomas** [comment]
If you simply write out the sample config file commented out, then a) it doesn't matter too much whether a particular option makes sense in a configuration file (though you should omit probably options that are actually not allowed there); similarly you can certainly add comments mentioning that particular options are not generally useful in a config file; and b) it's easy to grep (!) the file to see what settings are active (i.e. any that the user has uncommented).

**Comment by genivia-inc** [comment]
> If you simply write out the sample config file commented out, then a) it doesn't matter too much whether a particular option makes sense in a configuration file (though you should omit probably options that are actually not allowed there

No, that's not what I had intended by showing an example. The options that are set by default are enabled or disabled without commenting them out. I think it is useful to offer some hints e.g. for `--filter`.

> I'm not sure of the benefit of inventing a new syntax here. ug, as I understand it, takes a config file by default; for ugrep it would be sufficient to allow --config not to take an argument.

I think we are converging to reach consensus, so let me highlight the following.

The `--config` option loads the default configuration file `.ugrep` when present in the working directory or in the home directory.

The `--config` option has a shorthand `---`. This shorthand becomes more interesting when an argument is present as in `---CONF` as below.

The `--config=CONF` option to use a specific`.ugrep-CONF` configuration file has shorthand `---CONF`. This latter form of syntax is meant to suggest a customizable collection of options is "inserted" by name `CONF`, as if a macro is expanded. The custom options are essentially substituted into the command line. One such practical use case is #40 and I can think of other that developers would like, such as `ug ---issues` to search for source code (e.g. C++ or Python, etc with option `--file-type`) comments with TODO, FIXME, or other that the developers use to indicate development status issues. Granted, one can write a script to do this, but I think this fits better in the workflow.

**Comment by rrthomas** [comment]
Sounds good. The one thing I still haven't seen resolved is how to deal with per-repository configuration, that is, how to provide parent-directory searching. (Sorry if I missed something, but I reread, and the discussion seemed to stop in the comment above where I admitted I hadn't realised that sift does not in fact do this.) Also it would be good to have some way to deal with .gitignore, .hgignore etc. files (though that may be asking too much from an initial design; however, it's a great thing about `sift`). (It's a shame that `git grep` does not allow you to use an alternative `grep` program, or alternatively that there is no `git find` or `git ls` that could provide a suitable file list as input to a `dumb` grep. Indeed, it doesn't feel good to "have to" build this functionality into an independent tool!

**Comment by genivia-inc** [comment]
The master branch is updated to the 2.4.0 pre-release version with these new features:
- new `ug` command which is the same as`ugrep --config` to use the default .ugrep config files
- new option `--config=FILE` and abbreviated `---FILE` to load a specific config file
- new option `--save-config` and `--save-config=FILE`
- new option `--help [WHAT]` to search for matching help information among the options that are available
- updated documentation
- updated man page with new CONFIGURATION section
- improved AVX2 detection for SIMD optimization

I will hold off on creating an official 2.4.0 release until a day or so later, to give everyone some time to evaluate if this is what we want and if it works as expected.

Thanks for your suggestions and feedback!

**Comment by rrthomas** [comment]
@genivia-inc Sorry I've not had time to look at this since you posted; I'm following with interest and look forward to the new version in any case.

**Comment by genivia-inc** [comment]
@rrthomas No problem. I will upload the new 2.4.0 release today with a few more minor improvements.

**Comment by genivia-inc** [comment]
I assume everything is OK, so closing this issue for now. We can reopen this if a feature is lacking.
