### ISSUE TITLE
ugrep -z not being the default

### ISSUE THREAD

**Issue by stdedos** [Genivia/ugrep#49]
For the `ugrep` (i.e. not called as `grep`):

* Why is `-z` not the default? Nr. 1 (and paramount) target of this program should be in-place zero-conf (as shown in e.g. https://github.com/Genivia/ugrep/issues/48), and Nr. 2 should be _to search archived files_. It is even in your wiki (https://github.com/Genivia/ugrep/wiki#why-did-you-build-ugrep):
  > # Why did you build ugrep?
  > We were looking for a grep tool to quickly dig trough hundreds of zip- and tar-archived project repos with thousands of source code files, documentation files, images, and binary files. We wanted to do this without having to expand the archives, to save time and storage resources. 

  So, I am wondering why `-z` would not be a default.
* Even when `ugrep` is explicitly given a supported archive (`ugrep -FTrin PrefHashCalculator::Validate  src.git-refs_tags_83.0.4103.116.tar.gz`) it refuses to find its match. Given that I didn't want to decompress 3G source code on my disk, I was able to at least do a ramdisk, and spill it there.

**Comment by genivia-inc** [comment]
It is not the default for two reasons: 1) BSD does not enable option `-z` by default either; and 2) because there is a possibility that someone wants to search binary files that happen to match the magic bytes associated with archives and compressed files. In the second case the binary file becomes unsearchable as `ugrep` will likely throw an error.

The upcoming update also checks if the `ugrep` executable was renamed to `zgrep` and in that case option `-z` is enabled by default.

Otherwise, I suggest to define aliases e.g. `alias zgrep='ugrep -z'` will do, or simply `alias uz='ugrep -z'`.
