### ISSUE TITLE
ugrep doesn't work for perl-regexp

### ISSUE THREAD

**Issue by andalou** [Genivia/ugrep#51]
I'm using ugrep 2.3.1 on Windows 7.

If I have a file, say foo.txt

un kilo de arroz
arroz con pollo
medio kilo de pato
arroz con pato
una cucharada de sal
arroz con huevo

and I do:
ugrep "(?=.*pollo)(?=.*arroz)" foo.txt
or
ugrep -P "(?=.*pollo)(?=.*arroz)" foo.txt

I don't get any result unlike grep or pcregrep

**Comment by genivia-inc** [comment]
Sure, makes sense because this pattern has two lookaheads without anything else to match, so this produces empty matches.

Like the documentation says, empty matches are not produced unless `-Y` is used to allow empty matches:
~~~
$ ugrep -P -Y "(?=.*pollo)(?=.*arroz)" test.txt
arroz con pollo
~~~
Option `-Y` is also enabled when `ugrep` is renamed to `grep`.

This is a deliberate design choice. The reason is that empty matches are often not helpful and created by mistake in the regex pattern. Also, some patterns that may match empty are actually more useful when not matching empty, such as `a*b*c*` that produces expected results with ugrep, but not with grep.

We could add a check for cases where lookaheads are used, to enable `-Y` automatically, like when `^` or `$` are used, but I expect this to be very rare.

**Comment by andalou** [comment]
Thanks, the pattern also works with perl without any other switch, as in:

$ perl -ne "print if /(?=.*pollo)(?=.*arroz)/" test.txt
arroz con pollo

**Comment by genivia-inc** [comment]
@andalou Sure, it is the same thing.

Empty matches are perfectly valid. But empty matches are disabled by default in ugrep, because the results that people get with empty matches are almost always bad, e.g. showing every line in the input, unless the pattern is anchored with `^` and/or `$`: .ugrep allows empty matches by default when the pattern has a `^` or `$` anchor, but otherwise it is disabled.

This has nothing to do with PCRE or Perl, since these are simply regex libraries. These libraries support flags to disable empty matches too.

If you want empty matches enabled by default, use the v2.4.0 updated version with the new `ug` command. Define your `.ugrep` configuration file with the line `empty`.

We think it is perfectly fine to require `-Y` (`--empty`) in this case because you have a pattern consisting only of lookaheads and therefore it always produces an empty match for sure. In ugrep, grep, pcregrep etc this still shows a line but the line has nothing highlighted, which is what is meant by an empty match.
