### ISSUE TITLE
Build failure on Ubuntu 18 wiht error /usr/bin/ld: cannot find -lboost_regex

### ISSUE THREAD

**Issue by alex-bender** [Genivia/ugrep#67]
These two commands didn't help hence the issue:
```
$ autoreconf -fi
$ ./build.sh
```
```Making all in src
make[2]: Entering directory '/home/alex/src/ugrep-2.5.3/src'
g++ -std=gnu++11  -Wall -Wextra -Wunused -O2  -L/usr/lib -L/usr/lib -L/usr/lib -L/usr/lib -L/usr/lib -L/usr/lib -o ugrep ugrep-ugrep.o ugrep-glob.o ugrep-output.o ugrep-query.o ugrep-screen.o ugrep-stats.o ugrep-vkey.o ugrep-zopen.o -lpthread ../lib/libreflex.a -lpcre2-8  -lboost_regex
/usr/bin/ld: cannot find -lboost_regex
collect2: error: ld returned 1 exit status
Makefile:385: recipe for target 'ugrep' failed
make[2]: *** [ugrep] Error 1
make[2]: Leaving directory '/home/alex/src/ugrep-2.5.3/src'
Makefile:459: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/alex/src/ugrep-2.5.3'
Makefile:359: recipe for target 'all' failed
make: *** [all] Error 2
Failed to build ugrep: please run the following two commands:
$ autoreconf -fi
$ ./build.sh
```
Seems that `sudo apt-get install libboost-all-dev` fixes this problem but issue https://github.com/Genivia/ugrep/issues/63 stops build.
> defining the macro as documented in lz4 
helps.
Thanks

**Comment by genivia-inc** [comment]
What is the error produced by `autoreconf -fi` that prevents it from running?

If `./autoreconf -fi` does not work then try this:
~~~
touch config.h.in
~~~
After this, the following step is still needed::
~~~
./build.sh
~~~
which runs `./configure` and the tests.

Otherwise you may not be able to compile ugrep because libraries are not detected properly and SIMD hardware capabilities may not match those of the machine, which may result in runtime aborts.

**Comment by alex-bender** [comment]
Autoreconf -fi did not produce any error.
I had to install `libboost-all-dev` package and fix `ugrep/src/zstream.hpp` file in order to be able to build it

**Comment by genivia-inc** [comment]
Thanks for your help and feedback.

Installing Boost (for Boost.Regex) should not be necessary. It's a second possible choice when PCRE is not installed to enable option `-P`. Boost is huge!

I would like to understand the problem to offer an easy solution.

Git does not preserve file timestamps. That can mess up autoconf. The recommended method to work around this is `autoreconf -fi`. Some also had success with the following steps:
~~~
touch config.h.in
touch Makefile.in
./build.sh
~~~
Have you tried that?

**Comment by alex-bender** [comment]
So I've uninstalled libboost (not sure it it was  properly handled because I didn't get my initial error)
then I've tried to `touch` these two files, but sill I have problems with `LZ4_DECODER_RING_BUFFER_SIZE`

**Comment by genivia-inc** [comment]
> So I've uninstalled libboost (not sure it it was properly handled because I didn't get my initial error)
> then I've tried to touch these two files, but sill I have problems with `LZ4_DECODER_RING_BUFFER_SIZE`.

I understand. I plan to release an update later today that works around the missing lz4 library API macro `LZ4_DECODER_RING_BUFFER_SIZE`, which is supposed to be defined in `lz4.h`.

**Comment by alex-bender** [comment]
Nice to hear that. it is worth mentioning in readme that you have Dockerfile as well, I've discovered it too late, haha

**Comment by genivia-inc** [comment]
I successfully worked around the automake problems on a test machine without automake installed, after updating the `build.sh` script by adding a few more `touch` commands. It would help a lot if you could try this too on your machine to confirm this works (hopefully):
~~~
git clone https://github.com/Genivia/ugrep
cd ugrep
./build.sh
~~~
What has changed: after researching this issue again without finding any practical solutions to this problem except for mostly online complaints about this common problem with automake and git, I figured that the method with `touch` that I already had in place should in principle work. But the `build.sh` script was missing some other files to `touch`, such as `aclocal.m4` and `configure`. I also added `sleep 1` just to make sure that file timestamps differ in case the timestamp resolution is poor.

Thanks for helping out.

**Comment by alex-bender** [comment]
I've launched the ./build.sh and it works.
but having test failed due to the
`option -z is not available in this build configuration of ugrep`
`Error: ugrep --sort -z -c Hello archive.cpio failed`

**Comment by genivia-inc** [comment]
Zlib should be installed in order to use option `-z`. In fact, the test script executed with `make test` omits all compression tests automatically when the `config.h` file has no `HAVE_LIBZ 1` indicating that zlib is not available. This is indicated when `make test` starts which shows support or no support for certain libraries.

This means that for some reason your build did not start clean or was compiled without configure's `config.h`.

**Comment by alex-bender** [comment]
ok, so at first I've run `./configure`, it showed that `libzma not found: ugrep option -z won't decompress .lzma and .xz files`
and `checkin if lzma is wanted... yes`
then `./build.sh` which shows `Have liblzma? no`
and then test failed.
Also I've done `make clean` but the result remains the same.
Should we open new issue?

**Comment by genivia-inc** [comment]
It helps to understand why this fails in your case when no one else has this issue. Our tests with and without combinations of libraries installed work fine too, e.g. with `./build.sh --without-zlib` to disable zlib (as suggested by `./build.sh --help`). This all passes the tests since `config.h` is updated accordingly.

What does `make test` show on screen for the first lines? For example
~~~
ugrep 2.5.4 x86_64-apple-darwin16.7.0 +avx2 +pcre2_jit +zlib +bzip2 +lzma +lz4
Have libpcre2? yes
Have libz? yes
Have libbz2? yes
Have liblzma? yes
Have liblz4? yes
~~~

**Comment by alex-bender** [comment]
`make test` results into
```
ugrep 2.5.4 x86_64-pc-linux-gnu +avx2
...
```

**Comment by genivia-inc** [comment]
But what does `test make` show?

Here is my test with for example lzma removed with `./build.sh --without-lzma` as if LZMA was not installed:
~~~
ugrep 2.5.4 x86_64-apple-darwin16.7.0 +avx2 +pcre2_jit +zlib +bzip2 +lz4
Have libpcre2? yes
Have libz? yes
Have libbz2? yes
Have liblzma? no
Have liblz4? yes
~~~
Works like a charm.

**Comment by genivia-inc** [comment]
Ah, I see in your case this is because zlib is not installed, not lzma.

I will update the `make test` right now to detect this.

**Comment by genivia-inc** [comment]
The updated ugrep v2.5.5 should fix the `make test` issue when zlib and/or other compression libs are missing.

**Comment by alex-bender** [comment]
Thanks a lot!
**ALL TESTS PASSED**
