### ISSUE TITLE
CRLF replace with LF

### ISSUE THREAD

**Issue by BiBi-Abc** [Genivia/ugrep#71]
I was testing out ugrep, when I noticed something odd.

Using this command:
```
ugrep.exe "hello\r\nworld" testfile.txt
```

on `testfile.txt`, which uses CRLF line ending:
```
hello
world
```

doesn't produce any results. However, changing the SEARCH from `hello\r\nworld` to `hello\nworld` but **LEAVING THE FILE THE SAME**, produces a result.
This behavior could be bad if somebody wants to ONLY match `\r\n` line endings.

**Comment by genivia-inc** [comment]
Try option `-U`.

**Comment by BiBi-Abc** [comment]
I tried it and it works! Thank you.

**Comment by genivia-inc** [comment]
There are no newline replacements or hidden rules for matching end of lines. What you search for is what you get.

However, files can be opened on Windows in binary mode with `-U`, otherwise files are opened in normal read-only mode by default. In the latter case, the normal read-only mode, Windows replaces `\r\n` with `\n`. If you don't want that then use `-U` for binary matching "as-is".

So matching pattern `"hello\nworld"` works as should be expected (I think you meant `\n` instead of `\r`).

Hope this helps.
