### ISSUE TITLE
"ugrep: warning: cannot read..." in v3.0

### ISSUE THREAD

**Issue by paoloschi** [Genivia/ugrep#72]
If I search as _user_ in a file of which _root_ is the owner but can still be read by _others_, I notice this different behavior from the previous release:
I take as an example the file
```
-r--r--r-- 1 root root 2,2K  2 mag 16.26 /usr/share/applications/cups.desktop
```
and the difference here on VoidLinux, is as follows

__ugrep v2.5.6__  
```
BUILD/ugrep-2.5.6 $ bin/ugrep Exec /usr/share/applications/cups.desktop
Exec=xdg-open http://localhost:631/
```

__ugrep v3.0__  
```
BUILD/ugrep-3.0 $ bin/ugrep Exec /usr/share/applications/cups.desktop
ugrep: warning: cannot read /usr/share/applications/cups.desktop: Operation not permitted
```

is it to be understood as an introduced change of permission management in 3.x or is it a mere regression?

**Comment by genivia-inc** [comment]
Hmm. The only difference that I can think of is opening of files with `open` instead of `fopen`:
~~~
inline int fopen_s(FILE **file, const char *filename, const char *mode)
{
#if defined(HAVE_F_RDAHEAD) || defined(O_NOATIME)
  int fd = open(filename, O_RDONLY | O_NOATIME);
  if (fd < 0)
    return errno;
#if defined(HAVE_F_RDAHEAD)
  if (fcntl(fd, F_RDAHEAD, 1) < 0)
    return errno;
#endif
  return (*file = fdopen(fd, mode)) == NULL ? errno : 0;
#else
  return (*file = fopen(filename, mode)) == NULL ? errno : 0;
#endif
}
~~~
Perhaps the `fcntl()` operation fails on this file? Is this something that you can check?

**Comment by genivia-inc** [comment]
Try the master branch v3.0.1 update by cloning and `./build.sh`.

**Comment by paoloschi** [comment]
I apologize for the delayed response; unfortunately I do not have the expected result:

```
BUILD/ugrep $ bin/ugrep -V
ugrep 3.0.1 x86_64-pc-linux-gnu +avx2 +pcre2_jit +zlib +bzip2 +lzma +lz4
License BSD-3-Clause: <https://opensource.org/licenses/BSD-3-Clause>
Written by Robert van Engelen and others: <https://github.com/Genivia/ugrep>

BUILD/ugrep $ bin/ugrep Exec /usr/share/applications/cups.desktop
ugrep: warning: cannot read /usr/share/applications/cups.desktop: Operation not permitted
```

I really did not think that I had exposed a particularly specific case, difficult to reproduce.
my feedback does not limit to the particular file I brought as an example above!
as I wrote, in a linux system all the files that the user doesn't own but can access in read-only mode are processable up to ugrep 2.x but no more with ugrep 3.x
I find it hard to believe that it can only happen to me...

```
BUILD/ugrep $ ls -l /etc/hosts                                                                       
-rw-r--r-- 1 root root 787169  2 ott 10.14 /etc/hosts

BUILD/ugrep $ bin/ugrep localhost /etc/hosts
ugrep: warning: cannot read /etc/hosts: Operation not permitted
```

**Comment by genivia-inc** [comment]
This is a strange issue indeed. The only change is to use `open` and `fdopen` instead of `fopen`, with read permissions as before, with an extra option `O_NOATIME`. I think the `O_NOATIME` may be to blame, though I tried this on my systems but do not get a warning.

Looks like the same issue with GNOME:

https://gitlab.gnome.org/GNOME/glib/-/issues/874

and MongoDB:

https://jira.mongodb.org/browse/SERVER-7933

It's a shame not to be able to use `O_NOATIME` because sorting the output by access time (`used`) will produce unreliable results as the file access times are updated in the process.

**Comment by genivia-inc** [comment]
I've removed `O_NOATIME` and updated the master branch for the tentative v3.0.1. Perhaps you can give this a try?

**Comment by paoloschi** [comment]
you have caught exactly the culprit! I confirm that with this modification the ugrep access to the _root_ ownership files takes place again without any complaints:
```
BUILD/ugrep $ bin/ugrep -V
ugrep 3.0.1 x86_64-pc-linux-gnu +avx2 +pcre2_jit +zlib +bzip2 +lzma +lz4
License BSD-3-Clause: <https://opensource.org/licenses/BSD-3-Clause>
Written by Robert van Engelen and others: <https://github.com/Genivia/ugrep>

BUILD/ugrep $ bin/ugrep localhost /etc/hosts                     
::1  TC-M73 localhost.localdomain localhost ip6-localhost
127.0.0.1  TC-M73 localhost.localdomain localhost
```
thanks to you
interesting your description of why having to omit the `O_NOATIME` option is in fact so unconvenient... pity indeed

**Comment by genivia-inc** [comment]
The releases are updated.
