### ISSUE TITLE
Duplicate slash in results path

### ISSUE THREAD

**Issue by stdedos** [Genivia/ugrep#73]
```console
$ grep -Trin ffmpeg /etc/apt/
/etc/apt//sources.list.d/jonathonf-ubuntu-ffmpeg-4-bionic.list:     1:	deb ....
```

**Comment by genivia-inc** [comment]
I am aware of this. Out of curiosity I found that BSD grep produces the same double slash output:
~~~
$ grep -l -R '' src/
src//Makefile.am
src//Makefile
...
~~~
And also pcregrep produces double slashes. But GNU grep does not.

I suppose a single slash is nicer, but it is not required. Not sure if we really must remove the extra slash that is explicitly given on the command line as there may be a modest benefit to this visual feedback?

**Comment by stdedos** [comment]
Yeah, technically anything goes:
> https://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap04.html#tag_04_11
> [...] A pathname that begins with two successive slashes may be interpreted in an implementation-defined manner, although more than two leading slashes shall be treated as a single slash.

And, if you found existing behavior, then you may argue sticking to that and/or that it somehow visually separates you what did you enter vs the rest.

However, "explicitly" given may be an overstatement: Sometimes tab-completions explicitly give the trailing slash, to signify that that is a directory that's offered (also shells like e.g. zsh tend to swallow it after no further expansion needed).

Up to you! I would make a system test though in any case to explicitly select one behavior from the other.

**Comment by genivia-inc** [comment]
I think it is nicer to remove extra (trailing) path separators from the pathnames displayed.

I'll make the change.

This will work fine because the nice thing about the current design and implementation is that the command line arguments are checked first for missing files and directories. This is done with the specified filenames "as is", i.e. exactly as specified. This gives the proper visual feedback if something is wrong, such as when `dir/` is not a directory. Those erroneous filenames produce warnings and are no longer considered for the search (note that options `--pager` and `-Q` do not permit any warnings to prevent misrepresenting the search results displayed!).

After that initial check and purging, we can remove the extra trailing separators to improve the search results displayed.

**Comment by genivia-inc** [comment]
Ugrep v3.0.4 trims the pathnames.
