### ISSUE TITLE
Number of hits not consistent

### ISSUE THREAD

**Issue by RuneBergh** [Genivia/ugrep#9]
Searching a folder of compressed logs gives me a variation of up to 40% in the number of results, both with and without -o. without -o, its even at 1/7 of the results zgrep gives, and about 1/2 with -o. Both options differ from run to run, and its never the same number anymore.

**Comment by genivia-inc** [comment]
Do you have an example? I don't see this problem at all with 1.5.5. For example:
~~~
ugrep -rzo -F 10.0.0.1 2019-01-1/2019-01-1.conn.?.log.gz | wc -l
 4500000
ugrep -rzc -F 10.0.0.1 2019-01-1/2019-01-1.conn.?.log.gz
2019-01-1/2019-01-1.conn.2.log.gz:500000
2019-01-1/2019-01-1.conn.7.log.gz:500000
2019-01-1/2019-01-1.conn.8.log.gz:500000
2019-01-1/2019-01-1.conn.5.log.gz:500000
2019-01-1/2019-01-1.conn.3.log.gz:500000
2019-01-1/2019-01-1.conn.1.log.gz:500000
2019-01-1/2019-01-1.conn.4.log.gz:500000
2019-01-1/2019-01-1.conn.6.log.gz:500000
2019-01-1/2019-01-1.conn.9.log.gz:500000
~~~

**Comment by genivia-inc** [comment]
My runs with `xargs -P8` now work fine with ugrep 1.5.5, no matter how often I try:
~~~
find 2019-01-1 -name '2019-01-1.conn.?.log.gz' -print0 | xargs -P8 -0 ugrep -z -F 10.0.0.1 | wc -l
 4500000
~~~

**Comment by RuneBergh** [comment]
Tested it on real logs, ill try and produce some similar test data that can be shared for reproduction. 

I used only ugrep with -zrFf flags , searching a month worth of bro logs.

**Comment by genivia-inc** [comment]
I've updated `src/zstream.hpp` to produce zlib decompression errors in the master branch (not the release). You can try that update to see if there are decompression errors produced by zlib. There shouldn't be any, but we need to know for sure.

**Comment by genivia-inc** [comment]
Ah, not good. I see a zlib error pop up:
~~~
ugrep -rzo -F 10.0.0.1 2019-01-4/2019-01-4.conn.*.log.gz | wc -l
ugrep: zlib error: Bad file descriptor
~~~
I don't see any problems with `-J1` but with threads this error popped up. Zlib `gzread()` should be thread safe though, but this sure makes me wonder what other thing could cause this when lots of compressed files are searched in parallel.

**Comment by genivia-inc** [comment]
Zlib `gzdopen()` is the culprit. I've overlooked using `dup()`. The zlib documentation says: *If you want to keep fd open, use `fd = dup(fd_keep); gz = gzdopen(fd, mode);`. The duplicated descriptor should be saved to avoid a leak, since `gzdopen` does not close `fd` if it fails. If you are using `fileno()` to get the file descriptor from a `FILE *`, then you will have to use `dup()` to avoid double-`close()`ing the file descriptor. Both `gzclose()` and `fclose()` will close the associated file descriptor, so they need to have different file descriptors.*

I've updated the master branch (not the release) with an updated `src/zstream.hpp` that I've tested on lots of compressed files. All looks OK now! So if you want to give it a try then download the master branch with the updated `src/zstream.hpp`.

Next I will experiment with parallel threads to run the decompressor parallel to searching, which should speed things up even further. I had disabled this feature due to a problem, which is probably caused by this issue that is corrected.

Thanks for reporting this. I may not have found this problem otherwise.

**Comment by RuneBergh** [comment]
Sorry for the low quality report without any data to reproduce on etc, and the lack of debuging, got a bit busy at work, but looks like you made sense of it all and figured it out! Awesome! And im glad to be of any help. 

I would also like to thank you for both your quick fixes and detailed explanations, i learn a lot by reading your responses. 

Ill try to build from master then.  

Looking forward to seeing some results from the testing with parallel threads for running the decompressor parallel to searching.
